/* Generated by Nim Compiler v1.6.4 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw;
typedef struct tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g;
typedef struct tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ;
typedef struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A;
typedef struct tyObject_PixieError__iGcRqvltYLQCoM1tI9cqukQ tyObject_PixieError__iGcRqvltYLQCoM1tI9cqukQ;
typedef struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw;
typedef struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content tySequence__uB9b75OUPRENsBAu4AnoePA_Content;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
typedef NU8 tyEnum_BlendMode__5LYzfbrLeWt4hzSNsGzCUQ;
struct tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw {
NU8 r;
NU8 g;
NU8 b;
NU8 a;
};
typedef struct {
N_NIMCALL_PTR(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, ClP_0) (tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source, void* ClE_0);
void* ClE_0;
} tyProc__ahx1kvZUd3gRcZmpO4ziwg;
typedef N_NIMCALL_PTR(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, tyProc__pDXYMhp3ZE9buYYnMoReoZQ) (tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source);
struct tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g {
NU8 r;
NU8 g;
NU8 b;
NU8 a;
};
struct tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ {
NF32 r;
NF32 g;
NF32 b;
NF32 a;
};
typedef NF32 tyArray__mXNbtvWKAiZn9bWV4uCjiKg[3];
typedef N_CLOSURE_PTR(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, TM__LHGo88dm0cLvmgKkpdsivQ_2) (tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source, void* ClE_0);
struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A {
NI rc;
};
typedef struct {
N_NIMCALL_PTR(NU8, ClP_0) (NU8 backdrop, NU8 source, void* ClE_0);
void* ClE_0;
} tyProc__J9aFZ4xZVYu6zZ3I9aLCdVuw;
typedef N_NIMCALL_PTR(NU8, tyProc__Cif9aofUV85UivbLssUVkAw) (NU8 backdrop, NU8 source);
struct TNimTypeV2 {
void* destructor;
NI size;
NI align;
NCSTRING name;
void* traceImpl;
void* typeInfoV1;
NI flags;
};
struct RootObj {
TNimTypeV2* m_type;
};
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  NI len; tySequence__uB9b75OUPRENsBAu4AnoePA_Content* p;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringV2 message;
tySequence__uB9b75OUPRENsBAu4AnoePA trace;
Exception* up;
};
struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA {
  Exception Sup;
};
struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw {
  tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA Sup;
};
struct tyObject_PixieError__iGcRqvltYLQCoM1tI9cqukQ {
  tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw Sup;
};
typedef N_CLOSURE_PTR(NU8, TM__LHGo88dm0cLvmgKkpdsivQ_5) (NU8 backdrop, NU8 source, void* ClE_0);
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};


#ifndef tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
#define tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content { NI cap; tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};
#endif

      N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendNormal__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_148)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(NU8, blendAlpha__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_52)(NU8 backdrop, NU8 source);
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendDarken__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_153)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source);
static N_INLINE(NU8, blend__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_157)(NU8 backdropColor, NU8 backdropAlpha, NU8 sourceColor, NU8 sourceAlpha);
static N_INLINE(NU32, min__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_14)(NU32 a, NU32 b);
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendMultiply__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_163)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source);
static N_INLINE(NU8, blend__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_167)(NU8 backdropColor, NU8 backdropAlpha, NU8 sourceColor, NU8 sourceAlpha);
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendColorBurn__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_173)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source);
static N_INLINE(tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g, rgba__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_3)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw c);
static N_INLINE(NU8, blend__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_179)(NU32 backdrop, NU32 source);
static N_INLINE(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, rgbx__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_7)(tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g c);
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g, alphaFix__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_18)(tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g backdrop, tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g source, tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g mixed);
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendLighten__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_184)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source);
static N_INLINE(NU8, blend__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_188)(NU8 backdropColor, NU8 backdropAlpha, NU8 sourceColor, NU8 sourceAlpha);
static N_INLINE(NU32, max__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_194)(NU32 x, NU32 y);
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendScreen__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_199)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source);
static N_INLINE(NU8, screen__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_56)(NU32 backdrop, NU32 source);
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendColorDodge__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_203)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source);
static N_INLINE(NU8, blend__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_209)(NU32 backdrop, NU32 source);
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendOverlay__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_214)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source);
static N_INLINE(NU8, hardLight__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_60)(NU32 backdropColor, NU32 backdropAlpha, NU32 sourceColor, NU32 sourceAlpha);
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendSoftLight__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_218)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source);
static N_INLINE(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ, color__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_19)(tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g c);
static N_INLINE(NF32, softLight__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_66)(NF32 backdrop, NF32 source);
N_LIB_PRIVATE N_NIMCALL(NF32, roof___OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZdistance_22)(NF32 x, NI y);
N_LIB_PRIVATE N_NIMCALL(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ, alphaFix__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_32)(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ backdrop, tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ source, tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ mixed);
static N_INLINE(void, slasheq___OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_40)(NF32* x, NF32 y);
static N_INLINE(tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g, rgba__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_16)(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ c);
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendHardLight__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_228)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source);
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendDifference__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_232)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source);
static N_INLINE(NU8, blend__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_236)(NU8 backdropColor, NU8 backdropAlpha, NU8 sourceColor, NU8 sourceAlpha);
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendExclusion__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_242)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source);
static N_INLINE(NU8, blend__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_246)(NU32 backdrop, NU32 source);
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendHue__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_265)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source);
static N_INLINE(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ, SetLum__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_126)(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ C, NF32 l);
static N_INLINE(NF32, Lum__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_94)(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ C);
static N_INLINE(void, ClipColor__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_97)(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ* C);
N_LIB_PRIVATE N_NIMCALL(NF32, min__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_100)(NF32* x, NI xLen_0);
N_LIB_PRIVATE N_NIMCALL(NF32, max__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_113)(NF32* x, NI xLen_0);
static N_INLINE(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ, plus___OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_78)(NF32 v, tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ c);
static N_INLINE(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ, plus___OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_74)(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ c, NF32 v);
static N_INLINE(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ, slash___OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_86)(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ c, NF32 v);
static N_INLINE(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ, star___OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_82)(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ c, NF32 v);
static N_INLINE(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ, minus___OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_90)(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ c, NF32 v);
static N_INLINE(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ, SetSat__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_140)(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ C, NF32 s);
static N_INLINE(NF32, Sat__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_131)(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ C);
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendSaturation__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_272)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source);
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendColor__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_251)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source);
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendLuminosity__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_258)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source);
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendMask__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_279)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source);
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendOverwrite__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_304)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source);
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendSubtractMask__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_284)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source);
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendExcludeMask__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_289)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source);
static N_INLINE(NU8, max__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_293)(NU8 x, NU8 y);
static N_INLINE(NU8, min__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_298)(NU8 x, NU8 y);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p);
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p);
N_LIB_PRIVATE N_NIMCALL(NU8, maskNormal__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_333)(NU8 backdrop, NU8 source);
N_LIB_PRIVATE N_NIMCALL(NU8, maskMask__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_341)(NU8 backdrop, NU8 source);
static N_INLINE(NU8, maskMaskInline__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_337)(NU8 backdrop, NU8 source);
N_LIB_PRIVATE N_NIMCALL(NU8, maskOverwrite__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_361)(NU8 backdrop, NU8 source);
N_LIB_PRIVATE N_NIMCALL(NU8, maskSubtract__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_345)(NU8 backdrop, NU8 source);
N_LIB_PRIVATE N_NIMCALL(NU8, maskExclude__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_349)(NU8 backdrop, NU8 source);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size, NI alignment);
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(void, copyMem__system_1709)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZcommon_26)(tyEnum_BlendMode__5LYzfbrLeWt4hzSNsGzCUQ e);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
extern TNimTypeV2 NTIv2__iGcRqvltYLQCoM1tI9cqukQ_;
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__LHGo88dm0cLvmgKkpdsivQ_3 = { 14 | NIM_STRLIT_FLAG, "No masker for " };
static const NimStringV2 TM__LHGo88dm0cLvmgKkpdsivQ_4 = {14, (NimStrPayload*)&TM__LHGo88dm0cLvmgKkpdsivQ_3};
extern NIM_BOOL nimInErrorMode__system_3443;
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__system_3443);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NU8, blendAlpha__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_52)(NU8 backdrop, NU8 source) {
	NU8 result;
	result = (NU8)0;
	result = (NU8)((NU8)(source) + (NU8)(((NU8) ((NU32)((NU32)((NU32)((NU32)(((NU32) (backdrop))) * (NU32)(((NU32) ((NU8)((NU8)(((NU8) 255)) - (NU8)(source))))))) / (NU32)(((NU32) 255)))))));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendNormal__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_148)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source) {
	tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw result;
	NU32 k;
	NU8 T11_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (backdrop.a == ((NU8) 0));
		if (T3_) goto LA4_;
		T3_ = (source.a == ((NU8) 255));
		LA4_: ;
		if (!T3_) goto LA5_;
		result = source;
		goto BeforeRet_;
	}
	LA5_: ;
	{
		if (!(source.a == ((NU8) 0))) goto LA9_;
		result = backdrop;
		goto BeforeRet_;
	}
	LA9_: ;
	k = (NU32)((NU32)(((NU32) 255)) - (NU32)(((NU32) (source.a))));
	result.r = (NU8)((NU8)(source.r) + (NU8)(((NU8) ((NU32)((NU32)((NU32)((NU32)(((NU32) (backdrop.r))) * (NU32)(k))) / (NU32)(((NU32) 255)))))));
	result.g = (NU8)((NU8)(source.g) + (NU8)(((NU8) ((NU32)((NU32)((NU32)((NU32)(((NU32) (backdrop.g))) * (NU32)(k))) / (NU32)(((NU32) 255)))))));
	result.b = (NU8)((NU8)(source.b) + (NU8)(((NU8) ((NU32)((NU32)((NU32)((NU32)(((NU32) (backdrop.b))) * (NU32)(k))) / (NU32)(((NU32) 255)))))));
	T11_ = (NU8)0;
	T11_ = blendAlpha__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_52(backdrop.a, source.a);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.a = T11_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NU32, min__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_14)(NU32 a, NU32 b) {
	NU32 result;
	NU32 colontmpD_;
	NU32 colontmpD__2;
	result = (NU32)0;
	colontmpD_ = (NU32)0;
	colontmpD__2 = (NU32)0;
	{
		if (!((NU32)(a) < (NU32)(b))) goto LA3_;
		colontmpD_ = a;
		result = colontmpD_;
	}
	goto LA1_;
	LA3_: ;
	{
		colontmpD__2 = b;
		result = colontmpD__2;
	}
	LA1_: ;
	return result;
}
static N_INLINE(NU8, blend__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_157)(NU8 backdropColor, NU8 backdropAlpha, NU8 sourceColor, NU8 sourceAlpha) {
	NU8 result;
	NU32 T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NU8)0;
	T1_ = (NU32)0;
	T1_ = min__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_14((NU32)((NU32)(((NU32) (backdropColor))) + (NU32)((NU32)((NU32)((NU32)((NU32)(((NU32) ((NU8)((NU8)(((NU8) 255)) - (NU8)(backdropAlpha))))) * (NU32)(((NU32) (sourceColor))))) / (NU32)(((NU32) 255))))), (NU32)((NU32)(((NU32) (sourceColor))) + (NU32)((NU32)((NU32)((NU32)((NU32)(((NU32) ((NU8)((NU8)(((NU8) 255)) - (NU8)(sourceAlpha))))) * (NU32)(((NU32) (backdropColor))))) / (NU32)(((NU32) 255))))));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = ((NU8) (T1_));
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendDarken__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_153)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source) {
	tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw result;
	NU8 T1_;
	NU8 T2_;
	NU8 T3_;
	NU8 T4_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw));
	T1_ = (NU8)0;
	T1_ = blend__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_157(backdrop.r, backdrop.a, source.r, source.a);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.r = T1_;
	T2_ = (NU8)0;
	T2_ = blend__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_157(backdrop.g, backdrop.a, source.g, source.a);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.g = T2_;
	T3_ = (NU8)0;
	T3_ = blend__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_157(backdrop.b, backdrop.a, source.b, source.a);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.b = T3_;
	T4_ = (NU8)0;
	T4_ = blendAlpha__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_52(backdrop.a, source.a);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.a = T4_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NU8, blend__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_167)(NU8 backdropColor, NU8 backdropAlpha, NU8 sourceColor, NU8 sourceAlpha) {
	NU8 result;
	result = (NU8)0;
	result = ((NU8) ((NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((NU32)(((NU32) ((NU8)((NU8)(((NU8) 255)) - (NU8)(backdropAlpha))))) * (NU32)(((NU32) (sourceColor))))) + (NU32)((NU32)((NU32)(((NU32) ((NU8)((NU8)(((NU8) 255)) - (NU8)(sourceAlpha))))) * (NU32)(((NU32) (backdropColor))))))) + (NU32)((NU32)((NU32)(((NU32) (backdropColor))) * (NU32)(((NU32) (sourceColor))))))) / (NU32)(((NU32) 255)))));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendMultiply__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_163)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source) {
	tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw result;
	NU8 T1_;
	NU8 T2_;
	NU8 T3_;
	NU8 T4_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw));
	T1_ = (NU8)0;
	T1_ = blend__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_167(backdrop.r, backdrop.a, source.r, source.a);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.r = T1_;
	T2_ = (NU8)0;
	T2_ = blend__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_167(backdrop.g, backdrop.a, source.g, source.a);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.g = T2_;
	T3_ = (NU8)0;
	T3_ = blend__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_167(backdrop.b, backdrop.a, source.b, source.a);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.b = T3_;
	T4_ = (NU8)0;
	T4_ = blendAlpha__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_52(backdrop.a, source.a);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.a = T4_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g, rgba__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_3)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw c) {
	tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g result;
	nimZeroMem((void*)(&result), sizeof(tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g));
	result.r = c.r;
	result.g = c.g;
	result.b = c.b;
	result.a = c.a;
	{
		NIM_BOOL T3_;
		NU32 multiplier;
		T3_ = (NIM_BOOL)0;
		T3_ = !((result.a == ((NU8) 0)));
		if (!(T3_)) goto LA4_;
		T3_ = !((result.a == ((NU8) 255)));
		LA4_: ;
		if (!T3_) goto LA5_;
		multiplier = ((NU32) (((NF32)(((NF32)(255.0f) / (NF32)(((NF32) (c.a))))) * (NF32)(255.0f))));
		result.r = ((NU8) ((NU32)((NU32)((NU32)((NU32)(((NU32) (result.r))) * (NU32)(multiplier))) / (NU32)(((NU32) 255)))));
		result.g = ((NU8) ((NU32)((NU32)((NU32)((NU32)(((NU32) (result.g))) * (NU32)(multiplier))) / (NU32)(((NU32) 255)))));
		result.b = ((NU8) ((NU32)((NU32)((NU32)((NU32)(((NU32) (result.b))) * (NU32)(multiplier))) / (NU32)(((NU32) 255)))));
	}
	LA5_: ;
	return result;
}
static N_INLINE(NU8, blend__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_179)(NU32 backdrop, NU32 source) {
	NU8 result;
	NU8 colontmpD_;
	NU8 colontmpD__2;
	NU8 colontmpD__3;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NU8)0;
	colontmpD_ = (NU8)0;
	colontmpD__2 = (NU8)0;
	colontmpD__3 = (NU8)0;
	{
		if (!(backdrop == ((NU32) 255))) goto LA3_;
		colontmpD_ = ((NU8) 255);
		result = colontmpD_;
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(source == ((NU32) 0))) goto LA6_;
		colontmpD__2 = ((NU8) 0);
		result = colontmpD__2;
	}
	goto LA1_;
	LA6_: ;
	{
		NU32 T9_;
		T9_ = (NU32)0;
		T9_ = min__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_14(((NU32) 255), (NU32)((NU32)((NU32)((NU32)(((NU32) 255)) * (NU32)((NU32)((NU32)(((NU32) 255)) - (NU32)(backdrop))))) / (NU32)(source)));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		colontmpD__3 = (NU8)((NU8)(((NU8) 255)) - (NU8)(((NU8) (T9_))));
		result = colontmpD__3;
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, rgbx__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_7)(tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g c) {
	tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw result;
	nimZeroMem((void*)(&result), sizeof(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw));
	result.r = ((NU8) ((NU32)((NU32)((NU32)((NU32)(((NU32) (c.r))) * (NU32)(((NU32) (c.a))))) / (NU32)(((NU32) 255)))));
	result.g = ((NU8) ((NU32)((NU32)((NU32)((NU32)(((NU32) (c.g))) * (NU32)(((NU32) (c.a))))) / (NU32)(((NU32) 255)))));
	result.b = ((NU8) ((NU32)((NU32)((NU32)((NU32)(((NU32) (c.b))) * (NU32)(((NU32) (c.a))))) / (NU32)(((NU32) 255)))));
	result.a = c.a;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g, alphaFix__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_18)(tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g backdrop, tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g source, tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g mixed) {
	tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g result;
	NU32 sa;
	NU32 ba;
	NU32 t0;
	NU32 t1;
	NU32 t2;
	NU32 r;
	NU32 g;
	NU32 b;
	NU32 a;
{	nimZeroMem((void*)(&result), sizeof(tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g));
	sa = ((NU32) (source.a));
	ba = ((NU32) (backdrop.a));
	t0 = (NU32)((NU32)(sa) * (NU32)((NU32)((NU32)(((NU32) 255)) - (NU32)(ba))));
	t1 = (NU32)((NU32)(sa) * (NU32)(ba));
	t2 = (NU32)((NU32)((NU32)((NU32)(((NU32) 255)) - (NU32)(sa))) * (NU32)(ba));
	r = (NU32)((NU32)((NU32)((NU32)((NU32)((NU32)(t0) * (NU32)(((NU32) (source.r))))) + (NU32)((NU32)((NU32)(t1) * (NU32)(((NU32) (mixed.r))))))) + (NU32)((NU32)((NU32)(t2) * (NU32)(((NU32) (backdrop.r))))));
	g = (NU32)((NU32)((NU32)((NU32)((NU32)((NU32)(t0) * (NU32)(((NU32) (source.g))))) + (NU32)((NU32)((NU32)(t1) * (NU32)(((NU32) (mixed.g))))))) + (NU32)((NU32)((NU32)(t2) * (NU32)(((NU32) (backdrop.g))))));
	b = (NU32)((NU32)((NU32)((NU32)((NU32)((NU32)(t0) * (NU32)(((NU32) (source.b))))) + (NU32)((NU32)((NU32)(t1) * (NU32)(((NU32) (mixed.b))))))) + (NU32)((NU32)((NU32)(t2) * (NU32)(((NU32) (backdrop.b))))));
	a = (NU32)((NU32)(sa) + (NU32)((NU32)((NU32)((NU32)((NU32)(ba) * (NU32)((NU32)((NU32)(((NU32) 255)) - (NU32)(sa))))) / (NU32)(((NU32) 255)))));
	{
		if (!(a == ((NU32) 0))) goto LA3_;
		goto BeforeRet_;
	}
	LA3_: ;
	result.r = ((NU8) ((NU32)((NU32)((NU32)((NU32)(r) / (NU32)(a))) / (NU32)(((NU32) 255)))));
	result.g = ((NU8) ((NU32)((NU32)((NU32)((NU32)(g) / (NU32)(a))) / (NU32)(((NU32) 255)))));
	result.b = ((NU8) ((NU32)((NU32)((NU32)((NU32)(b) / (NU32)(a))) / (NU32)(((NU32) 255)))));
	result.a = ((NU8) (a));
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendColorBurn__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_173)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source) {
	tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw result;
	tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g backdrop_2;
	tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g source_2;
	tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g blended;
	NU8 T1_;
	NU8 T2_;
	NU8 T3_;
	tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g T4_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw));
	backdrop_2 = rgba__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_3(backdrop);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	source_2 = rgba__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_3(source);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimZeroMem((void*)(&blended), sizeof(tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g));
	T1_ = (NU8)0;
	T1_ = blend__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_179(((NU32) (backdrop_2.r)), ((NU32) (source_2.r)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	blended.r = T1_;
	T2_ = (NU8)0;
	T2_ = blend__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_179(((NU32) (backdrop_2.g)), ((NU32) (source_2.g)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	blended.g = T2_;
	T3_ = (NU8)0;
	T3_ = blend__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_179(((NU32) (backdrop_2.b)), ((NU32) (source_2.b)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	blended.b = T3_;
	T4_ = alphaFix__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_18(backdrop_2, source_2, blended);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = rgbx__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_7(T4_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NU32, max__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_194)(NU32 x, NU32 y) {
	NU32 result;
	NU32 colontmpD_;
	NU32 colontmpD__2;
	result = (NU32)0;
	colontmpD_ = (NU32)0;
	colontmpD__2 = (NU32)0;
	{
		if (!((NU32)(y) <= (NU32)(x))) goto LA3_;
		colontmpD_ = x;
		result = colontmpD_;
	}
	goto LA1_;
	LA3_: ;
	{
		colontmpD__2 = y;
		result = colontmpD__2;
	}
	LA1_: ;
	return result;
}
static N_INLINE(NU8, blend__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_188)(NU8 backdropColor, NU8 backdropAlpha, NU8 sourceColor, NU8 sourceAlpha) {
	NU8 result;
	NU32 T1_;
	result = (NU8)0;
	T1_ = (NU32)0;
	T1_ = max__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_194((NU32)((NU32)(((NU32) (backdropColor))) + (NU32)((NU32)((NU32)((NU32)((NU32)(((NU32) ((NU8)((NU8)(((NU8) 255)) - (NU8)(backdropAlpha))))) * (NU32)(((NU32) (sourceColor))))) / (NU32)(((NU32) 255))))), (NU32)((NU32)(((NU32) (sourceColor))) + (NU32)((NU32)((NU32)((NU32)((NU32)(((NU32) ((NU8)((NU8)(((NU8) 255)) - (NU8)(sourceAlpha))))) * (NU32)(((NU32) (backdropColor))))) / (NU32)(((NU32) 255))))));
	result = ((NU8) (T1_));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendLighten__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_184)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source) {
	tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw result;
	NU8 T1_;
	NU8 T2_;
	NU8 T3_;
	NU8 T4_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw));
	T1_ = (NU8)0;
	T1_ = blend__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_188(backdrop.r, backdrop.a, source.r, source.a);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.r = T1_;
	T2_ = (NU8)0;
	T2_ = blend__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_188(backdrop.g, backdrop.a, source.g, source.a);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.g = T2_;
	T3_ = (NU8)0;
	T3_ = blend__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_188(backdrop.b, backdrop.a, source.b, source.a);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.b = T3_;
	T4_ = (NU8)0;
	T4_ = blendAlpha__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_52(backdrop.a, source.a);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.a = T4_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NU8, screen__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_56)(NU32 backdrop, NU32 source) {
	NU8 result;
	result = (NU8)0;
	result = ((NU8) ((NI32)(((NI32) ((NU32)((NU32)(backdrop) + (NU32)(source)))) - ((NI32) ((NU32)((NU32)((NU32)((NU32)(backdrop) * (NU32)(source))) / (NU32)(((NU32) 255))))))));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendScreen__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_199)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source) {
	tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw result;
	NU8 T1_;
	NU8 T2_;
	NU8 T3_;
	NU8 T4_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw));
	T1_ = (NU8)0;
	T1_ = screen__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_56(((NU32) (backdrop.r)), ((NU32) (source.r)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.r = T1_;
	T2_ = (NU8)0;
	T2_ = screen__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_56(((NU32) (backdrop.g)), ((NU32) (source.g)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.g = T2_;
	T3_ = (NU8)0;
	T3_ = screen__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_56(((NU32) (backdrop.b)), ((NU32) (source.b)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.b = T3_;
	T4_ = (NU8)0;
	T4_ = blendAlpha__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_52(backdrop.a, source.a);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.a = T4_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NU8, blend__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_209)(NU32 backdrop, NU32 source) {
	NU8 result;
	NU8 colontmpD_;
	NU8 colontmpD__2;
	NU8 colontmpD__3;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NU8)0;
	colontmpD_ = (NU8)0;
	colontmpD__2 = (NU8)0;
	colontmpD__3 = (NU8)0;
	{
		if (!(backdrop == ((NU32) 0))) goto LA3_;
		colontmpD_ = ((NU8) 0);
		result = colontmpD_;
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(source == ((NU32) 255))) goto LA6_;
		colontmpD__2 = ((NU8) 255);
		result = colontmpD__2;
	}
	goto LA1_;
	LA6_: ;
	{
		NU32 T9_;
		T9_ = (NU32)0;
		T9_ = min__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_14(((NU32) 255), (NU32)((NU32)((NU32)((NU32)(((NU32) 255)) * (NU32)(backdrop))) / (NU32)((NU32)((NU32)(((NU32) 255)) - (NU32)(source)))));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		colontmpD__3 = ((NU8) (T9_));
		result = colontmpD__3;
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendColorDodge__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_203)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source) {
	tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw result;
	tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g backdrop_2;
	tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g source_2;
	tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g blended;
	NU8 T1_;
	NU8 T2_;
	NU8 T3_;
	tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g T4_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw));
	backdrop_2 = rgba__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_3(backdrop);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	source_2 = rgba__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_3(source);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimZeroMem((void*)(&blended), sizeof(tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g));
	T1_ = (NU8)0;
	T1_ = blend__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_209(((NU32) (backdrop_2.r)), ((NU32) (source_2.r)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	blended.r = T1_;
	T2_ = (NU8)0;
	T2_ = blend__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_209(((NU32) (backdrop_2.g)), ((NU32) (source_2.g)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	blended.g = T2_;
	T3_ = (NU8)0;
	T3_ = blend__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_209(((NU32) (backdrop_2.b)), ((NU32) (source_2.b)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	blended.b = T3_;
	T4_ = alphaFix__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_18(backdrop_2, source_2, blended);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = rgbx__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_7(T4_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NU8, hardLight__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_60)(NU32 backdropColor, NU32 backdropAlpha, NU32 sourceColor, NU32 sourceAlpha) {
	NU8 result;
	NU8 colontmpD_;
	NU8 colontmpD__2;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NU8)0;
	colontmpD_ = (NU8)0;
	colontmpD__2 = (NU8)0;
	{
		if (!((NU32)((NU32)((NU32)(sourceColor) * (NU32)(((NU32) 2)))) <= (NU32)(sourceAlpha))) goto LA3_;
		colontmpD_ = ((NU8) ((NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((NU32)((NU32)(((NU32) 2)) * (NU32)(sourceColor))) * (NU32)(backdropColor))) + (NU32)((NU32)((NU32)(sourceColor) * (NU32)((NU32)((NU32)(((NU32) 255)) - (NU32)(backdropAlpha))))))) + (NU32)((NU32)((NU32)(backdropColor) * (NU32)((NU32)((NU32)(((NU32) 255)) - (NU32)(sourceAlpha))))))) / (NU32)(((NU32) 255)))));
		result = colontmpD_;
	}
	goto LA1_;
	LA3_: ;
	{
		colontmpD__2 = screen__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_56(backdropColor, sourceColor);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = colontmpD__2;
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendOverlay__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_214)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source) {
	tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw result;
	NU8 T1_;
	NU8 T2_;
	NU8 T3_;
	NU8 T4_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw));
	T1_ = (NU8)0;
	T1_ = hardLight__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_60(((NU32) (source.r)), ((NU32) (source.a)), ((NU32) (backdrop.r)), ((NU32) (backdrop.a)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.r = T1_;
	T2_ = (NU8)0;
	T2_ = hardLight__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_60(((NU32) (source.g)), ((NU32) (source.a)), ((NU32) (backdrop.g)), ((NU32) (backdrop.a)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.g = T2_;
	T3_ = (NU8)0;
	T3_ = hardLight__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_60(((NU32) (source.b)), ((NU32) (source.a)), ((NU32) (backdrop.b)), ((NU32) (backdrop.a)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.b = T3_;
	T4_ = (NU8)0;
	T4_ = blendAlpha__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_52(backdrop.a, source.a);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.a = T4_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ, color__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_19)(tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g c) {
	tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ result;
	nimZeroMem((void*)(&result), sizeof(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ));
	result.r = ((NF32)(((NF32) (c.r))) / (NF32)(255.0f));
	result.g = ((NF32)(((NF32) (c.g))) / (NF32)(255.0f));
	result.b = ((NF32)(((NF32) (c.b))) / (NF32)(255.0f));
	result.a = ((NF32)(((NF32) (c.a))) / (NF32)(255.0f));
	return result;
}
static N_INLINE(NF32, softLight__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_66)(NF32 backdrop, NF32 source) {
	NF32 result;
	NF32 T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NF32)0;
	T1_ = (NF32)0;
	T1_ = roof___OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZdistance_22(backdrop, ((NI) 2));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = ((NF32)(((NF32)(((NF32)(1.0f) - (NF32)(((NF32)(2.0f) * (NF32)(source))))) * (NF32)(T1_))) + (NF32)(((NF32)(((NF32)(2.0f) * (NF32)(source))) * (NF32)(backdrop))));
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, slasheq___OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_40)(NF32* x, NF32 y) {
	(*x) = ((NF32)((*x)) / (NF32)(y));
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ, alphaFix__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_32)(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ backdrop, tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ source, tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ mixed) {
	tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ result;
	NF32 t0;
	NF32 t1;
	NF32 t2;
{	nimZeroMem((void*)(&result), sizeof(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ));
	result.a = ((NF32) (((NF)(((NF) (source.a))) + (NF)(((NF)(((NF) (backdrop.a))) * (NF)(((NF)(1.0) - (NF)(((NF) (source.a))))))))));
	{
		if (!(result.a == 0.0f)) goto LA3_;
		goto BeforeRet_;
	}
	LA3_: ;
	t0 = ((NF32)(source.a) * (NF32)(((NF32)(1.0f) - (NF32)(backdrop.a))));
	t1 = ((NF32)(source.a) * (NF32)(backdrop.a));
	t2 = ((NF32)(((NF32)(1.0f) - (NF32)(source.a))) * (NF32)(backdrop.a));
	result.r = ((NF32)(((NF32)(((NF32)(t0) * (NF32)(source.r))) + (NF32)(((NF32)(t1) * (NF32)(mixed.r))))) + (NF32)(((NF32)(t2) * (NF32)(backdrop.r))));
	result.g = ((NF32)(((NF32)(((NF32)(t0) * (NF32)(source.g))) + (NF32)(((NF32)(t1) * (NF32)(mixed.g))))) + (NF32)(((NF32)(t2) * (NF32)(backdrop.g))));
	result.b = ((NF32)(((NF32)(((NF32)(t0) * (NF32)(source.b))) + (NF32)(((NF32)(t1) * (NF32)(mixed.b))))) + (NF32)(((NF32)(t2) * (NF32)(backdrop.b))));
	slasheq___OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_40((&result.r), result.a);
	slasheq___OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_40((&result.g), result.a);
	slasheq___OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_40((&result.b), result.a);
	}BeforeRet_: ;
	return result;
}
static N_INLINE(tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g, rgba__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_16)(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ c) {
	tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g result;
	nimZeroMem((void*)(&result), sizeof(tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g));
	result.r = ((NU8) (((NF32)(c.r) * (NF32)(255.0f))));
	result.g = ((NU8) (((NF32)(c.g) * (NF32)(255.0f))));
	result.b = ((NU8) (((NF32)(c.b) * (NF32)(255.0f))));
	result.a = ((NU8) (((NF32)(c.a) * (NF32)(255.0f))));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendSoftLight__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_218)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source) {
	tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw result;
	tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g backdrop_2;
	tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g source_2;
	tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g rgba;
	tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ b;
	tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ s;
	tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ blended;
	NF32 T1_;
	NF32 T2_;
	NF32 T3_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw));
	backdrop_2 = rgba__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_3(backdrop);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	source_2 = rgba__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_3(source);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimZeroMem((void*)(&rgba), sizeof(tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g));
	b = color__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_19(backdrop_2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	s = color__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_19(source_2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimZeroMem((void*)(&blended), sizeof(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ));
	T1_ = (NF32)0;
	T1_ = softLight__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_66(b.r, s.r);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	blended.r = T1_;
	T2_ = (NF32)0;
	T2_ = softLight__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_66(b.g, s.g);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	blended.g = T2_;
	T3_ = (NF32)0;
	T3_ = softLight__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_66(b.b, s.b);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	blended.b = T3_;
	blended = alphaFix__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_32(b, s, blended);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	rgba = rgba__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_16(blended);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = rgbx__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_7(rgba);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendHardLight__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_228)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source) {
	tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw result;
	NU8 T1_;
	NU8 T2_;
	NU8 T3_;
	NU8 T4_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw));
	T1_ = (NU8)0;
	T1_ = hardLight__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_60(((NU32) (backdrop.r)), ((NU32) (backdrop.a)), ((NU32) (source.r)), ((NU32) (source.a)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.r = T1_;
	T2_ = (NU8)0;
	T2_ = hardLight__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_60(((NU32) (backdrop.g)), ((NU32) (backdrop.a)), ((NU32) (source.g)), ((NU32) (source.a)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.g = T2_;
	T3_ = (NU8)0;
	T3_ = hardLight__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_60(((NU32) (backdrop.b)), ((NU32) (backdrop.a)), ((NU32) (source.b)), ((NU32) (source.a)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.b = T3_;
	T4_ = (NU8)0;
	T4_ = blendAlpha__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_52(backdrop.a, source.a);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.a = T4_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NU8, blend__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_236)(NU8 backdropColor, NU8 backdropAlpha, NU8 sourceColor, NU8 sourceAlpha) {
	NU8 result;
	NU32 T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NU8)0;
	T1_ = (NU32)0;
	T1_ = min__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_14((NU32)((NU32)(((NU32) (backdropColor))) * (NU32)(((NU32) (sourceAlpha)))), (NU32)((NU32)(((NU32) (sourceColor))) * (NU32)(((NU32) (backdropAlpha)))));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = ((NU8) ((NI32)(((NI32) ((NU8)((NU8)(backdropColor) + (NU8)(sourceColor)))) - (NI32)(((NI32) 2) * ((NI32) ((NU32)((NU32)(T1_) / (NU32)(((NU32) 255)))))))));
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendDifference__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_232)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source) {
	tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw result;
	NU8 T1_;
	NU8 T2_;
	NU8 T3_;
	NU8 T4_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw));
	T1_ = (NU8)0;
	T1_ = blend__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_236(backdrop.r, backdrop.a, source.r, source.a);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.r = T1_;
	T2_ = (NU8)0;
	T2_ = blend__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_236(backdrop.g, backdrop.a, source.g, source.a);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.g = T2_;
	T3_ = (NU8)0;
	T3_ = blend__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_236(backdrop.b, backdrop.a, source.b, source.a);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.b = T3_;
	T4_ = (NU8)0;
	T4_ = blendAlpha__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_52(backdrop.a, source.a);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.a = T4_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NU8, blend__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_246)(NU32 backdrop, NU32 source) {
	NU8 result;
	NI32 v;
	result = (NU8)0;
	v = (NI32)(((NI32) ((NU32)((NU32)(backdrop) + (NU32)(source)))) - ((NI32) ((NU32)((NU32)((NU32)((NU32)((NU32)((NU32)(((NU32) 2)) * (NU32)(backdrop))) * (NU32)(source))) / (NU32)(((NU32) 255))))));
	result = ((NU8) (((((NI32) 0) >= v) ? ((NI32) 0) : v)));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendExclusion__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_242)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source) {
	tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw result;
	NU8 T1_;
	NU8 T2_;
	NU8 T3_;
	NU8 T4_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw));
	T1_ = (NU8)0;
	T1_ = blend__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_246(((NU32) (backdrop.r)), ((NU32) (source.r)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.r = T1_;
	T2_ = (NU8)0;
	T2_ = blend__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_246(((NU32) (backdrop.g)), ((NU32) (source.g)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.g = T2_;
	T3_ = (NU8)0;
	T3_ = blend__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_246(((NU32) (backdrop.b)), ((NU32) (source.b)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.b = T3_;
	T4_ = (NU8)0;
	T4_ = blendAlpha__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_52(backdrop.a, source.a);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.a = T4_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NF32, Lum__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_94)(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ C) {
	NF32 result;
	result = (NF32)0;
	result = ((NF32) (((NF)(((NF)(((NF)(0.3) * (NF)(((NF) (C.r))))) + (NF)(((NF)(0.59) * (NF)(((NF) (C.g))))))) + (NF)(((NF)(0.11) * (NF)(((NF) (C.b))))))));
	return result;
}
static N_INLINE(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ, plus___OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_74)(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ c, NF32 v) {
	tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ result;
	nimZeroMem((void*)(&result), sizeof(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ));
	result.r = ((NF32)(c.r) + (NF32)(v));
	result.g = ((NF32)(c.g) + (NF32)(v));
	result.b = ((NF32)(c.b) + (NF32)(v));
	result.a = ((NF32)(c.a) + (NF32)(v));
	return result;
}
static N_INLINE(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ, plus___OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_78)(NF32 v, tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ c) {
	tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ));
	result = plus___OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_74(c, v);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ, slash___OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_86)(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ c, NF32 v) {
	tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ result;
	nimZeroMem((void*)(&result), sizeof(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ));
	result.r = ((NF32)(c.r) / (NF32)(v));
	result.g = ((NF32)(c.g) / (NF32)(v));
	result.b = ((NF32)(c.b) / (NF32)(v));
	result.a = ((NF32)(c.a) / (NF32)(v));
	return result;
}
static N_INLINE(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ, star___OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_82)(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ c, NF32 v) {
	tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ result;
	nimZeroMem((void*)(&result), sizeof(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ));
	result.r = ((NF32)(c.r) * (NF32)(v));
	result.g = ((NF32)(c.g) * (NF32)(v));
	result.b = ((NF32)(c.b) * (NF32)(v));
	result.a = ((NF32)(c.a) * (NF32)(v));
	return result;
}
static N_INLINE(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ, minus___OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_90)(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ c, NF32 v) {
	tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ result;
	nimZeroMem((void*)(&result), sizeof(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ));
	result.r = ((NF32)(c.r) - (NF32)(v));
	result.g = ((NF32)(c.g) - (NF32)(v));
	result.b = ((NF32)(c.b) - (NF32)(v));
	result.a = ((NF32)(c.a) - (NF32)(v));
	return result;
}
static N_INLINE(void, ClipColor__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_97)(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ* C) {
	NF32 L;
	NF32 n;
	tyArray__mXNbtvWKAiZn9bWV4uCjiKg T1_;
	NF32 x;
	tyArray__mXNbtvWKAiZn9bWV4uCjiKg T2_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	L = Lum__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_94((*C));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T1_[0] = (*C).r;
	T1_[1] = (*C).g;
	T1_[2] = (*C).b;
	n = min__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_100(T1_, 3);
	T2_[0] = (*C).r;
	T2_[1] = (*C).g;
	T2_[2] = (*C).b;
	x = max__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_113(T2_, 3);
	{
		tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ T7_;
		tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ T8_;
		tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ T9_;
		tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ T10_;
		if (!(n < 0.0f)) goto LA5_;
		T7_ = minus___OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_90((*C), L);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T8_ = star___OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_82(T7_, L);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T9_ = slash___OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_86(T8_, ((NF32)(L) - (NF32)(n)));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimZeroMem((void*)(&T10_), sizeof(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ));
		T10_ = plus___OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_78(L, T9_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(*C) = T10_;
	}
	LA5_: ;
	{
		tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ T15_;
		tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ T16_;
		tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ T17_;
		tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ T18_;
		if (!(1.0f < x)) goto LA13_;
		T15_ = minus___OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_90((*C), L);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T16_ = star___OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_82(T15_, ((NF32)(1.0f) - (NF32)(L)));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T17_ = slash___OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_86(T16_, ((NF32)(x) - (NF32)(L)));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimZeroMem((void*)(&T18_), sizeof(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ));
		T18_ = plus___OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_78(L, T17_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(*C) = T18_;
	}
	LA13_: ;
	}BeforeRet_: ;
}
static N_INLINE(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ, SetLum__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_126)(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ C, NF32 l) {
	tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ result;
	NF32 d;
	NF32 T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ));
	T1_ = (NF32)0;
	T1_ = Lum__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_94(C);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	d = ((NF32)(l) - (NF32)(T1_));
	result.r = ((NF32)(C.r) + (NF32)(d));
	result.g = ((NF32)(C.g) + (NF32)(d));
	result.b = ((NF32)(C.b) + (NF32)(d));
	ClipColor__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_97((&result));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NF32, Sat__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_131)(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ C) {
	NF32 result;
	tyArray__mXNbtvWKAiZn9bWV4uCjiKg T1_;
	NF32 T2_;
	tyArray__mXNbtvWKAiZn9bWV4uCjiKg T3_;
	NF32 T4_;
	result = (NF32)0;
	T1_[0] = C.r;
	T1_[1] = C.g;
	T1_[2] = C.b;
	T2_ = (NF32)0;
	T2_ = max__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_113(T1_, 3);
	T3_[0] = C.r;
	T3_[1] = C.g;
	T3_[2] = C.b;
	T4_ = (NF32)0;
	T4_ = min__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_100(T3_, 3);
	result = ((NF32)(T2_) - (NF32)(T4_));
	return result;
}
static N_INLINE(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ, SetSat__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_140)(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ C, NF32 s) {
	tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ result;
	NF32 satC;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ));
	satC = Sat__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_131(C);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		tyArray__mXNbtvWKAiZn9bWV4uCjiKg T5_;
		NF32 T6_;
		tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ T7_;
		tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ T8_;
		if (!(0.0f < satC)) goto LA3_;
		T5_[0] = C.r;
		T5_[1] = C.g;
		T5_[2] = C.b;
		T6_ = (NF32)0;
		T6_ = min__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_100(T5_, 3);
		T7_ = minus___OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_90(C, T6_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T8_ = star___OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_82(T7_, s);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = slash___OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_86(T8_, satC);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	LA3_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendHue__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_265)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source) {
	tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw result;
	tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ backdrop_2;
	tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g T1_;
	tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ source_2;
	tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g T2_;
	tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ blended;
	NF32 T3_;
	tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ T4_;
	NF32 T5_;
	tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ T6_;
	tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g T7_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw));
	T1_ = rgba__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_3(backdrop);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	backdrop_2 = color__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_19(T1_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T2_ = rgba__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_3(source);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	source_2 = color__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_19(T2_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T3_ = (NF32)0;
	T3_ = Sat__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_131(backdrop_2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T4_ = SetSat__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_140(source_2, T3_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T5_ = (NF32)0;
	T5_ = Lum__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_94(backdrop_2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	blended = SetLum__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_126(T4_, T5_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T6_ = alphaFix__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_32(backdrop_2, source_2, blended);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T7_ = rgba__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_16(T6_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = rgbx__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_7(T7_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendSaturation__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_272)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source) {
	tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw result;
	tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ backdrop_2;
	tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g T1_;
	tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ source_2;
	tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g T2_;
	tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ blended;
	NF32 T3_;
	tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ T4_;
	NF32 T5_;
	tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ T6_;
	tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g T7_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw));
	T1_ = rgba__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_3(backdrop);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	backdrop_2 = color__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_19(T1_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T2_ = rgba__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_3(source);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	source_2 = color__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_19(T2_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T3_ = (NF32)0;
	T3_ = Sat__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_131(source_2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T4_ = SetSat__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_140(backdrop_2, T3_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T5_ = (NF32)0;
	T5_ = Lum__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_94(backdrop_2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	blended = SetLum__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_126(T4_, T5_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T6_ = alphaFix__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_32(backdrop_2, source_2, blended);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T7_ = rgba__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_16(T6_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = rgbx__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_7(T7_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendColor__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_251)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source) {
	tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw result;
	tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ backdrop_2;
	tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g T1_;
	tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ source_2;
	tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g T2_;
	tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ blended;
	NF32 T3_;
	tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ T4_;
	tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g T5_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw));
	T1_ = rgba__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_3(backdrop);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	backdrop_2 = color__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_19(T1_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T2_ = rgba__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_3(source);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	source_2 = color__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_19(T2_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T3_ = (NF32)0;
	T3_ = Lum__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_94(backdrop_2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	blended = SetLum__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_126(source_2, T3_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T4_ = alphaFix__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_32(backdrop_2, source_2, blended);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T5_ = rgba__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_16(T4_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = rgbx__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_7(T5_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendLuminosity__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_258)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source) {
	tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw result;
	tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ backdrop_2;
	tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g T1_;
	tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ source_2;
	tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g T2_;
	tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ blended;
	NF32 T3_;
	tyObject_Color__9au4GkmJGMtYC7TjyEwPQlQ T4_;
	tyObject_ColorRGBA__rA9bnJsuh1dIgzE1rI2je7g T5_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw));
	T1_ = rgba__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_3(backdrop);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	backdrop_2 = color__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_19(T1_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T2_ = rgba__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_3(source);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	source_2 = color__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_19(T2_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T3_ = (NF32)0;
	T3_ = Lum__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_94(source_2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	blended = SetLum__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_126(backdrop_2, T3_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T4_ = alphaFix__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_32(backdrop_2, source_2, blended);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T5_ = rgba__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_16(T4_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = rgbx__OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZtransformations_7(T5_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendMask__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_279)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source) {
	tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw result;
	NU32 k;
	nimZeroMem((void*)(&result), sizeof(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw));
	k = ((NU32) (source.a));
	result.r = ((NU8) ((NU32)((NU32)((NU32)((NU32)(((NU32) (backdrop.r))) * (NU32)(k))) / (NU32)(((NU32) 255)))));
	result.g = ((NU8) ((NU32)((NU32)((NU32)((NU32)(((NU32) (backdrop.g))) * (NU32)(k))) / (NU32)(((NU32) 255)))));
	result.b = ((NU8) ((NU32)((NU32)((NU32)((NU32)(((NU32) (backdrop.b))) * (NU32)(k))) / (NU32)(((NU32) 255)))));
	result.a = ((NU8) ((NU32)((NU32)((NU32)((NU32)(((NU32) (backdrop.a))) * (NU32)(k))) / (NU32)(((NU32) 255)))));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendOverwrite__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_304)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source) {
	tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw result;
	nimZeroMem((void*)(&result), sizeof(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw));
	result = source;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendSubtractMask__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_284)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source) {
	tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw result;
	NU32 a;
	nimZeroMem((void*)(&result), sizeof(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw));
	a = (NU32)((NU32)((NU32)((NU32)(((NU32) (backdrop.a))) * (NU32)(((NU32) ((NU8)((NU8)(((NU8) 255)) - (NU8)(source.a))))))) / (NU32)(((NU32) 255)));
	result.r = ((NU8) ((NU32)((NU32)((NU32)((NU32)(((NU32) (backdrop.r))) * (NU32)(a))) / (NU32)(((NU32) 255)))));
	result.g = ((NU8) ((NU32)((NU32)((NU32)((NU32)(((NU32) (backdrop.g))) * (NU32)(a))) / (NU32)(((NU32) 255)))));
	result.b = ((NU8) ((NU32)((NU32)((NU32)((NU32)(((NU32) (backdrop.b))) * (NU32)(a))) / (NU32)(((NU32) 255)))));
	result.a = ((NU8) (a));
	return result;
}
static N_INLINE(NU8, max__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_293)(NU8 x, NU8 y) {
	NU8 result;
	NU8 colontmpD_;
	NU8 colontmpD__2;
	result = (NU8)0;
	colontmpD_ = (NU8)0;
	colontmpD__2 = (NU8)0;
	{
		if (!((NU8)(y) <= (NU8)(x))) goto LA3_;
		colontmpD_ = x;
		result = colontmpD_;
	}
	goto LA1_;
	LA3_: ;
	{
		colontmpD__2 = y;
		result = colontmpD__2;
	}
	LA1_: ;
	return result;
}
static N_INLINE(NU8, min__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_298)(NU8 x, NU8 y) {
	NU8 result;
	NU8 colontmpD_;
	NU8 colontmpD__2;
	result = (NU8)0;
	colontmpD_ = (NU8)0;
	colontmpD__2 = (NU8)0;
	{
		if (!((NU8)(x) <= (NU8)(y))) goto LA3_;
		colontmpD_ = x;
		result = colontmpD_;
	}
	goto LA1_;
	LA3_: ;
	{
		colontmpD__2 = y;
		result = colontmpD__2;
	}
	LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw, blendExcludeMask__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_289)(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw backdrop, tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw source) {
	tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw result;
	NU32 a;
	NU8 T1_;
	NU8 T2_;
	nimZeroMem((void*)(&result), sizeof(tyObject_ColorRGBX__hrE0utwVpt2r9aS9b8RsUQgw));
	T1_ = (NU8)0;
	T1_ = max__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_293(backdrop.a, source.a);
	T2_ = (NU8)0;
	T2_ = min__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_298(backdrop.a, source.a);
	a = (NU32)((NU32)(((NU32) (T1_))) - (NU32)(((NU32) (T2_))));
	result.r = ((NU8) ((NU32)((NU32)((NU32)((NU32)(((NU32) (source.r))) * (NU32)(a))) / (NU32)(((NU32) 255)))));
	result.g = ((NU8) ((NU32)((NU32)((NU32)((NU32)(((NU32) (source.g))) * (NU32)(a))) / (NU32)(((NU32) 255)))));
	result.b = ((NU8) ((NU32)((NU32)((NU32)((NU32)(((NU32) (source.b))) * (NU32)(a))) / (NU32)(((NU32) 255)))));
	result.a = ((NU8) (a));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, blender__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_308)(tyEnum_BlendMode__5LYzfbrLeWt4hzSNsGzCUQ blendMode, tyProc__ahx1kvZUd3gRcZmpO4ziwg* Result) {
	tyProc__pDXYMhp3ZE9buYYnMoReoZQ T1_;
	tyProc__ahx1kvZUd3gRcZmpO4ziwg T22_;
	T1_ = (tyProc__pDXYMhp3ZE9buYYnMoReoZQ)0;
	switch (blendMode) {
	case ((tyEnum_BlendMode__5LYzfbrLeWt4hzSNsGzCUQ) 0):
	{
		T1_ = blendNormal__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_148;
	}
	break;
	case ((tyEnum_BlendMode__5LYzfbrLeWt4hzSNsGzCUQ) 1):
	{
		T1_ = blendDarken__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_153;
	}
	break;
	case ((tyEnum_BlendMode__5LYzfbrLeWt4hzSNsGzCUQ) 2):
	{
		T1_ = blendMultiply__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_163;
	}
	break;
	case ((tyEnum_BlendMode__5LYzfbrLeWt4hzSNsGzCUQ) 3):
	{
		T1_ = blendColorBurn__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_173;
	}
	break;
	case ((tyEnum_BlendMode__5LYzfbrLeWt4hzSNsGzCUQ) 4):
	{
		T1_ = blendLighten__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_184;
	}
	break;
	case ((tyEnum_BlendMode__5LYzfbrLeWt4hzSNsGzCUQ) 5):
	{
		T1_ = blendScreen__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_199;
	}
	break;
	case ((tyEnum_BlendMode__5LYzfbrLeWt4hzSNsGzCUQ) 6):
	{
		T1_ = blendColorDodge__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_203;
	}
	break;
	case ((tyEnum_BlendMode__5LYzfbrLeWt4hzSNsGzCUQ) 7):
	{
		T1_ = blendOverlay__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_214;
	}
	break;
	case ((tyEnum_BlendMode__5LYzfbrLeWt4hzSNsGzCUQ) 8):
	{
		T1_ = blendSoftLight__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_218;
	}
	break;
	case ((tyEnum_BlendMode__5LYzfbrLeWt4hzSNsGzCUQ) 9):
	{
		T1_ = blendHardLight__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_228;
	}
	break;
	case ((tyEnum_BlendMode__5LYzfbrLeWt4hzSNsGzCUQ) 10):
	{
		T1_ = blendDifference__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_232;
	}
	break;
	case ((tyEnum_BlendMode__5LYzfbrLeWt4hzSNsGzCUQ) 11):
	{
		T1_ = blendExclusion__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_242;
	}
	break;
	case ((tyEnum_BlendMode__5LYzfbrLeWt4hzSNsGzCUQ) 12):
	{
		T1_ = blendHue__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_265;
	}
	break;
	case ((tyEnum_BlendMode__5LYzfbrLeWt4hzSNsGzCUQ) 13):
	{
		T1_ = blendSaturation__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_272;
	}
	break;
	case ((tyEnum_BlendMode__5LYzfbrLeWt4hzSNsGzCUQ) 14):
	{
		T1_ = blendColor__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_251;
	}
	break;
	case ((tyEnum_BlendMode__5LYzfbrLeWt4hzSNsGzCUQ) 15):
	{
		T1_ = blendLuminosity__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_258;
	}
	break;
	case ((tyEnum_BlendMode__5LYzfbrLeWt4hzSNsGzCUQ) 16):
	{
		T1_ = blendMask__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_279;
	}
	break;
	case ((tyEnum_BlendMode__5LYzfbrLeWt4hzSNsGzCUQ) 17):
	{
		T1_ = blendOverwrite__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_304;
	}
	break;
	case ((tyEnum_BlendMode__5LYzfbrLeWt4hzSNsGzCUQ) 18):
	{
		T1_ = blendSubtractMask__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_284;
	}
	break;
	case ((tyEnum_BlendMode__5LYzfbrLeWt4hzSNsGzCUQ) 19):
	{
		T1_ = blendExcludeMask__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_289;
	}
	break;
	}
	nimZeroMem((void*)(&T22_), sizeof(tyProc__ahx1kvZUd3gRcZmpO4ziwg));
	T22_.ClP_0 = ((TM__LHGo88dm0cLvmgKkpdsivQ_2) (T1_)); T22_.ClE_0 = NIM_NIL;
	(*Result).ClE_0 = T22_.ClE_0;
	(*Result).ClP_0 = T22_.ClP_0;
}
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU64)(((NU) (x))) - (NU64)(((NU) (y))))));
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* cell;
		NI T5_;
		if (!!((p == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_716(((NI) (ptrdiff_t) (p)), ((NI) 8));
		cell = ((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T5_));
		{
			if (!((NI)((*cell).rc & ((NI) -8)) == ((NI) 0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
		LA8_: ;
		{
			(*cell).rc -= ((NI) 8);
		}
		LA6_: ;
	}
	LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_311)(tyProc__ahx1kvZUd3gRcZmpO4ziwg* dest) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest).ClE_0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest).ClE_0);
	}
	LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(NU8, maskNormal__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_333)(NU8 backdrop, NU8 source) {
	NU8 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NU8)0;
	result = blendAlpha__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_52(backdrop, source);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NU8, maskMaskInline__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_337)(NU8 backdrop, NU8 source) {
	NU8 result;
	result = (NU8)0;
	result = ((NU8) ((NU32)((NU32)((NU32)((NU32)(((NU32) (backdrop))) * (NU32)(((NU32) (source))))) / (NU32)(((NU32) 255)))));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU8, maskMask__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_341)(NU8 backdrop, NU8 source) {
	NU8 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NU8)0;
	result = maskMaskInline__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_337(backdrop, source);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU8, maskOverwrite__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_361)(NU8 backdrop, NU8 source) {
	NU8 result;
	result = (NU8)0;
	result = source;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU8, maskSubtract__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_345)(NU8 backdrop, NU8 source) {
	NU8 result;
	result = (NU8)0;
	result = ((NU8) ((NU32)((NU32)((NU32)((NU32)(((NU32) (backdrop))) * (NU32)(((NU32) ((NU8)((NU8)(((NU8) 255)) - (NU8)(source))))))) / (NU32)(((NU32) 255)))));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU8, maskExclude__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_349)(NU8 backdrop, NU8 source) {
	NU8 result;
	NU8 T1_;
	NU8 T2_;
	result = (NU8)0;
	T1_ = (NU8)0;
	T1_ = max__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_293(backdrop, source);
	T2_ = (NU8)0;
	T2_ = min__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_298(backdrop, source);
	result = (NU8)((NU8)(T1_) - (NU8)(T2_));
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__system_1709)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src) {
	{
		if (!(((NI) 0) < src.len)) goto LA3_;
		copyMem__system_1709(((void*) ((&(*(*dest).p).data[(*dest).len]))), ((void*) ((&(*src.p).data[((NI) 0)]))), ((NI) ((NI)(src.len + ((NI) 1)))));
		(*dest).len += src.len;
	}
	LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, masker__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_365)(tyEnum_BlendMode__5LYzfbrLeWt4hzSNsGzCUQ blendMode, tyProc__J9aFZ4xZVYu6zZ3I9aLCdVuw* Result) {
	tyProc__Cif9aofUV85UivbLssUVkAw T1_;
	tyProc__J9aFZ4xZVYu6zZ3I9aLCdVuw T11_;
{	T1_ = (tyProc__Cif9aofUV85UivbLssUVkAw)0;
	switch (blendMode) {
	case ((tyEnum_BlendMode__5LYzfbrLeWt4hzSNsGzCUQ) 0):
	{
		T1_ = maskNormal__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_333;
	}
	break;
	case ((tyEnum_BlendMode__5LYzfbrLeWt4hzSNsGzCUQ) 16):
	{
		T1_ = maskMask__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_341;
	}
	break;
	case ((tyEnum_BlendMode__5LYzfbrLeWt4hzSNsGzCUQ) 17):
	{
		T1_ = maskOverwrite__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_361;
	}
	break;
	case ((tyEnum_BlendMode__5LYzfbrLeWt4hzSNsGzCUQ) 18):
	{
		T1_ = maskSubtract__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_345;
	}
	break;
	case ((tyEnum_BlendMode__5LYzfbrLeWt4hzSNsGzCUQ) 19):
	{
		T1_ = maskExclude__OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_349;
	}
	break;
	default:
	{
		tyObject_PixieError__iGcRqvltYLQCoM1tI9cqukQ* T8_;
		NimStringV2 T9_;
		NimStringV2 T10_;
		T8_ = NIM_NIL;
		T8_ = (tyObject_PixieError__iGcRqvltYLQCoM1tI9cqukQ*) nimNewObj(sizeof(tyObject_PixieError__iGcRqvltYLQCoM1tI9cqukQ), NIM_ALIGNOF(tyObject_PixieError__iGcRqvltYLQCoM1tI9cqukQ));
		(*T8_).Sup.Sup.Sup.Sup.m_type = (&NTIv2__iGcRqvltYLQCoM1tI9cqukQ_);
		(*T8_).Sup.Sup.Sup.name = "PixieError";
		T9_.len = 0; T9_.p = NIM_NIL;
		T10_.len = 0; T10_.p = NIM_NIL;
		T10_ = dollar___OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZcommon_26(blendMode);
		T9_ = rawNewString(T10_.len + 14);
appendString((&T9_), TM__LHGo88dm0cLvmgKkpdsivQ_4);
appendString((&T9_), T10_);
		(*T8_).Sup.Sup.Sup.message = T9_;
		(*T8_).Sup.Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T8_, "PixieError", "masker", "blends.nim", 480);
		goto BeforeRet_;
	}
	break;
	}
	nimZeroMem((void*)(&T11_), sizeof(tyProc__J9aFZ4xZVYu6zZ3I9aLCdVuw));
	T11_.ClP_0 = ((TM__LHGo88dm0cLvmgKkpdsivQ_5) (T1_)); T11_.ClE_0 = NIM_NIL;
	(*Result).ClE_0 = T11_.ClE_0;
	(*Result).ClP_0 = T11_.ClP_0;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZOnimbleZpkgsZpixie4552O48O49ZpixieZblends_396)(tyProc__J9aFZ4xZVYu6zZ3I9aLCdVuw* dest) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest).ClE_0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest).ClE_0);
	}
	LA4_: ;
}
