/* Generated by Nim Compiler v1.6.4 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_FramebufferObj__1pPqnr9cylF8gi9bULYcALCQ tyObject_FramebufferObj__1pPqnr9cylF8gi9bULYcALCQ;
typedef struct tyObject_Bloom__kDHmp9bu9aDv39a8ndZ4EZHWQ tyObject_Bloom__kDHmp9bu9aDv39a8ndZ4EZHWQ;
typedef struct tyObject_Color__OSWJq3HNkIl1V7S3GsYvBg tyObject_Color__OSWJq3HNkIl1V7S3GsYvBg;
typedef struct tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ;
typedef struct tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ;
typedef struct tyObject_ShaderObj__KFmcUvp7lIrtBdspoRxLXw tyObject_ShaderObj__KFmcUvp7lIrtBdspoRxLXw;
typedef struct tyObject_FauState__309cTFhuUrshBEQHbLmaQlw tyObject_FauState__309cTFhuUrshBEQHbLmaQlw;
typedef struct tyObject_BatchcolonObjectType___RYPwJl20EVec0ujcBafF9aA tyObject_BatchcolonObjectType___RYPwJl20EVec0ujcBafF9aA;
typedef struct tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA;
typedef struct tyObject_CamcolonObjectType___4eTzE4gEL86vZ9bRFgwAN4A tyObject_CamcolonObjectType___4eTzE4gEL86vZ9bRFgwAN4A;
typedef struct tyObject_MeshObj__cPggZRHFWvGLKpQsZMF8yA tyObject_MeshObj__cPggZRHFWvGLKpQsZMF8yA;
typedef struct tyObject_AtlascolonObjectType___5kuY28uezWLPxjw6Jjpi9ag tyObject_AtlascolonObjectType___5kuY28uezWLPxjw6Jjpi9ag;
typedef struct tySequence__HG77dJmfYz9agmsHT9aDRxHA tySequence__HG77dJmfYz9agmsHT9aDRxHA;
typedef struct tySequence__HG77dJmfYz9agmsHT9aDRxHA_Content tySequence__HG77dJmfYz9agmsHT9aDRxHA_Content;
typedef struct tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w;
typedef struct tyObject_Touch__O3vdnbkm84I9bOqV6XPOHdw tyObject_Touch__O3vdnbkm84I9bOqV6XPOHdw;
typedef struct tyObject_MeshParam__PTeep4m69bNi7Bk4ErRbSdw tyObject_MeshParam__PTeep4m69bNi7Bk4ErRbSdw;
typedef struct tyObject_Blending__hsAju9cB1hd79a6H4b5CoxVQ tyObject_Blending__hsAju9cB1hd79a6H4b5CoxVQ;
typedef struct tyObject_Sampler__xQXqueoTRZOwCBoD5nnvhg tyObject_Sampler__xQXqueoTRZOwCBoD5nnvhg;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A;
typedef struct tyObject_Table__i55W8RrwGKsG9cl0sAKxgkQ tyObject_Table__i55W8RrwGKsG9cl0sAKxgkQ;
typedef struct tySequence__pUxI6Ljo6IKKHXKOZkQ7Og tySequence__pUxI6Ljo6IKKHXKOZkQ7Og;
typedef struct tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content;
typedef struct tyObject_Table__a9aFGxCEM6129c8Bf9cjeka9aw tyObject_Table__a9aFGxCEM6129c8Bf9cjeka9aw;
typedef struct tySequence__s9aRGEDrqx69bYD8TWX6AWeA tySequence__s9aRGEDrqx69bYD8TWX6AWeA;
typedef struct tySequence__s9aRGEDrqx69bYD8TWX6AWeA_Content tySequence__s9aRGEDrqx69bYD8TWX6AWeA_Content;
typedef struct tyObject_FauEvent__YNvUGRpkmCiP22cM2l29bkQ tyObject_FauEvent__YNvUGRpkmCiP22cM2l29bkQ;
typedef struct tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ;
typedef struct tyTuple__9cPYCugXZVVKLkBMRxkZXSA tyTuple__9cPYCugXZVVKLkBMRxkZXSA;
typedef struct tyObject_ShaderAttr__YLfRa9av9azfSk49bF6ygpRFw tyObject_ShaderAttr__YLfRa9av9azfSk49bF6ygpRFw;
struct tyObject_Color__OSWJq3HNkIl1V7S3GsYvBg {
NU8 rv;
NU8 gv;
NU8 bv;
NU8 av;
};
struct tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ {
NI x;
NI y;
};
struct tyObject_Bloom__kDHmp9bu9aDv39a8ndZ4EZHWQ {
tyObject_FramebufferObj__1pPqnr9cylF8gi9bULYcALCQ* buffer;
tyObject_FramebufferObj__1pPqnr9cylF8gi9bULYcALCQ* p1;
tyObject_FramebufferObj__1pPqnr9cylF8gi9bULYcALCQ* p2;
tyObject_ShaderObj__KFmcUvp7lIrtBdspoRxLXw* thresh;
tyObject_ShaderObj__KFmcUvp7lIrtBdspoRxLXw* bloom;
tyObject_ShaderObj__KFmcUvp7lIrtBdspoRxLXw* blur;
NI blurPasses;
NI scaling;
};
struct tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA {
tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ* texture;
NF32 u;
NF32 v;
NF32 u2;
NF32 v2;
};
struct tySequence__HG77dJmfYz9agmsHT9aDRxHA {
  NI len; tySequence__HG77dJmfYz9agmsHT9aDRxHA_Content* p;
};
struct tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w {
NF32 x;
NF32 y;
};
typedef NF32 tyArray__9aTCwbdg1cSQimdVd0OEKVw[4];
struct tyObject_Touch__O3vdnbkm84I9bOqV6XPOHdw {
tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w pos;
tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w delta;
tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w last;
NIM_BOOL down;
};
typedef tyObject_Touch__O3vdnbkm84I9bOqV6XPOHdw tyArray__q1daT0HgNuIpm71XQ8ZW8w[10];
struct tyObject_FauState__309cTFhuUrshBEQHbLmaQlw {
tyObject_Color__OSWJq3HNkIl1V7S3GsYvBg clearColor;
tyObject_BatchcolonObjectType___RYPwJl20EVec0ujcBafF9aA* batch;
NF32 pixelScl;
tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA white;
tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA circle;
tyObject_CamcolonObjectType___4eTzE4gEL86vZ9bRFgwAN4A* cam;
tyObject_MeshObj__cPggZRHFWvGLKpQsZMF8yA* quad;
tyObject_ShaderObj__KFmcUvp7lIrtBdspoRxLXw* screenspace;
tyObject_AtlascolonObjectType___5kuY28uezWLPxjw6Jjpi9ag* atlas;
NI64 frameId;
NI fps;
NF32 delta;
NF rawDelta;
NF32 targetFps;
NF32 maxDelta;
NF32 time;
tySequence__HG77dJmfYz9agmsHT9aDRxHA listeners;
tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ sizei;
tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w size;
NF32 screenDensity;
tyArray__9aTCwbdg1cSQimdVd0OEKVw insets;
NIM_BOOL shown;
tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w mouse;
tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w scroll;
tyArray__q1daT0HgNuIpm71XQ8ZW8w touches;
};
typedef NU8 tyEnum_TextureFilter__zerQ3LMmc801hL4AG54gqg;
typedef NU8 tyEnum_TextureWrap__u5t9aRlFqNYWEA2nuqy9c2aw;
struct tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ {
NU32 handle;
tyEnum_TextureWrap__u5t9aRlFqNYWEA2nuqy9c2aw uwrap;
tyEnum_TextureWrap__u5t9aRlFqNYWEA2nuqy9c2aw vwrap;
tyEnum_TextureFilter__zerQ3LMmc801hL4AG54gqg minfilter;
tyEnum_TextureFilter__zerQ3LMmc801hL4AG54gqg magfilter;
NU32 target;
tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ size;
};
struct tyObject_FramebufferObj__1pPqnr9cylF8gi9bULYcALCQ {
NU32 handle;
tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ size;
tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ* texture;
NIM_BOOL isDefault;
NIM_BOOL hasDepth;
NU32 depthHandle;
};
struct tyObject_Blending__hsAju9cB1hd79a6H4b5CoxVQ {
NU32 src;
NU32 dst;
};
typedef NU8 tyEnum_CullFace__0G6mOarn9cnCWCzi0fEshew;
struct tyObject_MeshParam__PTeep4m69bNi7Bk4ErRbSdw {
tyObject_FramebufferObj__1pPqnr9cylF8gi9bULYcALCQ* buffer;
NI offset;
NI count;
NIM_BOOL depth;
NIM_BOOL writeDepth;
tyObject_Blending__hsAju9cB1hd79a6H4b5CoxVQ blend;
tyEnum_CullFace__0G6mOarn9cnCWCzi0fEshew cullFace;
};
struct tyObject_Sampler__xQXqueoTRZOwCBoD5nnvhg {
tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ* texture;
NI index;
};
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A {
NI rc;
};
struct tySequence__pUxI6Ljo6IKKHXKOZkQ7Og {
  NI len; tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content* p;
};
struct tyObject_Table__i55W8RrwGKsG9cl0sAKxgkQ {
tySequence__pUxI6Ljo6IKKHXKOZkQ7Og data;
NI counter;
};
struct tySequence__s9aRGEDrqx69bYD8TWX6AWeA {
  NI len; tySequence__s9aRGEDrqx69bYD8TWX6AWeA_Content* p;
};
struct tyObject_Table__a9aFGxCEM6129c8Bf9cjeka9aw {
tySequence__s9aRGEDrqx69bYD8TWX6AWeA data;
NI counter;
};
struct tyObject_ShaderObj__KFmcUvp7lIrtBdspoRxLXw {
NU32 handle;
NU32 vertHandle;
NU32 fragHandle;
NimStringV2 compileLog;
NIM_BOOL compiled;
tyObject_Table__i55W8RrwGKsG9cl0sAKxgkQ uniforms;
tyObject_Table__a9aFGxCEM6129c8Bf9cjeka9aw attributes;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_FauEvent__YNvUGRpkmCiP22cM2l29bkQ* e, void* ClE_0);
void* ClE_0;
} tyProc__pYsVTQ4Z7hmuFG9c39aHjS9cw;


#ifndef tySequence__HG77dJmfYz9agmsHT9aDRxHA_Content_PP
#define tySequence__HG77dJmfYz9agmsHT9aDRxHA_Content_PP
struct tySequence__HG77dJmfYz9agmsHT9aDRxHA_Content { NI cap; tyProc__pYsVTQ4Z7hmuFG9c39aHjS9cw data[SEQ_DECL_SIZE];};
#endif

      struct tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ {
NI Field0;
NimStringV2 Field1;
NI Field2;
};


#ifndef tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content_PP
#define tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content_PP
struct tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content { NI cap; tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ data[SEQ_DECL_SIZE];};
#endif

      struct tyObject_ShaderAttr__YLfRa9av9azfSk49bF6ygpRFw {
NimStringV2 name;
NU32 gltype;
NI32 size;
NI32 length;
NI32 location;
};
struct tyTuple__9cPYCugXZVVKLkBMRxkZXSA {
NI Field0;
NimStringV2 Field1;
tyObject_ShaderAttr__YLfRa9av9azfSk49bF6ygpRFw Field2;
};


#ifndef tySequence__s9aRGEDrqx69bYD8TWX6AWeA_Content_PP
#define tySequence__s9aRGEDrqx69bYD8TWX6AWeA_Content_PP
struct tySequence__s9aRGEDrqx69bYD8TWX6AWeA_Content { NI cap; tyTuple__9cPYCugXZVVKLkBMRxkZXSA data[SEQ_DECL_SIZE];};
#endif

      typedef NU8 tyEnum_FauEventKind__xJFQo4JN2Z8swZKj8kGvYA;
typedef NU8 tyEnum_KeyCode__YhMyimscyfYwYiOPDuaH9bg;
struct tyObject_FauEvent__YNvUGRpkmCiP22cM2l29bkQ {
tyEnum_FauEventKind__xJFQo4JN2Z8swZKj8kGvYA kind;
union{
struct {tyEnum_KeyCode__YhMyimscyfYwYiOPDuaH9bg key;
NIM_BOOL keyDown;
} _kind_1;
struct {NI dragId;
tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w dragPos;
} _kind_2;
struct {NI touchId;
tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w touchPos;
NIM_BOOL touchDown;
tyEnum_KeyCode__YhMyimscyfYwYiOPDuaH9bg touchButton;
} _kind_3;
struct {tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w scroll;
} _kind_4;
struct {tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ size;
} _kind_5;
struct {NIM_BOOL shown;
} _kind_6;
};
};
N_LIB_PRIVATE N_NIMCALL(void, resize__OOZfauZsrcZfauZframebuffer_22)(tyObject_FramebufferObj__1pPqnr9cylF8gi9bULYcALCQ* buffer, tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ size);
static N_INLINE(tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ, div__OOZfauZsrcZfauZfmath_665)(tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ vecX60gensym40_, NI otherX60gensym40_);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ, vec2i__OOZfauZsrcZfauZfmath_428)(NI x, NI y);
N_LIB_PRIVATE N_NIMCALL(void, filtereq___OOZfauZsrcZfauZtexture_63)(tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ* texture, tyEnum_TextureFilter__zerQ3LMmc801hL4AG54gqg filter);
static N_INLINE(tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ*, texture__OOZfauZsrcZfauZframebuffer_19)(tyObject_FramebufferObj__1pPqnr9cylF8gi9bULYcALCQ* buffer);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___OOZfauZsrcZfauZtexture_116)(tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ** dest, tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ* src);
N_LIB_PRIVATE N_NIMCALL(void, clear__OOZfauZsrcZfauZframebuffer_87)(tyObject_FramebufferObj__1pPqnr9cylF8gi9bULYcALCQ* buffer, tyObject_Color__OSWJq3HNkIl1V7S3GsYvBg color);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___OOZfauZsrcZfauZframebuffer_73)(tyObject_FramebufferObj__1pPqnr9cylF8gi9bULYcALCQ** dest, tyObject_FramebufferObj__1pPqnr9cylF8gi9bULYcALCQ* src);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZfauZsrcZfauZtexture_113)(tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ** dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZfauZsrcZfauZshader_3359)(tyObject_Sampler__xQXqueoTRZOwCBoD5nnvhg* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZfauZsrcZfauZmesh_116)(tyObject_MeshParam__PTeep4m69bNi7Bk4ErRbSdw* dest);
N_LIB_PRIVATE N_NIMCALL(void, uniform__OOZfauZsrcZfauZshader_3417)(tyObject_ShaderObj__KFmcUvp7lIrtBdspoRxLXw* shader, NimStringV2 name, NF32 value);
N_LIB_PRIVATE N_NIMCALL(void, blit__OOZfauZsrcZfauZg50Zbloom_36)(tyObject_FramebufferObj__1pPqnr9cylF8gi9bULYcALCQ* buffer, tyObject_ShaderObj__KFmcUvp7lIrtBdspoRxLXw* shader, tyObject_MeshParam__PTeep4m69bNi7Bk4ErRbSdw* params);
static N_INLINE(void, meshParams__OOZfauZsrcZfauZmesh_98)(tyObject_FramebufferObj__1pPqnr9cylF8gi9bULYcALCQ* buffer, NI offset, NI count, NIM_BOOL depth, NIM_BOOL writeDepth, tyObject_Blending__hsAju9cB1hd79a6H4b5CoxVQ blend, tyEnum_CullFace__0G6mOarn9cnCWCzi0fEshew cullFace, tyObject_MeshParam__PTeep4m69bNi7Bk4ErRbSdw* Result);
N_LIB_PRIVATE N_NIMCALL(void, uniform__OOZfauZsrcZfauZshader_3422)(tyObject_ShaderObj__KFmcUvp7lIrtBdspoRxLXw* shader, NimStringV2 name, tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w value);
static N_INLINE(tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w, vec2__OOZfauZsrcZfauZfmath_446)(tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ v);
static N_INLINE(tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ, size__OOZfauZsrcZfauZframebuffer_16)(tyObject_FramebufferObj__1pPqnr9cylF8gi9bULYcALCQ* buffer);
N_LIB_PRIVATE N_NIMCALL(void, uniform__OOZfauZsrcZfauZshader_3379)(tyObject_ShaderObj__KFmcUvp7lIrtBdspoRxLXw* shader, NimStringV2 name, tyObject_Sampler__xQXqueoTRZOwCBoD5nnvhg value);
N_LIB_PRIVATE N_NIMCALL(void, sampler__OOZfauZsrcZfauZshader_3371)(tyObject_FramebufferObj__1pPqnr9cylF8gi9bULYcALCQ* buf, NI index, tyObject_Sampler__xQXqueoTRZOwCBoD5nnvhg* Result);
N_LIB_PRIVATE N_NIMCALL(void, renderInternal__OOZfauZsrcZfauZg50Zbloom_55)(tyObject_MeshObj__cPggZRHFWvGLKpQsZMF8yA* mesh, tyObject_ShaderObj__KFmcUvp7lIrtBdspoRxLXw* shader, tyObject_MeshParam__PTeep4m69bNi7Bk4ErRbSdw* args);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p);
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZfauZsrcZfauZframebuffer_14)(tyObject_FramebufferObj__1pPqnr9cylF8gi9bULYcALCQ* buffer);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p, NI alignment);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZfauZsrcZfauZshader_44)(tyObject_ShaderObj__KFmcUvp7lIrtBdspoRxLXw* shader);
N_LIB_PRIVATE N_NIMCALL(tyObject_FramebufferObj__1pPqnr9cylF8gi9bULYcALCQ*, newFramebuffer__OOZfauZsrcZfauZframebuffer_59)(tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ size, NIM_BOOL depth);
static N_INLINE(tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ, vec2i__OOZfauZsrcZfauZfmath_441)(NI xy);
N_LIB_PRIVATE N_NIMCALL(tyObject_ShaderObj__KFmcUvp7lIrtBdspoRxLXw*, newShader__OOZfauZsrcZfauZshader_65)(NimStringV2 vertexSource, NimStringV2 fragmentSource);
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__ZkEsBptFwabl0cpwMG9cGuA_2 = { 11 | NIM_STRLIT_FLAG, "u_threshold" };
static const NimStringV2 TM__ZkEsBptFwabl0cpwMG9cGuA_3 = {11, (NimStrPayload*)&TM__ZkEsBptFwabl0cpwMG9cGuA_2};
extern NIM_CONST tyObject_Blending__hsAju9cB1hd79a6H4b5CoxVQ blendDisabled__OOZfauZsrcZfauZmesh_82;
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__ZkEsBptFwabl0cpwMG9cGuA_4 = { 6 | NIM_STRLIT_FLAG, "u_size" };
static const NimStringV2 TM__ZkEsBptFwabl0cpwMG9cGuA_5 = {6, (NimStrPayload*)&TM__ZkEsBptFwabl0cpwMG9cGuA_4};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__ZkEsBptFwabl0cpwMG9cGuA_6 = { 9 | NIM_STRLIT_FLAG, "u_texture" };
static const NimStringV2 TM__ZkEsBptFwabl0cpwMG9cGuA_7 = {9, (NimStrPayload*)&TM__ZkEsBptFwabl0cpwMG9cGuA_6};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__ZkEsBptFwabl0cpwMG9cGuA_8 = { 5 | NIM_STRLIT_FLAG, "u_dir" };
static const NimStringV2 TM__ZkEsBptFwabl0cpwMG9cGuA_9 = {5, (NimStrPayload*)&TM__ZkEsBptFwabl0cpwMG9cGuA_8};
static const NimStringV2 TM__ZkEsBptFwabl0cpwMG9cGuA_10 = {9, (NimStrPayload*)&TM__ZkEsBptFwabl0cpwMG9cGuA_6};
static const NimStringV2 TM__ZkEsBptFwabl0cpwMG9cGuA_11 = {5, (NimStrPayload*)&TM__ZkEsBptFwabl0cpwMG9cGuA_8};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__ZkEsBptFwabl0cpwMG9cGuA_12 = { 10 | NIM_STRLIT_FLAG, "u_texture0" };
static const NimStringV2 TM__ZkEsBptFwabl0cpwMG9cGuA_13 = {10, (NimStrPayload*)&TM__ZkEsBptFwabl0cpwMG9cGuA_12};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__ZkEsBptFwabl0cpwMG9cGuA_14 = { 10 | NIM_STRLIT_FLAG, "u_texture1" };
static const NimStringV2 TM__ZkEsBptFwabl0cpwMG9cGuA_15 = {10, (NimStrPayload*)&TM__ZkEsBptFwabl0cpwMG9cGuA_14};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__ZkEsBptFwabl0cpwMG9cGuA_16 = { 16 | NIM_STRLIT_FLAG, "u_bloomIntensity" };
static const NimStringV2 TM__ZkEsBptFwabl0cpwMG9cGuA_17 = {16, (NimStrPayload*)&TM__ZkEsBptFwabl0cpwMG9cGuA_16};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__ZkEsBptFwabl0cpwMG9cGuA_18 = { 19 | NIM_STRLIT_FLAG, "u_originalIntensity" };
static const NimStringV2 TM__ZkEsBptFwabl0cpwMG9cGuA_19 = {19, (NimStrPayload*)&TM__ZkEsBptFwabl0cpwMG9cGuA_18};
static const struct {
  NI cap; NIM_CHAR data[115+1];
} TM__ZkEsBptFwabl0cpwMG9cGuA_20 = { 115 | NIM_STRLIT_FLAG, "attribute vec4 a_pos;\012attribute vec2 a_uv; \012varying vec2 v_uv;\012\012void main(){\012\011v_uv = a_uv;\012\011gl_Position = a_pos;\012}\012" };
static const NimStringV2 TM__ZkEsBptFwabl0cpwMG9cGuA_21 = {115, (NimStrPayload*)&TM__ZkEsBptFwabl0cpwMG9cGuA_20};
static const struct {
  NI cap; NIM_CHAR data[287+1];
} TM__ZkEsBptFwabl0cpwMG9cGuA_22 = { 287 | NIM_STRLIT_FLAG, "  uniform lowp sampler2D u_texture;\012  uniform float u_threshold;\012  varying vec2 v_uv;\012\012  void main(){\012    vec4 color = texture2D(u_texture, v_uv);\012    if(color.r + color.g + color.b > u_threshold * 3.0){\012      gl_FragColor = color;\012    }else{\012      gl_FragColor = vec4(0.0);\012    }\012  }\012  " };
static const NimStringV2 TM__ZkEsBptFwabl0cpwMG9cGuA_23 = {287, (NimStrPayload*)&TM__ZkEsBptFwabl0cpwMG9cGuA_22};
static const NimStringV2 TM__ZkEsBptFwabl0cpwMG9cGuA_24 = {115, (NimStrPayload*)&TM__ZkEsBptFwabl0cpwMG9cGuA_20};
static const struct {
  NI cap; NIM_CHAR data[395+1];
} TM__ZkEsBptFwabl0cpwMG9cGuA_25 = { 395 | NIM_STRLIT_FLAG, "  uniform lowp sampler2D u_texture0;\012  uniform lowp sampler2D u_texture1;\012  uniform lowp float u_bloomIntensity;\012  uniform lowp float u_originalIntensity;\012\012  varying vec2 v_uv;\012\012  void main(){\012    vec4 original = texture2D(u_texture0, v_uv) * u_originalIntensity;\012    vec4 bloom = texture2D(u_texture1, v_uv) * u_bloomIntensity;\012    gl_FragColor = original * (vec4(1.0) - bloom) + bloom;\012  }\012\012  " };
static const NimStringV2 TM__ZkEsBptFwabl0cpwMG9cGuA_26 = {395, (NimStrPayload*)&TM__ZkEsBptFwabl0cpwMG9cGuA_25};
static const struct {
  NI cap; NIM_CHAR data[650+1];
} TM__ZkEsBptFwabl0cpwMG9cGuA_27 = { 650 | NIM_STRLIT_FLAG, "  attribute vec4 a_pos;\012  attribute vec2 a_uv; \012  uniform vec2 u_dir;\012  uniform vec2 u_size;\012  varying vec2 v_texCoords0;\012  varying vec2 v_texCoords1;\012  varying vec2 v_texCoords2;\012  varying vec2 v_texCoords3;\012  varying vec2 v_texCoords4;\012  const vec2 futher = vec2(3.2307692308, 3.2307692308);\012  const vec2 closer = vec2(1.3846153846, 1.3846153846);\012\012  void main(){\012    vec2 sizeAndDir = u_dir / u_size;\012    vec2 f = futher*sizeAndDir;\012    vec2 c = closer*sizeAndDir;\012    \012    v_texCoords0 = a_uv - f;\012    v_texCoords1 = a_uv - c;\012    v_texCoords2 = a_uv;\012    v_texCoords3 = a_uv + c;\012    v_texCoords4 = a_uv + f;\012    \012    gl_Position = a_pos;\012  }\012  " };
static const NimStringV2 TM__ZkEsBptFwabl0cpwMG9cGuA_28 = {650, (NimStrPayload*)&TM__ZkEsBptFwabl0cpwMG9cGuA_27};
static const struct {
  NI cap; NIM_CHAR data[582+1];
} TM__ZkEsBptFwabl0cpwMG9cGuA_29 = { 582 | NIM_STRLIT_FLAG, "  uniform lowp sampler2D u_texture;\012  varying vec2 v_texCoords0;\012  varying vec2 v_texCoords1;\012  varying vec2 v_texCoords2;\012  varying vec2 v_texCoords3;\012  varying vec2 v_texCoords4;\012  const float center = 0.2270270270;\012  const float close = 0.3162162162;\012  const float far = 0.0702702703;\012\012  void main(){\012    gl_FragColor = far * texture2D(u_texture, v_texCoords0)\012        + close * texture2D(u_texture, v_texCoords1)\012        + center * texture2D(u_texture, v_texCoords2)\012        + close * texture2D(u_texture, v_texCoords3)\012        + far * texture2D(u_texture, v_texCoords4);\012  }\012  " };
static const NimStringV2 TM__ZkEsBptFwabl0cpwMG9cGuA_30 = {582, (NimStrPayload*)&TM__ZkEsBptFwabl0cpwMG9cGuA_29};
extern tyObject_FauState__309cTFhuUrshBEQHbLmaQlw fau__OOZfauZsrcZfauZglobals_252;
extern NIM_BOOL nimInErrorMode__system_3443;
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__system_3443);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ, vec2i__OOZfauZsrcZfauZfmath_428)(NI x, NI y) {
	tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ result;
	NI colontmpD_;
	NI colontmpD__2;
	nimZeroMem((void*)(&result), sizeof(tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ));
	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	nimZeroMem((void*)(&result), sizeof(tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ));
	colontmpD_ = x;
	result.x = colontmpD_;
	colontmpD__2 = y;
	result.y = colontmpD__2;
	return result;
}
static N_INLINE(tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ, div__OOZfauZsrcZfauZfmath_665)(tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ vecX60gensym40_, NI otherX60gensym40_) {
	tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ));
	result = vec2i__OOZfauZsrcZfauZfmath_428((NI)(vecX60gensym40_.x / otherX60gensym40_), (NI)(vecX60gensym40_.y / otherX60gensym40_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ*, texture__OOZfauZsrcZfauZframebuffer_19)(tyObject_FramebufferObj__1pPqnr9cylF8gi9bULYcALCQ* buffer) {
	tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ* result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	eqcopy___OOZfauZsrcZfauZtexture_116(&result, (*buffer).texture);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_FramebufferObj__1pPqnr9cylF8gi9bULYcALCQ*, buffer__OOZfauZsrcZfauZg50Zbloom_24)(tyObject_Bloom__kDHmp9bu9aDv39a8ndZ4EZHWQ* bloom, tyObject_Color__OSWJq3HNkIl1V7S3GsYvBg clearColor) {
	tyObject_FramebufferObj__1pPqnr9cylF8gi9bULYcALCQ* result;
	tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ* colontmpD_;
	tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ* colontmpD__2;
	tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ* colontmpD__3;
	tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ T2_;
	tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ T3_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	colontmpD_ = NIM_NIL;
	colontmpD__2 = NIM_NIL;
	colontmpD__3 = NIM_NIL;
	resize__OOZfauZsrcZfauZframebuffer_22((*bloom).buffer, fau__OOZfauZsrcZfauZglobals_252.sizei);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_ = div__OOZfauZsrcZfauZfmath_665(fau__OOZfauZsrcZfauZglobals_252.sizei, (*bloom).scaling);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	resize__OOZfauZsrcZfauZframebuffer_22((*bloom).p1, T2_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T3_ = div__OOZfauZsrcZfauZfmath_665(fau__OOZfauZsrcZfauZglobals_252.sizei, (*bloom).scaling);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	resize__OOZfauZsrcZfauZframebuffer_22((*bloom).p2, T3_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	colontmpD_ = texture__OOZfauZsrcZfauZframebuffer_19((*bloom).buffer);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	filtereq___OOZfauZsrcZfauZtexture_63(colontmpD_, ((tyEnum_TextureFilter__zerQ3LMmc801hL4AG54gqg) 1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	colontmpD__2 = texture__OOZfauZsrcZfauZframebuffer_19((*bloom).p1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	filtereq___OOZfauZsrcZfauZtexture_63(colontmpD__2, ((tyEnum_TextureFilter__zerQ3LMmc801hL4AG54gqg) 1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	colontmpD__3 = texture__OOZfauZsrcZfauZframebuffer_19((*bloom).p2);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	filtereq___OOZfauZsrcZfauZtexture_63(colontmpD__3, ((tyEnum_TextureFilter__zerQ3LMmc801hL4AG54gqg) 1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	clear__OOZfauZsrcZfauZframebuffer_87((*bloom).buffer, clearColor);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	eqcopy___OOZfauZsrcZfauZframebuffer_73(&result, (*bloom).buffer);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	eqdestroy___OOZfauZsrcZfauZtexture_113(&colontmpD__3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___OOZfauZsrcZfauZtexture_113(&colontmpD__2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___OOZfauZsrcZfauZtexture_113(&colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___OOZfauZsrcZfauZtexture_113(&colontmpD__3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___OOZfauZsrcZfauZtexture_113(&colontmpD__2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___OOZfauZsrcZfauZtexture_113(&colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, meshParams__OOZfauZsrcZfauZmesh_98)(tyObject_FramebufferObj__1pPqnr9cylF8gi9bULYcALCQ* buffer, NI offset, NI count, NIM_BOOL depth, NIM_BOOL writeDepth, tyObject_Blending__hsAju9cB1hd79a6H4b5CoxVQ blend, tyEnum_CullFace__0G6mOarn9cnCWCzi0fEshew cullFace, tyObject_MeshParam__PTeep4m69bNi7Bk4ErRbSdw* Result) {
	tyObject_FramebufferObj__1pPqnr9cylF8gi9bULYcALCQ* colontmpD_;
	NI colontmpD__2;
	NI colontmpD__3;
	NIM_BOOL colontmpD__4;
	NIM_BOOL colontmpD__5;
	tyObject_Blending__hsAju9cB1hd79a6H4b5CoxVQ colontmpD__6;
	tyEnum_CullFace__0G6mOarn9cnCWCzi0fEshew colontmpD__7;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colontmpD_ = NIM_NIL;
	colontmpD__2 = (NI)0;
	colontmpD__3 = (NI)0;
	colontmpD__4 = (NIM_BOOL)0;
	colontmpD__5 = (NIM_BOOL)0;
	nimZeroMem((void*)(&colontmpD__6), sizeof(tyObject_Blending__hsAju9cB1hd79a6H4b5CoxVQ));
	colontmpD__7 = (tyEnum_CullFace__0G6mOarn9cnCWCzi0fEshew)0;
	nimZeroMem((void*)Result, sizeof(tyObject_MeshParam__PTeep4m69bNi7Bk4ErRbSdw));
	colontmpD_ = 0;
	eqcopy___OOZfauZsrcZfauZframebuffer_73(&colontmpD_, buffer);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*Result).buffer = colontmpD_;
	colontmpD__2 = offset;
	(*Result).offset = colontmpD__2;
	colontmpD__3 = count;
	(*Result).count = colontmpD__3;
	colontmpD__4 = depth;
	(*Result).depth = colontmpD__4;
	colontmpD__5 = writeDepth;
	(*Result).writeDepth = colontmpD__5;
	colontmpD__6 = blend;
	(*Result).blend = colontmpD__6;
	colontmpD__7 = cullFace;
	(*Result).cullFace = colontmpD__7;
	}BeforeRet_: ;
}
static N_INLINE(tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w, vec2__OOZfauZsrcZfauZfmath_446)(tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ v) {
	tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w result;
	NI colontmpD_;
	NI colontmpD__2;
	nimZeroMem((void*)(&result), sizeof(tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w));
	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	nimZeroMem((void*)(&result), sizeof(tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w));
	colontmpD_ = v.x;
	result.x = ((NF32) (colontmpD_));
	colontmpD__2 = v.y;
	result.y = ((NF32) (colontmpD__2));
	return result;
}
static N_INLINE(tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ, size__OOZfauZsrcZfauZframebuffer_16)(tyObject_FramebufferObj__1pPqnr9cylF8gi9bULYcALCQ* buffer) {
	tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ result;
	nimZeroMem((void*)(&result), sizeof(tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ));
	result = (*buffer).size;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, blit__OOZfauZsrcZfauZg50Zbloom_28)(tyObject_Bloom__kDHmp9bu9aDv39a8ndZ4EZHWQ* bloom, tyObject_MeshParam__PTeep4m69bNi7Bk4ErRbSdw* params, NF32 intensity, NF32 threshold) {
	tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ* colontmpD_;
	tyObject_MeshParam__PTeep4m69bNi7Bk4ErRbSdw colontmpD__2;
	tyObject_Sampler__xQXqueoTRZOwCBoD5nnvhg colontmpD__3;
	tyObject_Sampler__xQXqueoTRZOwCBoD5nnvhg colontmpD__4;
	tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ T6_;
	tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w T7_;
NIM_BOOL oldNimErrFin11_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colontmpD_ = NIM_NIL;
	nimZeroMem((void*)(&colontmpD__2), sizeof(tyObject_MeshParam__PTeep4m69bNi7Bk4ErRbSdw));
	nimZeroMem((void*)(&colontmpD__3), sizeof(tyObject_Sampler__xQXqueoTRZOwCBoD5nnvhg));
	nimZeroMem((void*)(&colontmpD__4), sizeof(tyObject_Sampler__xQXqueoTRZOwCBoD5nnvhg));
	{
		colontmpD_ = texture__OOZfauZsrcZfauZframebuffer_19((*bloom).buffer);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!(colontmpD_ == 0)) goto LA4_;
		eqdestroy___OOZfauZsrcZfauZshader_3359((&colontmpD__4));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___OOZfauZsrcZfauZshader_3359((&colontmpD__3));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___OOZfauZsrcZfauZmesh_116((&colontmpD__2));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___OOZfauZsrcZfauZtexture_113(&colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	LA4_: ;
	uniform__OOZfauZsrcZfauZshader_3417((*bloom).thresh, TM__ZkEsBptFwabl0cpwMG9cGuA_3, threshold);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	meshParams__OOZfauZsrcZfauZmesh_98((*bloom).p1, ((NI) 0), ((NI) -1), NIM_FALSE, NIM_TRUE, blendDisabled__OOZfauZsrcZfauZmesh_82, ((tyEnum_CullFace__0G6mOarn9cnCWCzi0fEshew) 1), (&colontmpD__2));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	blit__OOZfauZsrcZfauZg50Zbloom_36((*bloom).buffer, (*bloom).thresh, (&colontmpD__2));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T6_ = size__OOZfauZsrcZfauZframebuffer_16((*bloom).p1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T7_ = vec2__OOZfauZsrcZfauZfmath_446(T6_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	uniform__OOZfauZsrcZfauZshader_3422((*bloom).blur, TM__ZkEsBptFwabl0cpwMG9cGuA_5, T7_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		NI i;
		NI i_2;
		i = (NI)0;
		i_2 = ((NI) 0);
		{
			while (1) {
				tyObject_Sampler__xQXqueoTRZOwCBoD5nnvhg colontmpD__5;
				tyObject_MeshParam__PTeep4m69bNi7Bk4ErRbSdw colontmpD__6;
				tyObject_Sampler__xQXqueoTRZOwCBoD5nnvhg colontmpD__7;
				tyObject_MeshParam__PTeep4m69bNi7Bk4ErRbSdw colontmpD__8;
				tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w T12_;
				tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w T13_;
				if (!(i_2 < (*bloom).blurPasses)) goto LA10;
				nimZeroMem((void*)(&colontmpD__5), sizeof(tyObject_Sampler__xQXqueoTRZOwCBoD5nnvhg));
				nimZeroMem((void*)(&colontmpD__6), sizeof(tyObject_MeshParam__PTeep4m69bNi7Bk4ErRbSdw));
				nimZeroMem((void*)(&colontmpD__7), sizeof(tyObject_Sampler__xQXqueoTRZOwCBoD5nnvhg));
				nimZeroMem((void*)(&colontmpD__8), sizeof(tyObject_MeshParam__PTeep4m69bNi7Bk4ErRbSdw));
				i = i_2;
				sampler__OOZfauZsrcZfauZshader_3371((*bloom).p1, ((NI) 0), (&colontmpD__5));
				if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
				uniform__OOZfauZsrcZfauZshader_3379((*bloom).blur, TM__ZkEsBptFwabl0cpwMG9cGuA_7, colontmpD__5);
				if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
				nimZeroMem((void*)(&T12_), sizeof(tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w));
				T12_.x = 1.0f;
				T12_.y = 0.0f;
				uniform__OOZfauZsrcZfauZshader_3422((*bloom).blur, TM__ZkEsBptFwabl0cpwMG9cGuA_9, T12_);
				if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
				meshParams__OOZfauZsrcZfauZmesh_98((*bloom).p2, ((NI) 0), ((NI) -1), NIM_FALSE, NIM_TRUE, blendDisabled__OOZfauZsrcZfauZmesh_82, ((tyEnum_CullFace__0G6mOarn9cnCWCzi0fEshew) 1), (&colontmpD__6));
				if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
				renderInternal__OOZfauZsrcZfauZg50Zbloom_55(fau__OOZfauZsrcZfauZglobals_252.quad, (*bloom).blur, (&colontmpD__6));
				if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
				sampler__OOZfauZsrcZfauZshader_3371((*bloom).p2, ((NI) 0), (&colontmpD__7));
				if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
				uniform__OOZfauZsrcZfauZshader_3379((*bloom).blur, TM__ZkEsBptFwabl0cpwMG9cGuA_10, colontmpD__7);
				if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
				nimZeroMem((void*)(&T13_), sizeof(tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w));
				T13_.x = 0.0f;
				T13_.y = 1.0f;
				uniform__OOZfauZsrcZfauZshader_3422((*bloom).blur, TM__ZkEsBptFwabl0cpwMG9cGuA_11, T13_);
				if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
				meshParams__OOZfauZsrcZfauZmesh_98((*bloom).p1, ((NI) 0), ((NI) -1), NIM_FALSE, NIM_TRUE, blendDisabled__OOZfauZsrcZfauZmesh_82, ((tyEnum_CullFace__0G6mOarn9cnCWCzi0fEshew) 1), (&colontmpD__8));
				if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
				renderInternal__OOZfauZsrcZfauZg50Zbloom_55(fau__OOZfauZsrcZfauZglobals_252.quad, (*bloom).blur, (&colontmpD__8));
				if (NIM_UNLIKELY(*nimErr_)) goto LA11_;
				i_2 += ((NI) 1);
				{
					LA11_:;
				}
				{
					oldNimErrFin11_ = *nimErr_; *nimErr_ = NIM_FALSE;
					eqdestroy___OOZfauZsrcZfauZmesh_116((&colontmpD__8));
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					eqdestroy___OOZfauZsrcZfauZshader_3359((&colontmpD__7));
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					eqdestroy___OOZfauZsrcZfauZmesh_116((&colontmpD__6));
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					eqdestroy___OOZfauZsrcZfauZshader_3359((&colontmpD__5));
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					*nimErr_ = oldNimErrFin11_;
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			} LA10: ;
		}
	}
	sampler__OOZfauZsrcZfauZshader_3371((*bloom).buffer, ((NI) 0), (&colontmpD__3));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	uniform__OOZfauZsrcZfauZshader_3379((*bloom).bloom, TM__ZkEsBptFwabl0cpwMG9cGuA_13, colontmpD__3);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	sampler__OOZfauZsrcZfauZshader_3371((*bloom).p1, ((NI) 1), (&colontmpD__4));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	uniform__OOZfauZsrcZfauZshader_3379((*bloom).bloom, TM__ZkEsBptFwabl0cpwMG9cGuA_15, colontmpD__4);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	uniform__OOZfauZsrcZfauZshader_3417((*bloom).bloom, TM__ZkEsBptFwabl0cpwMG9cGuA_17, intensity);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	uniform__OOZfauZsrcZfauZshader_3417((*bloom).bloom, TM__ZkEsBptFwabl0cpwMG9cGuA_19, 1.0f);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	renderInternal__OOZfauZsrcZfauZg50Zbloom_55(fau__OOZfauZsrcZfauZglobals_252.quad, (*bloom).bloom, params);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___OOZfauZsrcZfauZshader_3359((&colontmpD__4));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___OOZfauZsrcZfauZshader_3359((&colontmpD__3));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___OOZfauZsrcZfauZmesh_116((&colontmpD__2));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___OOZfauZsrcZfauZtexture_113(&colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU64)(((NU) (x))) - (NU64)(((NU) (y))))));
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* cell;
		NI T5_;
		if (!!((p == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_716(((NI) (ptrdiff_t) (p)), ((NI) 8));
		cell = ((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T5_));
		{
			if (!((NI)((*cell).rc & ((NI) -8)) == ((NI) 0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
		LA8_: ;
		{
			(*cell).rc -= ((NI) 8);
		}
		LA6_: ;
	}
	LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___main_253481)(tyObject_Bloom__kDHmp9bu9aDv39a8ndZ4EZHWQ* dest, tyObject_Bloom__kDHmp9bu9aDv39a8ndZ4EZHWQ* src) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest).buffer);
		if (!T3_) goto LA4_;
		eqdestroy___OOZfauZsrcZfauZframebuffer_14((*dest).buffer);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimRawDispose((*dest).buffer, ((NI) 8));
	}
	LA4_: ;
	(*dest).buffer = (*src).buffer;
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLast((*dest).p1);
		if (!T8_) goto LA9_;
		eqdestroy___OOZfauZsrcZfauZframebuffer_14((*dest).p1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimRawDispose((*dest).p1, ((NI) 8));
	}
	LA9_: ;
	(*dest).p1 = (*src).p1;
	{
		NIM_BOOL T13_;
		T13_ = (NIM_BOOL)0;
		T13_ = nimDecRefIsLast((*dest).p2);
		if (!T13_) goto LA14_;
		eqdestroy___OOZfauZsrcZfauZframebuffer_14((*dest).p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimRawDispose((*dest).p2, ((NI) 8));
	}
	LA14_: ;
	(*dest).p2 = (*src).p2;
	{
		NIM_BOOL T18_;
		T18_ = (NIM_BOOL)0;
		T18_ = nimDecRefIsLast((*dest).thresh);
		if (!T18_) goto LA19_;
		eqdestroy___OOZfauZsrcZfauZshader_44((*dest).thresh);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimRawDispose((*dest).thresh, ((NI) 8));
	}
	LA19_: ;
	(*dest).thresh = (*src).thresh;
	{
		NIM_BOOL T23_;
		T23_ = (NIM_BOOL)0;
		T23_ = nimDecRefIsLast((*dest).bloom);
		if (!T23_) goto LA24_;
		eqdestroy___OOZfauZsrcZfauZshader_44((*dest).bloom);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimRawDispose((*dest).bloom, ((NI) 8));
	}
	LA24_: ;
	(*dest).bloom = (*src).bloom;
	{
		NIM_BOOL T28_;
		T28_ = (NIM_BOOL)0;
		T28_ = nimDecRefIsLast((*dest).blur);
		if (!T28_) goto LA29_;
		eqdestroy___OOZfauZsrcZfauZshader_44((*dest).blur);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimRawDispose((*dest).blur, ((NI) 8));
	}
	LA29_: ;
	(*dest).blur = (*src).blur;
	(*dest).blurPasses = (*src).blurPasses;
	(*dest).scaling = (*src).scaling;
	}BeforeRet_: ;
}
static N_INLINE(tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ, vec2i__OOZfauZsrcZfauZfmath_441)(NI xy) {
	tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ result;
	NI colontmpD_;
	NI colontmpD__2;
	nimZeroMem((void*)(&result), sizeof(tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ));
	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	nimZeroMem((void*)(&result), sizeof(tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ));
	colontmpD_ = xy;
	result.x = colontmpD_;
	colontmpD__2 = xy;
	result.y = colontmpD__2;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, newBloom__OOZfauZsrcZfauZg50Zbloom_19)(NI scaling, NI passes, NIM_BOOL depth, tyObject_Bloom__kDHmp9bu9aDv39a8ndZ4EZHWQ* Result) {
	tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ T1_;
	tyObject_FramebufferObj__1pPqnr9cylF8gi9bULYcALCQ* T2_;
	tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ T3_;
	tyObject_FramebufferObj__1pPqnr9cylF8gi9bULYcALCQ* T4_;
	tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ T5_;
	tyObject_FramebufferObj__1pPqnr9cylF8gi9bULYcALCQ* T6_;
	tyObject_ShaderObj__KFmcUvp7lIrtBdspoRxLXw* T7_;
	tyObject_ShaderObj__KFmcUvp7lIrtBdspoRxLXw* T8_;
	tyObject_ShaderObj__KFmcUvp7lIrtBdspoRxLXw* T9_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyObject_Bloom__kDHmp9bu9aDv39a8ndZ4EZHWQ));
	T1_ = vec2i__OOZfauZsrcZfauZfmath_441(((NI) 2));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T2_ = NIM_NIL;
	T2_ = newFramebuffer__OOZfauZsrcZfauZframebuffer_59(T1_, depth);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*Result).buffer = T2_;
	T3_ = vec2i__OOZfauZsrcZfauZfmath_441(((NI) 2));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T4_ = NIM_NIL;
	T4_ = newFramebuffer__OOZfauZsrcZfauZframebuffer_59(T3_, NIM_FALSE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*Result).p1 = T4_;
	T5_ = vec2i__OOZfauZsrcZfauZfmath_441(((NI) 2));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T6_ = NIM_NIL;
	T6_ = newFramebuffer__OOZfauZsrcZfauZframebuffer_59(T5_, NIM_FALSE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*Result).p2 = T6_;
	(*Result).scaling = scaling;
	(*Result).blurPasses = passes;
	T7_ = NIM_NIL;
	T7_ = newShader__OOZfauZsrcZfauZshader_65(TM__ZkEsBptFwabl0cpwMG9cGuA_21, TM__ZkEsBptFwabl0cpwMG9cGuA_23);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*Result).thresh = T7_;
	T8_ = NIM_NIL;
	T8_ = newShader__OOZfauZsrcZfauZshader_65(TM__ZkEsBptFwabl0cpwMG9cGuA_24, TM__ZkEsBptFwabl0cpwMG9cGuA_26);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*Result).bloom = T8_;
	T9_ = NIM_NIL;
	T9_ = newShader__OOZfauZsrcZfauZshader_65(TM__ZkEsBptFwabl0cpwMG9cGuA_28, TM__ZkEsBptFwabl0cpwMG9cGuA_30);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*Result).blur = T9_;
	}BeforeRet_: ;
}
