/* Generated by Nim Compiler v1.6.4 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_SaveState__JG21xxTUaJxQnXwaK3dMWw tyObject_SaveState__JG21xxTUaJxQnXwaK3dMWw;
typedef struct tySequence__1G1c1pZ4AzoGz9awoII9a5sA tySequence__1G1c1pZ4AzoGz9awoII9a5sA;
typedef struct tySequence__1G1c1pZ4AzoGz9awoII9a5sA_Content tySequence__1G1c1pZ4AzoGz9awoII9a5sA_Content;
typedef struct tySequence__qwqHTkRvwhrRyENtudHQ7g tySequence__qwqHTkRvwhrRyENtudHQ7g;
typedef struct tySequence__qwqHTkRvwhrRyENtudHQ7g_Content tySequence__qwqHTkRvwhrRyENtudHQ7g_Content;
typedef struct tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ;
typedef struct tyObject_Table__i55W8RrwGKsG9cl0sAKxgkQ tyObject_Table__i55W8RrwGKsG9cl0sAKxgkQ;
typedef struct tySequence__pUxI6Ljo6IKKHXKOZkQ7Og tySequence__pUxI6Ljo6IKKHXKOZkQ7Og;
typedef struct tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content;
typedef struct tyTuple__BUNQL5x2cKJaBSzOn5pwkg tyTuple__BUNQL5x2cKJaBSzOn5pwkg;
typedef struct tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w;
typedef struct tyObject_Table__OxRqfkudSQS6aNVHuUx9bSg tyObject_Table__OxRqfkudSQS6aNVHuUx9bSg;
typedef struct tySequence__v87TdQ9b9cLCVESucM9cmtTyg tySequence__v87TdQ9b9cLCVESucM9cmtTyg;
typedef struct tySequence__v87TdQ9b9cLCVESucM9cmtTyg_Content tySequence__v87TdQ9b9cLCVESucM9cmtTyg_Content;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content tySequence__uB9b75OUPRENsBAu4AnoePA_Content;
typedef struct tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ;
typedef struct tyTuple__DtYz89aEFgC8CcjjapPJ8Rg tyTuple__DtYz89aEFgC8CcjjapPJ8Rg;
typedef struct tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
struct tySequence__1G1c1pZ4AzoGz9awoII9a5sA {
  NI len; tySequence__1G1c1pZ4AzoGz9awoII9a5sA_Content* p;
};
struct tySequence__qwqHTkRvwhrRyENtudHQ7g {
  NI len; tySequence__qwqHTkRvwhrRyENtudHQ7g_Content* p;
};
struct tySequence__pUxI6Ljo6IKKHXKOZkQ7Og {
  NI len; tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content* p;
};
struct tyObject_Table__i55W8RrwGKsG9cl0sAKxgkQ {
tySequence__pUxI6Ljo6IKKHXKOZkQ7Og data;
NI counter;
};
struct tyObject_SaveState__JG21xxTUaJxQnXwaK3dMWw {
NIM_BOOL introDone;
tySequence__1G1c1pZ4AzoGz9awoII9a5sA units;
NI copper;
NI rolls;
tySequence__qwqHTkRvwhrRyENtudHQ7g scores;
tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ* lastUnit;
tyObject_Table__i55W8RrwGKsG9cl0sAKxgkQ duplicates;
};
typedef tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ* tyArray__Xev9cG9bEVa9aj1taYYC5Nobg[9];
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyTuple__BUNQL5x2cKJaBSzOn5pwkg unit, NI moves, void* ClE_0);
void* ClE_0;
} tyProc__ojNDjFK5r5ivRd8Rxp6ZuA;
typedef N_NIMCALL_PTR(void, tyProc__cMnJRgMxnPy9bYjqfhi18yg) (tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ* unit, tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w pos);
struct tySequence__v87TdQ9b9cLCVESucM9cmtTyg {
  NI len; tySequence__v87TdQ9b9cLCVESucM9cmtTyg_Content* p;
};
struct tyObject_Table__OxRqfkudSQS6aNVHuUx9bSg {
tySequence__v87TdQ9b9cLCVESucM9cmtTyg data;
NI counter;
};
struct tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ {
NimStringV2 name;
NimStringV2 title;
NimStringV2 subtitle;
NimStringV2 ability;
NI abilityReload;
tyProc__ojNDjFK5r5ivRd8Rxp6ZuA abilityProc;
tyProc__cMnJRgMxnPy9bYjqfhi18yg draw;
tyObject_Table__OxRqfkudSQS6aNVHuUx9bSg textures;
NIM_BOOL unmoving;
NIM_BOOL unobtainable;
NIM_BOOL wasOver;
NF32 fade;
NF32 jump;
NIM_BOOL jumping;
NF32 clickTime;
};
typedef NU8 tyEnum_CompressedDataFormat__hW3Jjtknic3hfPFuiaDRPw;
typedef NimStringV2 tyArray__nHXaesL0DJZHyVS07ARPRA[1];
struct TNimTypeV2 {
void* destructor;
NI size;
NI align;
NCSTRING name;
void* traceImpl;
void* typeInfoV1;
NI flags;
};
struct RootObj {
TNimTypeV2* m_type;
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  NI len; tySequence__uB9b75OUPRENsBAu4AnoePA_Content* p;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringV2 message;
tySequence__uB9b75OUPRENsBAu4AnoePA trace;
Exception* up;
};


#ifndef tySequence__1G1c1pZ4AzoGz9awoII9a5sA_Content_PP
#define tySequence__1G1c1pZ4AzoGz9awoII9a5sA_Content_PP
struct tySequence__1G1c1pZ4AzoGz9awoII9a5sA_Content { NI cap; tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ* data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__qwqHTkRvwhrRyENtudHQ7g_Content_PP
#define tySequence__qwqHTkRvwhrRyENtudHQ7g_Content_PP
struct tySequence__qwqHTkRvwhrRyENtudHQ7g_Content { NI cap; NI data[SEQ_DECL_SIZE];};
#endif

      struct tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ {
NI Field0;
NimStringV2 Field1;
NI Field2;
};


#ifndef tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content_PP
#define tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content_PP
struct tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content { NI cap; tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ data[SEQ_DECL_SIZE];};
#endif

      struct tyTuple__BUNQL5x2cKJaBSzOn5pwkg {
NI32 Field0;
NI32 Field1;
};
struct tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w {
NF32 x;
NF32 y;
};
struct tyTuple__DtYz89aEFgC8CcjjapPJ8Rg {
NI Field0;
NimStringV2 Field1;
tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ* Field2;
};


#ifndef tySequence__v87TdQ9b9cLCVESucM9cmtTyg_Content_PP
#define tySequence__v87TdQ9b9cLCVESucM9cmtTyg_Content_PP
struct tySequence__v87TdQ9b9cLCVESucM9cmtTyg_Content { NI cap; tyTuple__DtYz89aEFgC8CcjjapPJ8Rg data[SEQ_DECL_SIZE];};
#endif

      struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};


#ifndef tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
#define tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content { NI cap; tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};
#endif

      static N_INLINE(NimStringV2, slash___pureZos_131)(NimStringV2 head, NimStringV2 tail);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosjoinPath)(NimStringV2 head, NimStringV2 tail);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosfileExists)(NimStringV2 filename);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___vars_600)(tyObject_SaveState__JG21xxTUaJxQnXwaK3dMWw* dest, tyObject_SaveState__JG21xxTUaJxQnXwaK3dMWw* src);
N_LIB_PRIVATE N_NIMCALL(void, fromJson__saveio_375)(NimStringV2 s, tyObject_SaveState__JG21xxTUaJxQnXwaK3dMWw* Result);
N_LIB_PRIVATE N_NIMCALL(void, parseHook__OOZOOZOOZOnimbleZpkgsZjsony4549O48O49Zjsony_181)(NimStringV2 s, NI* i, NimStringV2* v);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a, NimStringV2 b);
static N_INLINE(NIM_BOOL, equalMem__system_1717)(void* a, void* b, NI size);
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___vars_795)(tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ** dest, tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ* src);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_2592)(NimStringV2* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___vars_792)(tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ** dest, tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ* src);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___vars_789)(tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ** dest);
static N_INLINE(NimStringV2, uncompress__OOZOOZOOZOnimbleZpkgsZzippy4548O57O55Zzippy_131)(NimStringV2 src, tyEnum_CompressedDataFormat__hW3Jjtknic3hfPFuiaDRPw dataFormat);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, uncompress__OOZOOZOOZOnimbleZpkgsZzippy4548O57O55Zzippy_93)(void* src, NI len, tyEnum_CompressedDataFormat__hW3Jjtknic3hfPFuiaDRPw dataFormat);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, readFile__systemZio_491)(NimStringV2 filename);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args, NI argsLen_0);
static N_INLINE(NIM_BOOL, isObj)(TNimTypeV2* obj, NCSTRING subclass);
static N_INLINE(Exception*, nimBorrowCurrentException)(void);
N_NIMCALL(NimStringV2, rawNewString)(NI cap);
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(void, copyMem__system_1709)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s, NI addlen);
N_LIB_PRIVATE N_NIMCALL(void, formatValue__pureZstrformat_160)(NimStringV2* result, NimStringV2 value, NimStringV2 specifier);
static N_INLINE(NimStringV2, getCurrentExceptionMsg__system_5952)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_2595)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(void, popCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_3188)(Exception** dest, Exception* src);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toJson__saveio_48)(tyObject_SaveState__JG21xxTUaJxQnXwaK3dMWw* v);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s, NIM_CHAR c);
static N_INLINE(NimStringV2, compress__OOZOOZOOZOnimbleZpkgsZzippy4548O57O55Zzippy_77)(NimStringV2 src, NI level, tyEnum_CompressedDataFormat__hW3Jjtknic3hfPFuiaDRPw dataFormat);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, compress__OOZOOZOOZOnimbleZpkgsZzippy4548O57O55Zzippy_7)(void* src, NI len, NI level, tyEnum_CompressedDataFormat__hW3Jjtknic3hfPFuiaDRPw dataFormat);
N_LIB_PRIVATE N_NIMCALL(void, noscreateDir)(NimStringV2 dir);
N_LIB_PRIVATE N_NIMCALL(void, writeFile__systemZio_496)(NimStringV2 filename, NimStringV2 content);
static const struct {
  NI cap; NIM_CHAR data[30+1];
} TM__aJ9cAU2XHKgQoKe80UA7djg_2 = { 30 | NIM_STRLIT_FLAG, "/data/data/io.anuke.animdustry" };
static const NimStringV2 TM__aJ9cAU2XHKgQoKe80UA7djg_3 = {30, (NimStrPayload*)&TM__aJ9cAU2XHKgQoKe80UA7djg_2};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__aJ9cAU2XHKgQoKe80UA7djg_4 = { 8 | NIM_STRLIT_FLAG, "data.bin" };
static const NimStringV2 TM__aJ9cAU2XHKgQoKe80UA7djg_5 = {8, (NimStrPayload*)&TM__aJ9cAU2XHKgQoKe80UA7djg_4};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__aJ9cAU2XHKgQoKe80UA7djg_6 = { 3 | NIM_STRLIT_FLAG, "nil" };
static const NimStringV2 TM__aJ9cAU2XHKgQoKe80UA7djg_7 = {3, (NimStrPayload*)&TM__aJ9cAU2XHKgQoKe80UA7djg_6};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__aJ9cAU2XHKgQoKe80UA7djg_9 = { 18 | NIM_STRLIT_FLAG, "Loaded game state." };
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__aJ9cAU2XHKgQoKe80UA7djg_8 = {{18, (NimStrPayload*)&TM__aJ9cAU2XHKgQoKe80UA7djg_9}}
;
static const struct {
  NI cap; NIM_CHAR data[25+1];
} TM__aJ9cAU2XHKgQoKe80UA7djg_10 = { 25 | NIM_STRLIT_FLAG, "Invalid save state JSON: " };
static const NimStringV2 TM__aJ9cAU2XHKgQoKe80UA7djg_11 = {25, (NimStrPayload*)&TM__aJ9cAU2XHKgQoKe80UA7djg_10};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__aJ9cAU2XHKgQoKe80UA7djg_12 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__aJ9cAU2XHKgQoKe80UA7djg_13 = {0, (NimStrPayload*)&TM__aJ9cAU2XHKgQoKe80UA7djg_12};
static const NimStringV2 TM__aJ9cAU2XHKgQoKe80UA7djg_14 = {0, (NimStrPayload*)&TM__aJ9cAU2XHKgQoKe80UA7djg_12};
static const struct {
  NI cap; NIM_CHAR data[25+1];
} TM__aJ9cAU2XHKgQoKe80UA7djg_15 = { 25 | NIM_STRLIT_FLAG, "Corrupt save state data: " };
static const NimStringV2 TM__aJ9cAU2XHKgQoKe80UA7djg_16 = {25, (NimStrPayload*)&TM__aJ9cAU2XHKgQoKe80UA7djg_15};
static const NimStringV2 TM__aJ9cAU2XHKgQoKe80UA7djg_17 = {0, (NimStrPayload*)&TM__aJ9cAU2XHKgQoKe80UA7djg_12};
static const struct {
  NI cap; NIM_CHAR data[33+1];
} TM__aJ9cAU2XHKgQoKe80UA7djg_18 = { 33 | NIM_STRLIT_FLAG, "Error: Save data cannot be read: " };
static const NimStringV2 TM__aJ9cAU2XHKgQoKe80UA7djg_19 = {33, (NimStrPayload*)&TM__aJ9cAU2XHKgQoKe80UA7djg_18};
static const NimStringV2 TM__aJ9cAU2XHKgQoKe80UA7djg_20 = {0, (NimStrPayload*)&TM__aJ9cAU2XHKgQoKe80UA7djg_12};
static const NimStringV2 TM__aJ9cAU2XHKgQoKe80UA7djg_21 = {3, (NimStrPayload*)&TM__aJ9cAU2XHKgQoKe80UA7djg_6};
static const struct {
  NI cap; NIM_CHAR data[34+1];
} TM__aJ9cAU2XHKgQoKe80UA7djg_22 = { 34 | NIM_STRLIT_FLAG, "Error: Failed to write save data: " };
static const NimStringV2 TM__aJ9cAU2XHKgQoKe80UA7djg_23 = {34, (NimStrPayload*)&TM__aJ9cAU2XHKgQoKe80UA7djg_22};
static const NimStringV2 TM__aJ9cAU2XHKgQoKe80UA7djg_24 = {0, (NimStrPayload*)&TM__aJ9cAU2XHKgQoKe80UA7djg_12};
N_LIB_PRIVATE NimStringV2 dataDir__saveio_7;
N_LIB_PRIVATE NimStringV2 dataFile__saveio_8;
extern NIM_BOOL nimInErrorMode__system_3443;
extern tyObject_SaveState__JG21xxTUaJxQnXwaK3dMWw save__vars_400;
extern tyArray__Xev9cG9bEVa9aj1taYYC5Nobg allUnits__vars_435;
extern tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ* unitMono__vars_427;
extern Exception* currException__system_3145;
extern Exception* currException__system_3145;
extern Exception* currException__system_3145;
extern Exception* currException__system_3145;
extern Exception* currException__system_3145;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__system_3443);
	return result;
}
static N_INLINE(NimStringV2, slash___pureZos_131)(NimStringV2 head, NimStringV2 tail) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	result = nosjoinPath(head, tail);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size) {
	int result;
	result = (int)0;
	result = memcmp(a, b, ((size_t) (size)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_1717)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = nimCmpMem(a, b, size);
	result = (T1_ == ((NI32) 0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a, NimStringV2 b) {
	NIM_BOOL result;
	NI alen;
	NI blen;
{	result = (NIM_BOOL)0;
	alen = a.len;
	blen = b.len;
	{
		if (!(alen == blen)) goto LA3_;
		{
			if (!(alen == ((NI) 0))) goto LA7_;
			result = NIM_TRUE;
			goto BeforeRet_;
		}
		LA7_: ;
		result = equalMem__system_1717(((void*) ((&a.p->data[((NI) 0)]))), ((void*) ((&b.p->data[((NI) 0)]))), ((NI) (alen)));
		goto BeforeRet_;
	}
	LA3_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, parseHook__saveio_9)(NimStringV2 s, NI* i, tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ** u) {
	NimStringV2 str;
NIM_BOOL oldNimErrFin7_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	str.len = 0; str.p = NIM_NIL;
	parseHook__OOZOOZOOZOnimbleZpkgsZjsony4549O48O49Zjsony_181(s, i, (&str));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		if (!eqStrings(str, TM__aJ9cAU2XHKgQoKe80UA7djg_7)) goto LA4_;
		eqsink___vars_795(&(*u), ((tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ*) NIM_NIL));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		eqdestroy___system_2592((&str));
		goto BeforeRet_;
	}
	LA4_: ;
	{
		tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ* other;
		NI i_2;
		other = NIM_NIL;
		i_2 = ((NI) 0);
		{
			while (1) {
				eqcopy___vars_792(&other, allUnits__vars_435[(i_2)- 0]);
				if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
				{
					if (!eqStrings((*other).name, str)) goto LA12_;
					eqsink___vars_795(&(*u), other);
					if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
					other = 0;
					eqdestroy___vars_789(&other);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					eqdestroy___system_2592((&str));
					goto BeforeRet_;
				}
				LA12_: ;
				{
					if (!(((NI) 8) <= ((NI) (i_2)))) goto LA16_;
					goto LA8;
				}
				LA16_: ;
				i_2 += ((NI) 1);
			}
		} LA8: ;
		{
			LA7_:;
		}
		{
			oldNimErrFin7_ = *nimErr_; *nimErr_ = NIM_FALSE;
			eqdestroy___vars_789(&other);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			*nimErr_ = oldNimErrFin7_;
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	eqcopy___vars_792(&(*u), unitMono__vars_427);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		eqdestroy___system_2592((&str));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NimStringV2, uncompress__OOZOOZOOZOnimbleZpkgsZzippy4548O57O55Zzippy_131)(NimStringV2 src, tyEnum_CompressedDataFormat__hW3Jjtknic3hfPFuiaDRPw dataFormat) {
	NimStringV2 result;
	NimStringV2 T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	T1_.len = 0; T1_.p = NIM_NIL;
	{
		if (!(((NI) 0) < src.len)) goto LA4_;
		result = uncompress__OOZOOZOOZOnimbleZpkgsZzippy4548O57O55Zzippy_93(((void*) ((&src.p->data[((NI) 0)]))), src.len, dataFormat);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA2_;
	LA4_: ;
	{
		result = uncompress__OOZOOZOOZOnimbleZpkgsZzippy4548O57O55Zzippy_93(NIM_NIL, ((NI) 0), dataFormat);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	LA2_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL, isObj)(TNimTypeV2* obj, NCSTRING subclass) {
	NIM_BOOL result;
	NCSTRING T1_;
	result = (NIM_BOOL)0;
	T1_ = (NCSTRING)0;
	T1_ = strstr((*obj).name, subclass);
	result = !((((void*) (T1_)) == NIM_NIL));
	return result;
}
static N_INLINE(Exception*, nimBorrowCurrentException)(void) {
	Exception* result;
	result = NIM_NIL;
	result = currException__system_3145;
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__system_1709)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src) {
	{
		if (!(((NI) 0) < src.len)) goto LA3_;
		copyMem__system_1709(((void*) ((&(*(*dest).p).data[(*dest).len]))), ((void*) ((&(*src.p).data[((NI) 0)]))), ((NI) ((NI)(src.len + ((NI) 1)))));
		(*dest).len += src.len;
	}
	LA3_: ;
}
static N_INLINE(NimStringV2, getCurrentExceptionMsg__system_5952)(void) {
	NimStringV2 result;
	NimStringV2 T1_;
{	result.len = 0; result.p = NIM_NIL;
	T1_.len = 0; T1_.p = NIM_NIL;
	{
		if (!(currException__system_3145 == ((Exception*) NIM_NIL))) goto LA4_;
		result = TM__aJ9cAU2XHKgQoKe80UA7djg_13;
	}
	goto LA2_;
	LA4_: ;
	{
		eqcopy___system_2595((&result), (*currException__system_3145).message);
	}
	LA2_: ;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, popCurrentException)(void) {
	eqcopy___system_3188(&currException__system_3145, (*currException__system_3145).up);
}
N_LIB_PRIVATE N_NIMCALL(void, loadGame__saveio_374)(void) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NIM_BOOL T3_;
		NimStringV2 colontmpD_;
		NimStringV2 colontmpD__2;
		NimStringV2 T8_;
		NimStringV2 T9_;
		tyObject_SaveState__JG21xxTUaJxQnXwaK3dMWw T10_;
		T3_ = (NIM_BOOL)0;
		T3_ = nosfileExists(dataFile__saveio_8);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
		T8_.len = 0; T8_.p = NIM_NIL;
		T8_ = readFile__systemZio_491(dataFile__saveio_8);
		if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
		colontmpD_ = T8_;
		T9_.len = 0; T9_.p = NIM_NIL;
		T9_ = uncompress__OOZOOZOOZOnimbleZpkgsZzippy4548O57O55Zzippy_131(colontmpD_, ((tyEnum_CompressedDataFormat__hW3Jjtknic3hfPFuiaDRPw) 3));
		if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
		colontmpD__2 = T9_;
		nimZeroMem((void*)(&T10_), sizeof(tyObject_SaveState__JG21xxTUaJxQnXwaK3dMWw));
		fromJson__saveio_375(colontmpD__2, (&T10_));
		if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
		eqsink___vars_600((&save__vars_400), (&T10_));
		if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
		echoBinSafe(TM__aJ9cAU2XHKgQoKe80UA7djg_8, 1);
		{
			LA7_:;
		}
		{
			eqdestroy___system_2592((&colontmpD__2));
			eqdestroy___system_2592((&colontmpD_));
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
		if (NIM_UNLIKELY(*nimErr_)) {
			LA6_:;
			if (isObj(nimBorrowCurrentException()->Sup.m_type, "|jsony.jsony.JsonError|ValueError|CatchableError|Exception|RootObj|")) {
				NimStringV2 fmtRes;
				NimStringV2 colontmpD__3;
				tyArray__nHXaesL0DJZHyVS07ARPRA T17_;
				*nimErr_ = NIM_FALSE;
				fmtRes.len = 0; fmtRes.p = NIM_NIL;
				colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
				fmtRes = rawNewString(((NI) 61));
				prepareAdd((&fmtRes), 25);
appendString((&fmtRes), TM__aJ9cAU2XHKgQoKe80UA7djg_11);
				colontmpD__3 = getCurrentExceptionMsg__system_5952();
				formatValue__pureZstrformat_160((&fmtRes), colontmpD__3, TM__aJ9cAU2XHKgQoKe80UA7djg_14);
				if (NIM_UNLIKELY(*nimErr_)) goto LA16_;
				T17_[0] = fmtRes;
				echoBinSafe(T17_, 1);
				{
					LA16_:;
				}
				{
					eqdestroy___system_2592((&colontmpD__3));
					eqdestroy___system_2592((&fmtRes));
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA14_;
				popCurrentException();
				LA14_:;
			}
			else 			if (isObj(nimBorrowCurrentException()->Sup.m_type, "|zippy.common.ZippyError|ValueError|CatchableError|Exception|RootObj|")) {
				NimStringV2 fmtRes_2;
				NimStringV2 colontmpD__4;
				tyArray__nHXaesL0DJZHyVS07ARPRA T23_;
				*nimErr_ = NIM_FALSE;
				fmtRes_2.len = 0; fmtRes_2.p = NIM_NIL;
				colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
				fmtRes_2 = rawNewString(((NI) 61));
				prepareAdd((&fmtRes_2), 25);
appendString((&fmtRes_2), TM__aJ9cAU2XHKgQoKe80UA7djg_16);
				colontmpD__4 = getCurrentExceptionMsg__system_5952();
				formatValue__pureZstrformat_160((&fmtRes_2), colontmpD__4, TM__aJ9cAU2XHKgQoKe80UA7djg_17);
				if (NIM_UNLIKELY(*nimErr_)) goto LA22_;
				T23_[0] = fmtRes_2;
				echoBinSafe(T23_, 1);
				{
					LA22_:;
				}
				{
					eqdestroy___system_2592((&colontmpD__4));
					eqdestroy___system_2592((&fmtRes_2));
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA20_;
				popCurrentException();
				LA20_:;
			}
			else 			if (isObj(nimBorrowCurrentException()->Sup.m_type, "|IOError|CatchableError|Exception|RootObj|")) {
				NimStringV2 fmtRes_3;
				NimStringV2 colontmpD__5;
				tyArray__nHXaesL0DJZHyVS07ARPRA T29_;
				*nimErr_ = NIM_FALSE;
				fmtRes_3.len = 0; fmtRes_3.p = NIM_NIL;
				colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
				fmtRes_3 = rawNewString(((NI) 69));
				prepareAdd((&fmtRes_3), 33);
appendString((&fmtRes_3), TM__aJ9cAU2XHKgQoKe80UA7djg_19);
				colontmpD__5 = getCurrentExceptionMsg__system_5952();
				formatValue__pureZstrformat_160((&fmtRes_3), colontmpD__5, TM__aJ9cAU2XHKgQoKe80UA7djg_20);
				if (NIM_UNLIKELY(*nimErr_)) goto LA28_;
				T29_[0] = fmtRes_3;
				echoBinSafe(T29_, 1);
				{
					LA28_:;
				}
				{
					eqdestroy___system_2592((&colontmpD__5));
					eqdestroy___system_2592((&fmtRes_3));
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA26_;
				popCurrentException();
				LA26_:;
			}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	LA4_: ;
	}BeforeRet_: ;
}
static N_INLINE(void, nimAddCharV1)(NimStringV2* s, NIM_CHAR c) {
	prepareAdd(s, ((NI) 1));
	(*(*s).p).data[(*s).len] = c;
	(*(*s).p).data[(NI)((*s).len + ((NI) 1))] = 0;
	(*s).len += ((NI) 1);
}
N_LIB_PRIVATE N_NIMCALL(void, dumpHook__saveio_40)(NimStringV2* s, tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ* u) {
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	NimStringV2 T1_;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	nimAddCharV1((&(*s)), 34);
	T1_.len = 0; T1_.p = NIM_NIL;
	{
		if (!(u == ((tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ*) NIM_NIL))) goto LA4_;
		colontmpD_ = TM__aJ9cAU2XHKgQoKe80UA7djg_21;
		T1_ = colontmpD_;
	}
	goto LA2_;
	LA4_: ;
	{
		eqcopy___system_2595((&colontmpD__2), (*u).name);
		T1_ = colontmpD__2;
	}
	LA2_: ;
	prepareAdd((&(*s)), T1_.len + 0);
appendString((&(*s)), T1_);
	nimAddCharV1((&(*s)), 34);
	eqdestroy___system_2592((&colontmpD__2));
	eqdestroy___system_2592((&colontmpD_));
}
static N_INLINE(NimStringV2, compress__OOZOOZOOZOnimbleZpkgsZzippy4548O57O55Zzippy_77)(NimStringV2 src, NI level, tyEnum_CompressedDataFormat__hW3Jjtknic3hfPFuiaDRPw dataFormat) {
	NimStringV2 result;
	NimStringV2 T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	T1_.len = 0; T1_.p = NIM_NIL;
	{
		if (!(((NI) 0) < src.len)) goto LA4_;
		result = compress__OOZOOZOOZOnimbleZpkgsZzippy4548O57O55Zzippy_7(((void*) ((&src.p->data[((NI) 0)]))), src.len, level, dataFormat);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA2_;
	LA4_: ;
	{
		result = compress__OOZOOZOOZOnimbleZpkgsZzippy4548O57O55Zzippy_7(NIM_NIL, ((NI) 0), level, dataFormat);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	LA2_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, saveGame__saveio_47)(void) {
	NimStringV2 data;
	NimStringV2 comp;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	data.len = 0; data.p = NIM_NIL;
	comp.len = 0; comp.p = NIM_NIL;
	data = toJson__saveio_48((&save__vars_400));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	comp = compress__OOZOOZOOZOnimbleZpkgsZzippy4548O57O55Zzippy_77(data, ((NI) -1), ((tyEnum_CompressedDataFormat__hW3Jjtknic3hfPFuiaDRPw) 3));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	noscreateDir(dataDir__saveio_7);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	writeFile__systemZio_496(dataFile__saveio_8, comp);
	if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
	if (NIM_UNLIKELY(*nimErr_)) {
		LA2_:;
		if (isObj(nimBorrowCurrentException()->Sup.m_type, "|IOError|CatchableError|Exception|RootObj|")) {
			NimStringV2 fmtRes;
			NimStringV2 colontmpD_;
			tyArray__nHXaesL0DJZHyVS07ARPRA T7_;
			*nimErr_ = NIM_FALSE;
			fmtRes.len = 0; fmtRes.p = NIM_NIL;
			colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
			fmtRes = rawNewString(((NI) 70));
			prepareAdd((&fmtRes), 34);
appendString((&fmtRes), TM__aJ9cAU2XHKgQoKe80UA7djg_23);
			colontmpD_ = getCurrentExceptionMsg__system_5952();
			formatValue__pureZstrformat_160((&fmtRes), colontmpD_, TM__aJ9cAU2XHKgQoKe80UA7djg_24);
			if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
			T7_[0] = fmtRes;
			echoBinSafe(T7_, 1);
			{
				LA6_:;
			}
			{
				eqdestroy___system_2592((&colontmpD_));
				eqdestroy___system_2592((&fmtRes));
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
			popCurrentException();
			LA4_:;
		}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		eqdestroy___system_2592((&comp));
		eqdestroy___system_2592((&data));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, animdustry_saveioInit000)(void) {
{
	NimStringV2 T1_;
NIM_BOOL* nimErr_;
nimErr_ = nimErrorFlag();
	dataDir__saveio_7 = TM__aJ9cAU2XHKgQoKe80UA7djg_3;
	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = slash___pureZos_131(dataDir__saveio_7, TM__aJ9cAU2XHKgQoKe80UA7djg_5);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	dataFile__saveio_8 = T1_;
	BeforeRet_: ;
}
}

