/* Generated by Nim Compiler v1.6.4 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyTuple__6ziS9c652xoISTZPdl3I9aeg tyTuple__6ziS9c652xoISTZPdl3I9aeg;
typedef struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ;
struct tyTuple__6ziS9c652xoISTZPdl3I9aeg {
NF32 Field0;
NI Field1;
};
struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ {
NI Field0;
NI Field1;
};
static N_INLINE(void, stareq___OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZdistance_29)(NF32* x, NF32 y);
static N_INLINE(void, stareq___pureZtimes_2624)(NI* x, NI y);
N_LIB_PRIVATE N_NIMCALL(NI, nextPowerOfTwo__pureZmath_177)(NI x) {
	NI result;
	result = (NI)0;
	result = (NI)(x - ((NI) 1));
	result = (NI)(result | (NI)((NI64)(result) >> (NU64)(((NI) 32))));
	result = (NI)(result | (NI)((NI64)(result) >> (NU64)(((NI) 16))));
	result = (NI)(result | (NI)((NI64)(result) >> (NU64)(((NI) 8))));
	result = (NI)(result | (NI)((NI64)(result) >> (NU64)(((NI) 4))));
	result = (NI)(result | (NI)((NI64)(result) >> (NU64)(((NI) 2))));
	result = (NI)(result | (NI)((NI64)(result) >> (NU64)(((NI) 1))));
	result += (NI)(((NI) 1) + (x <= ((NI) 0)));
	return result;
}
static N_INLINE(void, stareq___OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZdistance_29)(NF32* x, NF32 y) {
	(*x) = ((NF32)((*x)) * (NF32)(y));
}
N_LIB_PRIVATE N_NIMCALL(NF32, roof___OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZdistance_22)(NF32 x, NI y) {
	NF32 result;
	result = (NF32)0;
	switch (y) {
	case ((NI) 0):
	{
		result = 1.0f;
	}
	break;
	case ((NI) 1):
	{
		result = x;
	}
	break;
	case ((NI) 2):
	{
		result = ((NF32)(x) * (NF32)(x));
	}
	break;
	case ((NI) 3):
	{
		result = ((NF32)(((NF32)(x) * (NF32)(x))) * (NF32)(x));
	}
	break;
	default:
	{
		tyTuple__6ziS9c652xoISTZPdl3I9aeg T6_;
		NF32 x_2;
		NI y_2;
		T6_.Field0 = x;
		T6_.Field1 = y;
		x_2 = T6_.Field0;
		y_2 = T6_.Field1;
		result = 1.0f;
		{
			while (1) {
				{
					if (!!(((NI)(((NI) (y_2)) & ((NI) 1)) == ((NI) 0)))) goto LA11_;
					stareq___OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZdistance_29((&result), x_2);
				}
				LA11_: ;
				y_2 = ((NI) ((NI)((NI64)(((NI) (y_2))) >> (NU64)(((NI) 1)))));
				{
					if (!(((NI) (y_2)) == ((NI) 0))) goto LA15_;
					goto LA7;
				}
				LA15_: ;
				stareq___OOZOOZOOZOnimbleZpkgsZchroma4548O50O53ZchromaZdistance_29((&x_2), x_2);
			}
		} LA7: ;
	}
	break;
	}
	return result;
}
static N_INLINE(void, stareq___pureZtimes_2624)(NI* x, NI y) {
	(*x) = (NI)((*x) * y);
}
N_LIB_PRIVATE N_NIMCALL(NI, roof___pureZtimes_2617)(NI x, NI y) {
	NI result;
	result = (NI)0;
	switch (y) {
	case ((NI) 0):
	{
		result = ((NI) 1);
	}
	break;
	case ((NI) 1):
	{
		result = x;
	}
	break;
	case ((NI) 2):
	{
		result = (NI)(x * x);
	}
	break;
	case ((NI) 3):
	{
		result = (NI)((NI)(x * x) * x);
	}
	break;
	default:
	{
		tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ T6_;
		NI x_2;
		NI y_2;
		T6_.Field0 = x;
		T6_.Field1 = y;
		x_2 = T6_.Field0;
		y_2 = T6_.Field1;
		result = ((NI) 1);
		{
			while (1) {
				{
					if (!!(((NI)(((NI) (y_2)) & ((NI) 1)) == ((NI) 0)))) goto LA11_;
					stareq___pureZtimes_2624((&result), x_2);
				}
				LA11_: ;
				y_2 = ((NI) ((NI)((NI64)(((NI) (y_2))) >> (NU64)(((NI) 1)))));
				{
					if (!(((NI) (y_2)) == ((NI) 0))) goto LA15_;
					goto LA7;
				}
				LA15_: ;
				stareq___pureZtimes_2624((&x_2), x_2);
			}
		} LA7: ;
	}
	break;
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, euclDiv__main_4334)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = (NI)(x / y);
	{
		if (!((NI)(x % y) < ((NI) 0))) goto LA3_;
		{
			if (!(((NI) 0) < y)) goto LA7_;
			result -= ((NI) 1);
		}
		goto LA5_;
		LA7_: ;
		{
			result += ((NI) 1);
		}
		LA5_: ;
	}
	LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, euclMod__main_4348)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = (NI)(x % y);
	{
		if (!(result < ((NI) 0))) goto LA3_;
		result += (y > 0? (y) : -(y));
	}
	LA3_: ;
	return result;
}
