/* Generated by Nim Compiler v1.6.4 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tySequence__1G1c1pZ4AzoGz9awoII9a5sA tySequence__1G1c1pZ4AzoGz9awoII9a5sA;
typedef struct tySequence__1G1c1pZ4AzoGz9awoII9a5sA_Content tySequence__1G1c1pZ4AzoGz9awoII9a5sA_Content;
typedef struct tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyTuple__BUNQL5x2cKJaBSzOn5pwkg tyTuple__BUNQL5x2cKJaBSzOn5pwkg;
typedef struct tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w;
typedef struct tyObject_Table__OxRqfkudSQS6aNVHuUx9bSg tyObject_Table__OxRqfkudSQS6aNVHuUx9bSg;
typedef struct tySequence__v87TdQ9b9cLCVESucM9cmtTyg tySequence__v87TdQ9b9cLCVESucM9cmtTyg;
typedef struct tySequence__v87TdQ9b9cLCVESucM9cmtTyg_Content tySequence__v87TdQ9b9cLCVESucM9cmtTyg_Content;
typedef struct tyTuple__DtYz89aEFgC8CcjjapPJ8Rg tyTuple__DtYz89aEFgC8CcjjapPJ8Rg;
typedef struct tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ;
struct tySequence__1G1c1pZ4AzoGz9awoII9a5sA {
  NI len; tySequence__1G1c1pZ4AzoGz9awoII9a5sA_Content* p;
};
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyTuple__BUNQL5x2cKJaBSzOn5pwkg unit, NI moves, void* ClE_0);
void* ClE_0;
} tyProc__ojNDjFK5r5ivRd8Rxp6ZuA;
typedef N_NIMCALL_PTR(void, tyProc__cMnJRgMxnPy9bYjqfhi18yg) (tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ* unit, tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w pos);
struct tySequence__v87TdQ9b9cLCVESucM9cmtTyg {
  NI len; tySequence__v87TdQ9b9cLCVESucM9cmtTyg_Content* p;
};
struct tyObject_Table__OxRqfkudSQS6aNVHuUx9bSg {
tySequence__v87TdQ9b9cLCVESucM9cmtTyg data;
NI counter;
};
struct tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ {
NimStringV2 name;
NimStringV2 title;
NimStringV2 subtitle;
NimStringV2 ability;
NI abilityReload;
tyProc__ojNDjFK5r5ivRd8Rxp6ZuA abilityProc;
tyProc__cMnJRgMxnPy9bYjqfhi18yg draw;
tyObject_Table__OxRqfkudSQS6aNVHuUx9bSg textures;
NIM_BOOL unmoving;
NIM_BOOL unobtainable;
NIM_BOOL wasOver;
NF32 fade;
NF32 jump;
NIM_BOOL jumping;
NF32 clickTime;
};


#ifndef tySequence__1G1c1pZ4AzoGz9awoII9a5sA_Content_PP
#define tySequence__1G1c1pZ4AzoGz9awoII9a5sA_Content_PP
struct tySequence__1G1c1pZ4AzoGz9awoII9a5sA_Content { NI cap; tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ* data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__1G1c1pZ4AzoGz9awoII9a5sA_Content_PP
#define tySequence__1G1c1pZ4AzoGz9awoII9a5sA_Content_PP
struct tySequence__1G1c1pZ4AzoGz9awoII9a5sA_Content { NI cap; tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ* data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__1G1c1pZ4AzoGz9awoII9a5sA_Content_PP
#define tySequence__1G1c1pZ4AzoGz9awoII9a5sA_Content_PP
struct tySequence__1G1c1pZ4AzoGz9awoII9a5sA_Content { NI cap; tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ* data[SEQ_DECL_SIZE];};
#endif

      struct tyTuple__BUNQL5x2cKJaBSzOn5pwkg {
NI32 Field0;
NI32 Field1;
};
struct tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w {
NF32 x;
NF32 y;
};
struct tyTuple__DtYz89aEFgC8CcjjapPJ8Rg {
NI Field0;
NimStringV2 Field1;
tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ* Field2;
};


#ifndef tySequence__v87TdQ9b9cLCVESucM9cmtTyg_Content_PP
#define tySequence__v87TdQ9b9cLCVESucM9cmtTyg_Content_PP
struct tySequence__v87TdQ9b9cLCVESucM9cmtTyg_Content { NI cap; tyTuple__DtYz89aEFgC8CcjjapPJ8Rg data[SEQ_DECL_SIZE];};
#endif

      N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap, NI elemSize, NI elemAlign);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___vars_792)(tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ** dest, tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ* src);
N_LIB_PRIVATE N_NIMCALL(void, add__saveio_508)(tySequence__1G1c1pZ4AzoGz9awoII9a5sA* x, tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ* value);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___vars_789)(tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ** dest);
static N_INLINE(NIM_BOOL, contains__main_4655)(tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ** a, NI aLen_0, tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ* item);
static N_INLINE(NI, find__main_4660)(tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ** a, NI aLen_0, tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ* item);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
extern NIM_BOOL nimInErrorMode__system_3443;
static N_INLINE(NI, find__main_4660)(tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ** a, NI aLen_0, tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ* item) {
	NI result;
{	result = (NI)0;
	result = ((NI) 0);
	{
		tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ** i;
		NI i_2;
		i = (tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ**)0;
		i_2 = ((NI) 0);
		{
			while (1) {
				if (!(i_2 < aLen_0)) goto LA3;
				i = &a[i_2];
				{
					if (!((*i) == item)) goto LA6_;
					goto BeforeRet_;
				}
				LA6_: ;
				result += ((NI) 1);
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
	result = ((NI) -1);
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL, contains__main_4655)(tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ** a, NI aLen_0, tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ* item) {
	NIM_BOOL result;
	NI T1_;
{	result = (NIM_BOOL)0;
	T1_ = (NI)0;
	T1_ = find__main_4660(a, aLen_0, item);
	result = (((NI) 0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__system_3443);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__1G1c1pZ4AzoGz9awoII9a5sA, deduplicate__main_4610)(tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ** s, NI sLen_0, NIM_BOOL isSorted) {
	tySequence__1G1c1pZ4AzoGz9awoII9a5sA result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	result.len = 0; result.p = (tySequence__1G1c1pZ4AzoGz9awoII9a5sA_Content*) newSeqPayload(0, sizeof(tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ*), NIM_ALIGNOF(tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ*));
	{
		if (!(((NI) 0) < sLen_0)) goto LA3_;
		{
			tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ* prev;
			tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ* colontmpD_;
			if (!isSorted) goto LA7_;
			prev = NIM_NIL;
			colontmpD_ = NIM_NIL;
			eqcopy___vars_792(&prev, s[((NI) 0)]);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			colontmpD_ = 0;
			eqcopy___vars_792(&colontmpD_, prev);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			add__saveio_508((&result), colontmpD_);
			{
				NI i;
				NI colontmp_;
				NI res;
				i = (NI)0;
				colontmp_ = (NI)0;
				colontmp_ = (sLen_0-1);
				res = ((NI) 1);
				{
					while (1) {
						if (!(res <= colontmp_)) goto LA11;
						i = res;
						{
							tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ* colontmpD__2;
							if (!!((s[i] == prev))) goto LA14_;
							colontmpD__2 = NIM_NIL;
							eqcopy___vars_792(&prev, s[i]);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							colontmpD__2 = 0;
							eqcopy___vars_792(&colontmpD__2, prev);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							add__saveio_508((&result), colontmpD__2);
						}
						LA14_: ;
						res += ((NI) 1);
					} LA11: ;
				}
			}
			eqdestroy___vars_789(&prev);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		goto LA5_;
		LA7_: ;
		{
			{
				tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ** itm;
				NI i_2;
				itm = (tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ**)0;
				i_2 = ((NI) 0);
				{
					while (1) {
						if (!(i_2 < sLen_0)) goto LA19;
						itm = &s[i_2];
						{
							NIM_BOOL T22_;
							tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ* colontmpD__3;
							T22_ = (NIM_BOOL)0;
							T22_ = contains__main_4655(result.p->data, result.len, (*itm));
							if (!!(T22_)) goto LA23_;
							colontmpD__3 = NIM_NIL;
							colontmpD__3 = 0;
							eqcopy___vars_792(&colontmpD__3, (*itm));
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							add__saveio_508((&result), colontmpD__3);
						}
						LA23_: ;
						i_2 += ((NI) 1);
					} LA19: ;
				}
			}
		}
		LA5_: ;
	}
	LA3_: ;
	}BeforeRet_: ;
	return result;
}
