/* Generated by Nim Compiler v1.6.4 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_Rand__liBKmwv1H6v7oYBhDFHa6A tyObject_Rand__liBKmwv1H6v7oYBhDFHa6A;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_HSlice__o9ajL6M2gGnsTbnGkrCsx9aA tyObject_HSlice__o9ajL6M2gGnsTbnGkrCsx9aA;
typedef struct tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA;
typedef struct tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ;
typedef struct tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA;
typedef struct tyObject_HSlice__vOYTm9cLQaRc5TUw9atOyHnA tyObject_HSlice__vOYTm9cLQaRc5TUw9atOyHnA;
typedef struct tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ;
typedef struct tyTuple__BUNQL5x2cKJaBSzOn5pwkg tyTuple__BUNQL5x2cKJaBSzOn5pwkg;
typedef struct tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w;
typedef struct tyObject_Table__OxRqfkudSQS6aNVHuUx9bSg tyObject_Table__OxRqfkudSQS6aNVHuUx9bSg;
typedef struct tySequence__v87TdQ9b9cLCVESucM9cmtTyg tySequence__v87TdQ9b9cLCVESucM9cmtTyg;
typedef struct tySequence__v87TdQ9b9cLCVESucM9cmtTyg_Content tySequence__v87TdQ9b9cLCVESucM9cmtTyg_Content;
typedef struct tyTuple__DtYz89aEFgC8CcjjapPJ8Rg tyTuple__DtYz89aEFgC8CcjjapPJ8Rg;
struct tyObject_Rand__liBKmwv1H6v7oYBhDFHa6A {
NU64 a0;
NU64 a1;
};
typedef NU8 tyArray__qtqsWM5aXmcpMIVmvq3kAA[16];
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
typedef NU64 tyArray__NzKR9bw29cLPrd712Xt6Liiw[2];
struct tyObject_HSlice__o9ajL6M2gGnsTbnGkrCsx9aA {
NF32 a;
NF32 b;
};
struct tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA {
tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ* texture;
NF32 u;
NF32 v;
NF32 u2;
NF32 v2;
};
struct tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA {
NI a;
NI b;
};
struct tyObject_HSlice__vOYTm9cLQaRc5TUw9atOyHnA {
NF a;
NF b;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyTuple__BUNQL5x2cKJaBSzOn5pwkg unit, NI moves, void* ClE_0);
void* ClE_0;
} tyProc__ojNDjFK5r5ivRd8Rxp6ZuA;
typedef N_NIMCALL_PTR(void, tyProc__cMnJRgMxnPy9bYjqfhi18yg) (tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ* unit, tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w pos);
struct tySequence__v87TdQ9b9cLCVESucM9cmtTyg {
  NI len; tySequence__v87TdQ9b9cLCVESucM9cmtTyg_Content* p;
};
struct tyObject_Table__OxRqfkudSQS6aNVHuUx9bSg {
tySequence__v87TdQ9b9cLCVESucM9cmtTyg data;
NI counter;
};
struct tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ {
NimStringV2 name;
NimStringV2 title;
NimStringV2 subtitle;
NimStringV2 ability;
NI abilityReload;
tyProc__ojNDjFK5r5ivRd8Rxp6ZuA abilityProc;
tyProc__cMnJRgMxnPy9bYjqfhi18yg draw;
tyObject_Table__OxRqfkudSQS6aNVHuUx9bSg textures;
NIM_BOOL unmoving;
NIM_BOOL unobtainable;
NIM_BOOL wasOver;
NF32 fade;
NF32 jump;
NIM_BOOL jumping;
NF32 clickTime;
};
struct tyTuple__BUNQL5x2cKJaBSzOn5pwkg {
NI32 Field0;
NI32 Field1;
};
struct tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w {
NF32 x;
NF32 y;
};
struct tyTuple__DtYz89aEFgC8CcjjapPJ8Rg {
NI Field0;
NimStringV2 Field1;
tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ* Field2;
};


#ifndef tySequence__v87TdQ9b9cLCVESucM9cmtTyg_Content_PP
#define tySequence__v87TdQ9b9cLCVESucM9cmtTyg_Content_PP
struct tySequence__v87TdQ9b9cLCVESucM9cmtTyg_Content { NI cap; tyTuple__DtYz89aEFgC8CcjjapPJ8Rg data[SEQ_DECL_SIZE];};
#endif

      N_LIB_PRIVATE N_NIMCALL(tyObject_Rand__liBKmwv1H6v7oYBhDFHa6A, initRand__pureZrandom_245)(void);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(NIM_BOOL, isValid__pureZrandom_24)(tyObject_Rand__liBKmwv1H6v7oYBhDFHa6A r);
N_LIB_PRIVATE N_NIMCALL(tyObject_Rand__liBKmwv1H6v7oYBhDFHa6A, getRandomState__pureZrandom_247)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, urandom__stdZsysrand_50)(NU8* dest, NI destLen_0);
static N_INLINE(void, copyMem__system_1709)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(void, quit__system_6020)(NimStringV2 errormsg, NI errorcode);
N_LIB_PRIVATE N_NIMCALL(void, skipRandomNumbers__pureZrandom_53)(tyObject_Rand__liBKmwv1H6v7oYBhDFHa6A* s);
N_LIB_PRIVATE N_NIMCALL(NU64, next__pureZrandom_44)(tyObject_Rand__liBKmwv1H6v7oYBhDFHa6A* r);
N_LIB_PRIVATE N_NIMCALL(NU64, rotl__pureZrandom_32)(NU64 x, NU64 k);
N_LIB_PRIVATE N_NIMCALL(NF, rand__pureZrandom_118)(tyObject_Rand__liBKmwv1H6v7oYBhDFHa6A* r, NF max);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___OOZfauZsrcZfauZpatch_28)(tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA* dest, tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA src);
N_LIB_PRIVATE N_NIMCALL(NI, rand__patterns_1490)(tyObject_Rand__liBKmwv1H6v7oYBhDFHa6A* r, tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA x);
N_LIB_PRIVATE N_NIMCALL(NU64, rand__pureZrandom_96)(tyObject_Rand__liBKmwv1H6v7oYBhDFHa6A* r, NU64 max);
static N_INLINE(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA, dotdot___pureZunicode_914)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(NF, rand__OOZfauZsrcZfauZfmath_198)(tyObject_Rand__liBKmwv1H6v7oYBhDFHa6A* r, tyObject_HSlice__vOYTm9cLQaRc5TUw9atOyHnA x);
N_LIB_PRIVATE N_NIMCALL(NI, rand__main_4265)(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA x);
N_LIB_PRIVATE NIM_CONST tyObject_Rand__liBKmwv1H6v7oYBhDFHa6A DefaultRandSeed__pureZrandom_13 = {7616934476015405061ULL, 15122295919272093642ULL}
;
static const struct {
  NI cap; NIM_CHAR data[81+1];
} TM__AIKkgex03Z1j45JceakCTA_2 = { 81 | NIM_STRLIT_FLAG, "Failed to initializes baseState in random module as sysrand.urandom doesn\'t work." };
static const NimStringV2 TM__AIKkgex03Z1j45JceakCTA_3 = {81, (NimStrPayload*)&TM__AIKkgex03Z1j45JceakCTA_2};
N_LIB_PRIVATE NIM_CONST tyArray__NzKR9bw29cLPrd712Xt6Liiw helper__pureZrandom_55 = {13739361407582206667ULL,
15594563132006766882ULL}
;
N_LIB_PRIVATE tyObject_Rand__liBKmwv1H6v7oYBhDFHa6A state__pureZrandom_14;
N_LIB_PRIVATE tyObject_Rand__liBKmwv1H6v7oYBhDFHa6A baseState__pureZrandom_244;
extern NIM_BOOL nimInErrorMode__system_3443;
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__system_3443);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL, isValid__pureZrandom_24)(tyObject_Rand__liBKmwv1H6v7oYBhDFHa6A r) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	result = (NIM_BOOL)0;
	T1_ = (NIM_BOOL)0;
	T1_ = (r.a0 == 0ULL);
	if (!(T1_)) goto LA2_;
	T1_ = (r.a1 == 0ULL);
	LA2_: ;
	result = !(T1_);
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__system_1709)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Rand__liBKmwv1H6v7oYBhDFHa6A, getRandomState__pureZrandom_247)(void) {
	tyObject_Rand__liBKmwv1H6v7oYBhDFHa6A result;
	tyArray__qtqsWM5aXmcpMIVmvq3kAA urand;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Rand__liBKmwv1H6v7oYBhDFHa6A));
	nimZeroMem((void*)urand, sizeof(tyArray__qtqsWM5aXmcpMIVmvq3kAA));
	{
		NI i;
		NI res;
		i = (NI)0;
		res = ((NI) 0);
		{
			while (1) {
				if (!(res <= ((NI) 7))) goto LA3;
				i = res;
				{
					NIM_BOOL T6_;
					T6_ = (NIM_BOOL)0;
					T6_ = urandom__stdZsysrand_50(urand, 16);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					if (!T6_) goto LA7_;
					copyMem__system_1709(((void*) ((&result))), ((void*) ((&urand[(((NI) 0))- 0]))), ((NI) 16));
					{
						NIM_BOOL T11_;
						T11_ = (NIM_BOOL)0;
						T11_ = isValid__pureZrandom_24(result);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						if (!T11_) goto LA12_;
						goto LA1;
					}
					LA12_: ;
				}
				LA7_: ;
				res += ((NI) 1);
			} LA3: ;
		}
	} LA1: ;
	{
		NIM_BOOL T16_;
		T16_ = (NIM_BOOL)0;
		T16_ = isValid__pureZrandom_24(result);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!!(T16_)) goto LA17_;
		quit__system_6020(TM__AIKkgex03Z1j45JceakCTA_3, ((NI) 1));
	}
	LA17_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU64, rotl__pureZrandom_32)(NU64 x, NU64 k) {
	NU64 result;
	result = (NU64)0;
	result = (NU64)((NU64)((NU64)(x) << (NU64)(k)) | (NU64)((NU64)(x) >> (NU64)((NU64)((NU64)(64ULL) - (NU64)(k)))));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU64, next__pureZrandom_44)(tyObject_Rand__liBKmwv1H6v7oYBhDFHa6A* r) {
	NU64 result;
	NU64 s0;
	NU64 s1;
	NU64 T1_;
	NU64 T2_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NU64)0;
	s0 = (*r).a0;
	s1 = (*r).a1;
	result = (NU64)((NU64)(s0) + (NU64)(s1));
	s1 = (NU64)(s1 ^ s0);
	T1_ = (NU64)0;
	T1_ = rotl__pureZrandom_32(s0, 55ULL);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*r).a0 = (NU64)((NU64)(T1_ ^ s1) ^ (NU64)((NU64)(s1) << (NU64)(((NI) 14))));
	T2_ = (NU64)0;
	T2_ = rotl__pureZrandom_32(s1, 36ULL);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*r).a1 = T2_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, skipRandomNumbers__pureZrandom_53)(tyObject_Rand__liBKmwv1H6v7oYBhDFHa6A* s) {
	NU64 s0;
	NU64 s1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	s0 = 0ULL;
	s1 = 0ULL;
	{
		NI i;
		NI res;
		i = (NI)0;
		res = ((NI) 0);
		{
			while (1) {
				if (!(res <= ((NI) 1))) goto LA3;
				i = res;
				{
					NI b;
					NI i_2;
					b = (NI)0;
					i_2 = ((NI) 0);
					{
						while (1) {
							NU64 T11_;
							if (!(i_2 < ((NI) 64))) goto LA6;
							b = i_2;
							{
								if (!!(((NU64)(helper__pureZrandom_55[(i)- 0] & (NU64)((NU64)(1ULL) << (NU64)(((NU64) (b))))) == 0ULL))) goto LA9_;
								s0 = (NU64)(s0 ^ (*s).a0);
								s1 = (NU64)(s1 ^ (*s).a1);
							}
							LA9_: ;
							T11_ = (NU64)0;
							T11_ = next__pureZrandom_44(s);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							(void)(T11_);
							i_2 += ((NI) 1);
						} LA6: ;
					}
				}
				res += ((NI) 1);
			} LA3: ;
		}
	}
	(*s).a0 = s0;
	(*s).a1 = s1;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Rand__liBKmwv1H6v7oYBhDFHa6A, initRand__pureZrandom_245)(void) {
	tyObject_Rand__liBKmwv1H6v7oYBhDFHa6A result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Rand__liBKmwv1H6v7oYBhDFHa6A));
	{
		NIM_BOOL T3_;
		tyObject_Rand__liBKmwv1H6v7oYBhDFHa6A T6_;
		T3_ = (NIM_BOOL)0;
		T3_ = isValid__pureZrandom_24(baseState__pureZrandom_244);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!!(T3_)) goto LA4_;
		nimZeroMem((void*)(&T6_), sizeof(tyObject_Rand__liBKmwv1H6v7oYBhDFHa6A));
		T6_ = getRandomState__pureZrandom_247();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		baseState__pureZrandom_244 = T6_;
	}
	LA4_: ;
	result = baseState__pureZrandom_244;
	skipRandomNumbers__pureZrandom_53((&baseState__pureZrandom_244));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, randomize__pureZrandom_277)(void) {
	tyObject_Rand__liBKmwv1H6v7oYBhDFHa6A T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&T1_), sizeof(tyObject_Rand__liBKmwv1H6v7oYBhDFHa6A));
	T1_ = initRand__pureZrandom_245();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	state__pureZrandom_14 = T1_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Rand__liBKmwv1H6v7oYBhDFHa6A, initRand__pureZrandom_216)(NI64 seed) {
	tyObject_Rand__liBKmwv1H6v7oYBhDFHa6A result;
	NI64 colontmpD_;
	NI64 colontmpD__2;
	NI64 seed_2;
	NU64 T6_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Rand__liBKmwv1H6v7oYBhDFHa6A));
	colontmpD_ = (NI64)0;
	colontmpD__2 = (NI64)0;
	{
		if (!!((seed == IL64(0)))) goto LA3_;
		colontmpD_ = seed;
		seed_2 = colontmpD_;
	}
	goto LA1_;
	LA3_: ;
	{
		colontmpD__2 = IL64(2147483647);
		seed_2 = colontmpD__2;
	}
	LA1_: ;
	result.a0 = ((NU64) ((NI64)((NI64)(seed_2) >> (NU64)(((NI) 16)))));
	result.a1 = ((NU64) ((NI64)(seed_2 & IL64(65535))));
	skipRandomNumbers__pureZrandom_53((&result));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T6_ = (NU64)0;
	T6_ = next__pureZrandom_44((&result));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(void)(T6_);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NF, rand__pureZrandom_118)(tyObject_Rand__liBKmwv1H6v7oYBhDFHa6A* r, NF max) {
	NF result;
	NU64 x;
	NU64 u;
	union { NU64 source; NF dest; } LOC1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NF)0;
	x = next__pureZrandom_44(r);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	u = (NU64)(4607182418800017408ULL | (NU64)((NU64)(x) >> (NU64)(12ULL)));
	LOC1.source = u;
	result = ((NF)(((NF)(LOC1.dest) - (NF)(1.0))) * (NF)(((NF) (max))));
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NF32, rand__OOZfauZsrcZfauZfmath_380)(tyObject_Rand__liBKmwv1H6v7oYBhDFHa6A* r, tyObject_HSlice__o9ajL6M2gGnsTbnGkrCsx9aA x) {
	NF32 result;
	NF T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NF32)0;
	T1_ = (NF)0;
	T1_ = rand__pureZrandom_118(r, ((NF) (((NF32)(x.b) - (NF32)(x.a)))));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = ((NF32) (((NF)(T1_) + (NF)(((NF) (x.a))))));
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU64, rand__pureZrandom_96)(tyObject_Rand__liBKmwv1H6v7oYBhDFHa6A* r, NU64 max) {
	NU64 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NU64)0;
	{
		if (!(max == 0ULL)) goto LA3_;
		goto BeforeRet_;
	}
	goto LA1_;
	LA3_: ;
	{
		NU64 max_2;
		max_2 = max;
		{
			if (!(max_2 == 18446744073709551615ULL)) goto LA8_;
			result = next__pureZrandom_44(r);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			goto BeforeRet_;
		}
		LA8_: ;
		{
			while (1) {
				NU64 x;
				x = next__pureZrandom_44(r);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				{
					if (!((NU64)(x) <= (NU64)((NU64)((NU64)(18446744073709551615ULL) - (NU64)((NU64)((NU64)(18446744073709551615ULL) % (NU64)(max_2))))))) goto LA14_;
					result = (NU64)((NU64)(x) % (NU64)((NU64)((NU64)(max_2) + (NU64)(1ULL))));
					goto BeforeRet_;
				}
				LA14_: ;
			}
		}
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, rand__patterns_1490)(tyObject_Rand__liBKmwv1H6v7oYBhDFHa6A* r, tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA x) {
	NI result;
	NU64 T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	T1_ = (NU64)0;
	T1_ = rand__pureZrandom_96(r, (NU64)((NU64)(((NU64) (x.b))) - (NU64)(((NU64) (x.a)))));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = ((NI) ((NU64)((NU64)(T1_) + (NU64)(((NU64) (x.a))))));
	}BeforeRet_: ;
	return result;
}
static N_INLINE(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA, dotdot___pureZunicode_914)(NI a, NI b) {
	tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA result;
	nimZeroMem((void*)(&result), sizeof(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA));
	nimZeroMem((void*)(&result), sizeof(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA));
	result.a = a;
	result.b = b;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, sample__patterns_1600)(tyObject_Rand__liBKmwv1H6v7oYBhDFHa6A* r, tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA* a, NI aLen_0, tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA* Result) {
	tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA T1_;
	NI T2_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA));
	T1_ = dotdot___pureZunicode_914(((NI) 0), (aLen_0-1));
	T2_ = (NI)0;
	T2_ = rand__patterns_1490(r, T1_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqcopy___OOZfauZsrcZfauZpatch_28(Result, a[T2_]);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NF, rand__OOZfauZsrcZfauZfmath_198)(tyObject_Rand__liBKmwv1H6v7oYBhDFHa6A* r, tyObject_HSlice__vOYTm9cLQaRc5TUw9atOyHnA x) {
	NF result;
	NF T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NF)0;
	T1_ = (NF)0;
	T1_ = rand__pureZrandom_118(r, ((NF) (((NF)(x.b) - (NF)(x.a)))));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = ((NF)(T1_) + (NF)(x.a));
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NF, rand__OOZfauZsrcZfauZfmath_190)(tyObject_HSlice__vOYTm9cLQaRc5TUw9atOyHnA x) {
	NF result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NF)0;
	result = rand__OOZfauZsrcZfauZfmath_198((&state__pureZrandom_14), x);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, rand__main_4265)(tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA x) {
	NI result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	result = rand__patterns_1490((&state__pureZrandom_14), x);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ**, sample__main_4246)(tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ** a, NI aLen_0) {
	tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ** result;
	tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA T1_;
	NI T2_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (tyObject_UnitcolonObjectType___SsZeRd6gcBu7cG15jQxSuQ**)0;
	T1_ = dotdot___pureZunicode_914(((NI) 0), (aLen_0-1));
	T2_ = (NI)0;
	T2_ = rand__main_4265(T1_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = &a[T2_];
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, stdlib_randomInit000)(void) {
{
	state__pureZrandom_14 = DefaultRandSeed__pureZrandom_13;
}
}

