/* Generated by Nim Compiler v1.6.4 */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tySequence__rOUGT12uxe0NLayHTZQq8g tySequence__rOUGT12uxe0NLayHTZQq8g;
typedef struct tySequence__rOUGT12uxe0NLayHTZQq8g_Content tySequence__rOUGT12uxe0NLayHTZQq8g_Content;
typedef struct tyTuple__BUNQL5x2cKJaBSzOn5pwkg tyTuple__BUNQL5x2cKJaBSzOn5pwkg;
typedef struct tyTuple__g4r3XfQCKzdcXRKjmYJQBw tyTuple__g4r3XfQCKzdcXRKjmYJQBw;
typedef struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A;
typedef struct tyObject_ComponentcolonObjectType___SwyartCHmIIoZLZWUHBvew tyObject_ComponentcolonObjectType___SwyartCHmIIoZLZWUHBvew;
struct tySequence__rOUGT12uxe0NLayHTZQq8g {
  NI len; tySequence__rOUGT12uxe0NLayHTZQq8g_Content* p;
};
typedef struct {
N_NIMCALL_PTR(tySequence__rOUGT12uxe0NLayHTZQq8g, ClP_0) (tyTuple__BUNQL5x2cKJaBSzOn5pwkg entity, tyTuple__g4r3XfQCKzdcXRKjmYJQBw component, void* ClE_0);
void* ClE_0;
} tyProc__fGO239csCkwyeR04c78nCjQ;
struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A {
NI rc;
};


#ifndef tySequence__rOUGT12uxe0NLayHTZQq8g_Content_PP
#define tySequence__rOUGT12uxe0NLayHTZQq8g_Content_PP
struct tySequence__rOUGT12uxe0NLayHTZQq8g_Content { NI cap; tyObject_ComponentcolonObjectType___SwyartCHmIIoZLZWUHBvew* data[SEQ_DECL_SIZE];};
#endif

      struct tyTuple__BUNQL5x2cKJaBSzOn5pwkg {
NI32 Field0;
NI32 Field1;
};
struct tyTuple__g4r3XfQCKzdcXRKjmYJQBw {
NU16 Field0;
NI32 Field1;
NI32 Field2;
};


#ifndef tySequence__rOUGT12uxe0NLayHTZQq8g_Content_PP
#define tySequence__rOUGT12uxe0NLayHTZQq8g_Content_PP
struct tySequence__rOUGT12uxe0NLayHTZQq8g_Content { NI cap; tyObject_ComponentcolonObjectType___SwyartCHmIIoZLZWUHBvew* data[SEQ_DECL_SIZE];};
#endif

      static N_INLINE(void, nimIncRef)(void* p);
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p, NI align);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq___OOZOOZOOZOnimbleZpkgsZpolymorph4548O51O48ZpolymorphZsharedtypes_460)(NU16 c1, NU16 c2) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = (((NI) (c1)) == ((NI) (c2)));
	return result;
}
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU32)(((NU) (x))) - (NU32)(((NU) (y))))));
	return result;
}
static N_INLINE(void, nimIncRef)(void* p) {
	NI T1_;
	T1_ = (NI)0;
	T1_ = minuspercent___system_716(((NI) (ptrdiff_t) (p)), ((NI) 4));
	(*((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T1_))).rc += ((NI) 8);
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* cell;
		NI T5_;
		if (!!((p == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_716(((NI) (ptrdiff_t) (p)), ((NI) 4));
		cell = ((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T5_));
		{
			if (!((NI)((*cell).rc & ((NI) -8)) == ((NI) 0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
		LA8_: ;
		{
			(*cell).rc -= ((NI) 8);
		}
		LA6_: ;
	}
	LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___main_52490)(tyProc__fGO239csCkwyeR04c78nCjQ* dest, tyProc__fGO239csCkwyeR04c78nCjQ src) {
	{
		if (!src.ClE_0) goto LA3_;
		nimIncRef(src.ClE_0);
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLast((*dest).ClE_0);
		if (!T7_) goto LA8_;
		nimDestroyAndDispose((*dest).ClE_0);
	}
	LA8_: ;
	(*dest).ClE_0 = src.ClE_0;
	(*dest).ClP_0 = src.ClP_0;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZOnimbleZpkgsZpolymorph4548O51O48ZpolymorphZcomponents_69)(tySequence__rOUGT12uxe0NLayHTZQq8g* dest) {
	NI colontmp_;
	colontmp_ = ((NI) 0);
	{
		while (1) {
			NI T3_;
			T3_ = (*dest).len;
			if (!(colontmp_ < T3_)) goto LA2;
			{
				NIM_BOOL T6_;
				T6_ = (NIM_BOOL)0;
				T6_ = nimDecRefIsLast((*dest).p->data[colontmp_]);
				if (!T6_) goto LA7_;
				nimDestroyAndDispose((*dest).p->data[colontmp_]);
			}
			LA7_: ;
			colontmp_ += ((NI) 1);
		} LA2: ;
	}
	if ((*dest).p && !((*dest).p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc((*dest).p, NIM_ALIGNOF(tyObject_ComponentcolonObjectType___SwyartCHmIIoZLZWUHBvew*));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___main_52487)(tyProc__fGO239csCkwyeR04c78nCjQ* dest) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest).ClE_0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest).ClE_0);
	}
	LA4_: ;
}
