/* Generated by Nim Compiler v1.6.4 */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_AtlascolonObjectType___5kuY28uezWLPxjw6Jjpi9ag tyObject_AtlascolonObjectType___5kuY28uezWLPxjw6Jjpi9ag;
typedef struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A;
typedef struct tySequence__AB1TndMAvXQUoC2xJSQVEg tySequence__AB1TndMAvXQUoC2xJSQVEg;
typedef struct tySequence__AB1TndMAvXQUoC2xJSQVEg_Content tySequence__AB1TndMAvXQUoC2xJSQVEg_Content;
typedef struct tyObject_Table__hLzAgCdI52IxQ1lJQGTKVA tyObject_Table__hLzAgCdI52IxQ1lJQGTKVA;
typedef struct tyObject_Table__c36tEmVxDEcCLwl9bZ5VYmw tyObject_Table__c36tEmVxDEcCLwl9bZ5VYmw;
typedef struct tySequence__NV14do9aURznn03ltuah5VA tySequence__NV14do9aURznn03ltuah5VA;
typedef struct tySequence__NV14do9aURznn03ltuah5VA_Content tySequence__NV14do9aURznn03ltuah5VA_Content;
typedef struct tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ;
typedef struct tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA;
typedef struct tyObject_Patch9__YtojNSDnK7j9aYZRNVXTN7g tyObject_Patch9__YtojNSDnK7j9aYZRNVXTN7g;
typedef struct tyObject_StringStreamObj__Olau5FPRehZBBEB77FHnfw tyObject_StringStreamObj__Olau5FPRehZBBEB77FHnfw;
typedef struct tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA;
typedef struct tyTuple__Ir1duhFQeN2Qu2wazAMb5w tyTuple__Ir1duhFQeN2Qu2wazAMb5w;
typedef struct tyTuple__HervhaKiavhm9bIe9bPCAHbA tyTuple__HervhaKiavhm9bIe9bPCAHbA;
struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A {
NI rc;
};
struct tySequence__AB1TndMAvXQUoC2xJSQVEg {
  NI len; tySequence__AB1TndMAvXQUoC2xJSQVEg_Content* p;
};
struct tyObject_Table__hLzAgCdI52IxQ1lJQGTKVA {
tySequence__AB1TndMAvXQUoC2xJSQVEg data;
NI counter;
};
struct tySequence__NV14do9aURznn03ltuah5VA {
  NI len; tySequence__NV14do9aURznn03ltuah5VA_Content* p;
};
struct tyObject_Table__c36tEmVxDEcCLwl9bZ5VYmw {
tySequence__NV14do9aURznn03ltuah5VA data;
NI counter;
};
struct tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA {
tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ* texture;
NF32 u;
NF32 v;
NF32 u2;
NF32 v2;
};
typedef tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA tyArray__cYLMonStdqJ9bQDnj3JlASw[9];
struct tyObject_Patch9__YtojNSDnK7j9aYZRNVXTN7g {
tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ* texture;
NI left;
NI right;
NI top;
NI bot;
NI width;
NI height;
tyArray__cYLMonStdqJ9bQDnj3JlASw patches;
};
struct tyObject_AtlascolonObjectType___5kuY28uezWLPxjw6Jjpi9ag {
tyObject_Table__hLzAgCdI52IxQ1lJQGTKVA patches;
tyObject_Table__c36tEmVxDEcCLwl9bZ5VYmw patches9;
tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ* texture;
tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA error;
tyObject_Patch9__YtojNSDnK7j9aYZRNVXTN7g error9;
};
struct TNimTypeV2 {
void* destructor;
NI size;
NI align;
NCSTRING name;
void* traceImpl;
void* typeInfoV1;
NI flags;
};
struct RootObj {
TNimTypeV2* m_type;
};
typedef N_NIMCALL_PTR(void, tyProc__JQrsH08b4uPTH9cyFPlVOZg) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__9bmhFrLahRsL2hltfRDVtlQ) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s);
typedef N_NIMCALL_PTR(void, tyProc__3svSoGIUJIsHkaBL7q4DAQ) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s, NI pos);
typedef N_NIMCALL_PTR(NI, tyProc__xflqkf2D1uVClg70czEDHA) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s);
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
typedef N_NIMCALL_PTR(NI, tyProc__c9c0f59ak4YGQ6neEym8LPKw) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s, NimStringV2* buffer, tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA slice);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__7jFfqMk9ajToCz6Hv9atCA4A) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s, NimStringV2* line);
typedef N_NIMCALL_PTR(NI, tyProc__2VVzVL9bOnKhj1eZKkf9cEuA) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s, void* buffer, NI bufLen);
typedef N_NIMCALL_PTR(void, tyProc__ki6p1QyfOkJLQJ9aw5NI0AQ) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s, void* buffer, NI bufLen);
struct tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ {
  RootObj Sup;
tyProc__JQrsH08b4uPTH9cyFPlVOZg closeImpl;
tyProc__9bmhFrLahRsL2hltfRDVtlQ atEndImpl;
tyProc__3svSoGIUJIsHkaBL7q4DAQ setPositionImpl;
tyProc__xflqkf2D1uVClg70czEDHA getPositionImpl;
tyProc__c9c0f59ak4YGQ6neEym8LPKw readDataStrImpl;
tyProc__7jFfqMk9ajToCz6Hv9atCA4A readLineImpl;
tyProc__2VVzVL9bOnKhj1eZKkf9cEuA readDataImpl;
tyProc__2VVzVL9bOnKhj1eZKkf9cEuA peekDataImpl;
tyProc__ki6p1QyfOkJLQJ9aw5NI0AQ writeDataImpl;
tyProc__JQrsH08b4uPTH9cyFPlVOZg flushImpl;
};
struct tyObject_StringStreamObj__Olau5FPRehZBBEB77FHnfw {
  tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ Sup;
NimStringV2 data;
NI pos;
};
struct tyTuple__Ir1duhFQeN2Qu2wazAMb5w {
NI Field0;
NimStringV2 Field1;
tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA Field2;
};


#ifndef tySequence__AB1TndMAvXQUoC2xJSQVEg_Content_PP
#define tySequence__AB1TndMAvXQUoC2xJSQVEg_Content_PP
struct tySequence__AB1TndMAvXQUoC2xJSQVEg_Content { NI cap; tyTuple__Ir1duhFQeN2Qu2wazAMb5w data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__AB1TndMAvXQUoC2xJSQVEg_Content_PP
#define tySequence__AB1TndMAvXQUoC2xJSQVEg_Content_PP
struct tySequence__AB1TndMAvXQUoC2xJSQVEg_Content { NI cap; tyTuple__Ir1duhFQeN2Qu2wazAMb5w data[SEQ_DECL_SIZE];};
#endif

      struct tyTuple__HervhaKiavhm9bIe9bPCAHbA {
NI Field0;
NimStringV2 Field1;
tyObject_Patch9__YtojNSDnK7j9aYZRNVXTN7g Field2;
};


#ifndef tySequence__NV14do9aURznn03ltuah5VA_Content_PP
#define tySequence__NV14do9aURznn03ltuah5VA_Content_PP
struct tySequence__NV14do9aURznn03ltuah5VA_Content { NI cap; tyTuple__HervhaKiavhm9bIe9bPCAHbA data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__NV14do9aURznn03ltuah5VA_Content_PP
#define tySequence__NV14do9aURznn03ltuah5VA_Content_PP
struct tySequence__NV14do9aURznn03ltuah5VA_Content { NI cap; tyTuple__HervhaKiavhm9bIe9bPCAHbA data[SEQ_DECL_SIZE];};
#endif

      struct tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA {
NI a;
NI b;
};
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p);
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZfauZsrcZfauZglobals_268)(tyObject_AtlascolonObjectType___5kuY28uezWLPxjw6Jjpi9ag* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZfauZsrcZfauZatlas_361)(tySequence__AB1TndMAvXQUoC2xJSQVEg* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZfauZsrcZfauZglobals_277)(tySequence__NV14do9aURznn03ltuah5VA* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZfauZsrcZfauZtexture_28)(tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ* texture);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p, NI alignment);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size, NI alignment);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZfauZsrcZfauZtexture_119)(tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ** dest, tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ* src);
N_LIB_PRIVATE N_NIMCALL(tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ*, loadTexture__OOZfauZsrcZcore_874)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_StringStreamObj__Olau5FPRehZBBEB77FHnfw*, assetStaticStream__OOZfauZsrcZcore_878)(void);
N_LIB_PRIVATE N_NIMCALL(NI32, readInt32__pureZstreams_321)(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(NI16, readInt16__pureZstreams_286)(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, readStr__pureZstreams_548)(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s, NI length);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, readBool__pureZstreams_232)(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s);
N_LIB_PRIVATE N_NIMCALL(void, newPatch__OOZfauZsrcZfauZpatch_18)(tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ* texture, NI x, NI y, NI width, NI height, tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA* Result);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___OOZfauZsrcZcore_937)(tyObject_Table__c36tEmVxDEcCLwl9bZ5VYmw* t, NimStringV2 key, tyObject_Patch9__YtojNSDnK7j9aYZRNVXTN7g* val);
N_LIB_PRIVATE N_NIMCALL(void, newPatch9__OOZfauZsrcZfauZpatch_107)(tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA patch, NI left, NI right, NI top, NI bot, tyObject_Patch9__YtojNSDnK7j9aYZRNVXTN7g* Result);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___OOZfauZsrcZcore_1158)(tyObject_Table__hLzAgCdI52IxQ1lJQGTKVA* t, NimStringV2 key, tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA val);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZfauZsrcZfauZpatch_25)(tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_2592)(NimStringV2* dest);
N_LIB_PRIVATE N_NIMCALL(void, close__pureZstreams_57)(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___OOZfauZsrcZfauZpatch_28)(tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA* dest, tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA src);
N_LIB_PRIVATE N_NIMCALL(tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA*, X5BX5D___OOZfauZsrcZcore_1392)(tyObject_Table__hLzAgCdI52IxQ1lJQGTKVA* t, NimStringV2 key);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZfauZsrcZfauZpatch_143)(tyObject_Patch9__YtojNSDnK7j9aYZRNVXTN7g* dest, tyObject_Patch9__YtojNSDnK7j9aYZRNVXTN7g* src);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZstreams_623)(tyObject_StringStreamObj__Olau5FPRehZBBEB77FHnfw** dest);
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__s19aBQpheVam0UGIob9bLB5A_2 = { 5 | NIM_STRLIT_FLAG, "error" };
static const NimStringV2 TM__s19aBQpheVam0UGIob9bLB5A_3 = {5, (NimStrPayload*)&TM__s19aBQpheVam0UGIob9bLB5A_2};
static const NimStringV2 TM__s19aBQpheVam0UGIob9bLB5A_4 = {5, (NimStrPayload*)&TM__s19aBQpheVam0UGIob9bLB5A_2};
extern NIM_BOOL nimInErrorMode__system_3443;
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU32)(((NU) (x))) - (NU32)(((NU) (y))))));
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* cell;
		NI T5_;
		if (!!((p == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_716(((NI) (ptrdiff_t) (p)), ((NI) 4));
		cell = ((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T5_));
		{
			if (!((NI)((*cell).rc & ((NI) -8)) == ((NI) 0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
		LA8_: ;
		{
			(*cell).rc -= ((NI) 8);
		}
		LA6_: ;
	}
	LA3_: ;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__system_3443);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZfauZsrcZfauZglobals_268)(tyObject_AtlascolonObjectType___5kuY28uezWLPxjw6Jjpi9ag* dest) {
	NI colontmp_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___OOZfauZsrcZfauZatlas_361((&(*dest).patches.data));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___OOZfauZsrcZfauZglobals_277((&(*dest).patches9.data));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest).texture);
		if (!T3_) goto LA4_;
		eqdestroy___OOZfauZsrcZfauZtexture_28((*dest).texture);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimRawDispose((*dest).texture, ((NI) 4));
	}
	LA4_: ;
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLast((*dest).error.texture);
		if (!T8_) goto LA9_;
		eqdestroy___OOZfauZsrcZfauZtexture_28((*dest).error.texture);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimRawDispose((*dest).error.texture, ((NI) 4));
	}
	LA9_: ;
	{
		NIM_BOOL T13_;
		T13_ = (NIM_BOOL)0;
		T13_ = nimDecRefIsLast((*dest).error9.texture);
		if (!T13_) goto LA14_;
		eqdestroy___OOZfauZsrcZfauZtexture_28((*dest).error9.texture);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimRawDispose((*dest).error9.texture, ((NI) 4));
	}
	LA14_: ;
	colontmp_ = ((NI) 0);
	{
		while (1) {
			if (!(colontmp_ < ((NI) 9))) goto LA17;
			{
				NIM_BOOL T20_;
				T20_ = (NIM_BOOL)0;
				T20_ = nimDecRefIsLast((*dest).error9.patches[(colontmp_)- 0].texture);
				if (!T20_) goto LA21_;
				eqdestroy___OOZfauZsrcZfauZtexture_28((*dest).error9.patches[(colontmp_)- 0].texture);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimRawDispose((*dest).error9.patches[(colontmp_)- 0].texture, ((NI) 4));
			}
			LA21_: ;
			colontmp_ += ((NI) 1);
		} LA17: ;
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZfauZsrcZcore_1482)(tyObject_AtlascolonObjectType___5kuY28uezWLPxjw6Jjpi9ag** dest, tyObject_AtlascolonObjectType___5kuY28uezWLPxjw6Jjpi9ag* src) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest));
		if (!T3_) goto LA4_;
		eqdestroy___OOZfauZsrcZfauZglobals_268((*dest));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimRawDispose((*dest), ((NI) 4));
	}
	LA4_: ;
	(*dest) = src;
	}BeforeRet_: ;
}
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_AtlascolonObjectType___5kuY28uezWLPxjw6Jjpi9ag*, loadAtlas__OOZfauZsrcZcore_870)(void) {
	tyObject_AtlascolonObjectType___5kuY28uezWLPxjw6Jjpi9ag* result;
	tyObject_StringStreamObj__Olau5FPRehZBBEB77FHnfw* stream;
	tyObject_AtlascolonObjectType___5kuY28uezWLPxjw6Jjpi9ag* T2_;
	tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ* T3_;
	NI32 amount;
NIM_BOOL oldNimErrFin7_;
	tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA* T16_;
	tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA* T17_;
	tyObject_Patch9__YtojNSDnK7j9aYZRNVXTN7g T18_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	stream = NIM_NIL;
	T2_ = NIM_NIL;
	T2_ = (tyObject_AtlascolonObjectType___5kuY28uezWLPxjw6Jjpi9ag*) nimNewObj(sizeof(tyObject_AtlascolonObjectType___5kuY28uezWLPxjw6Jjpi9ag), NIM_ALIGNOF(tyObject_AtlascolonObjectType___5kuY28uezWLPxjw6Jjpi9ag));
	result = T2_;
	T3_ = NIM_NIL;
	T3_ = loadTexture__OOZfauZsrcZcore_874();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	eqsink___OOZfauZsrcZfauZtexture_119(&(*result).texture, T3_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	stream = assetStaticStream__OOZfauZsrcZcore_878();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	amount = readInt32__pureZstreams_321(&stream->Sup);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		NI32 i;
		NI32 res;
		i = (NI32)0;
		res = ((NI32) 0);
		{
			while (1) {
				NimStringV2 name;
				tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA patch;
				NI16 nameLen;
				NI16 x;
				NI16 y;
				NI16 width;
				NI16 height;
				NIM_BOOL hasSplit;
				tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA T8_;
				tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA blitTmp;
				if (!(res < amount)) goto LA6;
				name.len = 0; name.p = NIM_NIL;
				nimZeroMem((void*)(&patch), sizeof(tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA));
				i = res;
				nameLen = readInt16__pureZstreams_286(&stream->Sup);
				if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
				name = readStr__pureZstreams_548(&stream->Sup, ((NI) (nameLen)));
				if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
				x = readInt16__pureZstreams_286(&stream->Sup);
				if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
				y = readInt16__pureZstreams_286(&stream->Sup);
				if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
				width = readInt16__pureZstreams_286(&stream->Sup);
				if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
				height = readInt16__pureZstreams_286(&stream->Sup);
				if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
				hasSplit = readBool__pureZstreams_232(&stream->Sup);
				if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
				nimZeroMem((void*)(&T8_), sizeof(tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA));
				newPatch__OOZfauZsrcZfauZpatch_18((*result).texture, ((NI) (x)), ((NI) (y)), ((NI) (width)), ((NI) (height)), (&T8_));
				patch = T8_;
				if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
				{
					NI16 left;
					NI16 right;
					NI16 top;
					NI16 bot;
					tyObject_Patch9__YtojNSDnK7j9aYZRNVXTN7g T13_;
					if (!hasSplit) goto LA11_;
					left = readInt16__pureZstreams_286(&stream->Sup);
					if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
					right = readInt16__pureZstreams_286(&stream->Sup);
					if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
					top = readInt16__pureZstreams_286(&stream->Sup);
					if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
					bot = readInt16__pureZstreams_286(&stream->Sup);
					if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
					nimZeroMem((void*)(&T13_), sizeof(tyObject_Patch9__YtojNSDnK7j9aYZRNVXTN7g));
					newPatch9__OOZfauZsrcZfauZpatch_107(patch, ((NI) (left)), ((NI) (right)), ((NI) (top)), ((NI) (bot)), (&T13_));
					if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
					X5BX5Deq___OOZfauZsrcZcore_937((&(*result).patches9), name, (&T13_));
					if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
				}
				LA11_: ;
				nimZeroMem((void*)(&blitTmp), sizeof(tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA));
				blitTmp = patch;
				nimZeroMem((void*)(&patch), sizeof(tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA));
				X5BX5Deq___OOZfauZsrcZcore_1158((&(*result).patches), name, blitTmp);
				if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
				res += ((NI) 1);
				{
					LA7_:;
				}
				{
					oldNimErrFin7_ = *nimErr_; *nimErr_ = NIM_FALSE;
					eqdestroy___OOZfauZsrcZfauZpatch_25((&patch));
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					eqdestroy___system_2592((&name));
					*nimErr_ = oldNimErrFin7_;
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			} LA6: ;
		}
	}
	close__pureZstreams_57(&stream->Sup);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T16_ = (tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA*)0;
	T16_ = X5BX5D___OOZfauZsrcZcore_1392((&(*result).patches), TM__s19aBQpheVam0UGIob9bLB5A_3);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	eqcopy___OOZfauZsrcZfauZpatch_28((&(*result).error), (*T16_));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T17_ = (tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA*)0;
	T17_ = X5BX5D___OOZfauZsrcZcore_1392((&(*result).patches), TM__s19aBQpheVam0UGIob9bLB5A_4);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimZeroMem((void*)(&T18_), sizeof(tyObject_Patch9__YtojNSDnK7j9aYZRNVXTN7g));
	newPatch9__OOZfauZsrcZfauZpatch_107((*T17_), ((NI) 0), ((NI) 0), ((NI) 0), ((NI) 0), (&T18_));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	eqsink___OOZfauZsrcZfauZpatch_143((&(*result).error9), (&T18_));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		eqdestroy___pureZstreams_623(&stream);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
