/* Generated by Nim Compiler v1.6.4 */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ;
typedef struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw;
typedef struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content tySequence__uB9b75OUPRENsBAu4AnoePA_Content;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
struct TNimTypeV2 {
void* destructor;
NI size;
NI align;
NCSTRING name;
void* traceImpl;
void* typeInfoV1;
NI flags;
};
struct RootObj {
TNimTypeV2* m_type;
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  NI len; tySequence__uB9b75OUPRENsBAu4AnoePA_Content* p;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringV2 message;
tySequence__uB9b75OUPRENsBAu4AnoePA trace;
Exception* up;
};
struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA {
  Exception Sup;
};
struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw {
  tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA Sup;
};
struct tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ {
  tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw Sup;
};
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};


#ifndef tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
#define tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content { NI cap; tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};
#endif

      N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size, NI alignment);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
N_LIB_PRIVATE N_NIMCALL(NI, nextZeroByte__OOZOOZOOZOnimbleZpkgsZzippy4548O57O55ZzippyZgzip_40)(NU8* src, NI len, NI start);
static N_INLINE(NU32, read32__OOZOOZOOZOnimbleZpkgsZzippy4548O57O55ZzippyZinternal_390)(NU8* src, NI ip);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s, NI newLen);
N_LIB_PRIVATE N_NIMCALL(void, inflate__OOZOOZOOZOnimbleZpkgsZzippy4548O57O55ZzippyZinflate_509)(NimStringV2* dst, NU8* src, NI len, NI pos);
static N_INLINE(NU32, crc32__OOZOOZOOZOnimbleZpkgsZzippy4548O57O55ZzippyZcrc_138)(NimStringV2 src);
N_LIB_PRIVATE N_NIMCALL(NU32, crc32__OOZOOZOOZOnimbleZpkgsZzippy4548O57O55ZzippyZcrc_77)(void* src, NI len);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
extern TNimTypeV2 NTIv2__j2RCbV49bRvsx6N3fCdjSIQ_;
static const struct {
  NI cap; NIM_CHAR data[36+1];
} TM__KI6FnpwETfuweeL0NXTMMg_2 = { 36 | NIM_STRLIT_FLAG, "Invalid buffer, unable to uncompress" };
static const NimStringV2 TM__KI6FnpwETfuweeL0NXTMMg_3 = {36, (NimStrPayload*)&TM__KI6FnpwETfuweeL0NXTMMg_2};
static const struct {
  NI cap; NIM_CHAR data[39+1];
} TM__KI6FnpwETfuweeL0NXTMMg_4 = { 39 | NIM_STRLIT_FLAG, "Failed gzip identification values check" };
static const NimStringV2 TM__KI6FnpwETfuweeL0NXTMMg_5 = {39, (NimStrPayload*)&TM__KI6FnpwETfuweeL0NXTMMg_4};
static const struct {
  NI cap; NIM_CHAR data[30+1];
} TM__KI6FnpwETfuweeL0NXTMMg_6 = { 30 | NIM_STRLIT_FLAG, "Unsupported compression method" };
static const NimStringV2 TM__KI6FnpwETfuweeL0NXTMMg_7 = {30, (NimStrPayload*)&TM__KI6FnpwETfuweeL0NXTMMg_6};
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__KI6FnpwETfuweeL0NXTMMg_8 = { 22 | NIM_STRLIT_FLAG, "Reserved flag bits set" };
static const NimStringV2 TM__KI6FnpwETfuweeL0NXTMMg_9 = {22, (NimStrPayload*)&TM__KI6FnpwETfuweeL0NXTMMg_8};
static const struct {
  NI cap; NIM_CHAR data[35+1];
} TM__KI6FnpwETfuweeL0NXTMMg_10 = { 35 | NIM_STRLIT_FLAG, "Currently unsupported flags are set" };
static const NimStringV2 TM__KI6FnpwETfuweeL0NXTMMg_11 = {35, (NimStrPayload*)&TM__KI6FnpwETfuweeL0NXTMMg_10};
static const NimStringV2 TM__KI6FnpwETfuweeL0NXTMMg_12 = {36, (NimStrPayload*)&TM__KI6FnpwETfuweeL0NXTMMg_2};
static const NimStringV2 TM__KI6FnpwETfuweeL0NXTMMg_13 = {36, (NimStrPayload*)&TM__KI6FnpwETfuweeL0NXTMMg_2};
static const NimStringV2 TM__KI6FnpwETfuweeL0NXTMMg_14 = {36, (NimStrPayload*)&TM__KI6FnpwETfuweeL0NXTMMg_2};
static const struct {
  NI cap; NIM_CHAR data[28+1];
} TM__KI6FnpwETfuweeL0NXTMMg_15 = { 28 | NIM_STRLIT_FLAG, "Checksum verification failed" };
static const NimStringV2 TM__KI6FnpwETfuweeL0NXTMMg_16 = {28, (NimStrPayload*)&TM__KI6FnpwETfuweeL0NXTMMg_15};
static const struct {
  NI cap; NIM_CHAR data[24+1];
} TM__KI6FnpwETfuweeL0NXTMMg_17 = { 24 | NIM_STRLIT_FLAG, "Size verification failed" };
static const NimStringV2 TM__KI6FnpwETfuweeL0NXTMMg_18 = {24, (NimStrPayload*)&TM__KI6FnpwETfuweeL0NXTMMg_17};
extern NIM_BOOL nimInErrorMode__system_3443;
N_LIB_PRIVATE N_NIMCALL(NI, nextZeroByte__OOZOOZOOZOnimbleZpkgsZzippy4548O57O55ZzippyZgzip_40)(NU8* src, NI len, NI start) {
	NI result;
	tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ* T8_;
{	result = (NI)0;
	{
		NI i;
		NI i_2;
		i = (NI)0;
		i_2 = start;
		{
			while (1) {
				if (!(i_2 < len)) goto LA3;
				i = i_2;
				{
					if (!(src[i] == ((NU8) 0))) goto LA6_;
					result = i;
					goto BeforeRet_;
				}
				LA6_: ;
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
	T8_ = NIM_NIL;
	T8_ = (tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ*) nimNewObj(sizeof(tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ), NIM_ALIGNOF(tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ));
	(*T8_).Sup.Sup.Sup.Sup.m_type = (&NTIv2__j2RCbV49bRvsx6N3fCdjSIQ_);
	(*T8_).Sup.Sup.Sup.name = "ZippyError";
	(*T8_).Sup.Sup.Sup.message = TM__KI6FnpwETfuweeL0NXTMMg_12;
	(*T8_).Sup.Sup.Sup.parent = ((Exception*) NIM_NIL);
	raiseExceptionEx((Exception*)T8_, "ZippyError", "nextZeroByte", "gzip.nim", 47);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NU32, read32__OOZOOZOOZOnimbleZpkgsZzippy4548O57O55ZzippyZinternal_390)(NU8* src, NI ip) {
	NU32 result;
	result = (NU32)0;
	result = (*((NU32*) ((&src[ip]))));
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__system_3443);
	return result;
}
static N_INLINE(NU32, crc32__OOZOOZOOZOnimbleZpkgsZzippy4548O57O55ZzippyZcrc_138)(NimStringV2 src) {
	NU32 result;
	NU32 colontmpD_;
	NU32 colontmpD__2;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NU32)0;
	colontmpD_ = (NU32)0;
	colontmpD__2 = (NU32)0;
	{
		if (!(((NI) 0) < src.len)) goto LA3_;
		colontmpD_ = crc32__OOZOOZOOZOnimbleZpkgsZzippy4548O57O55ZzippyZcrc_77(((void*) ((&src.p->data[((NI) 0)]))), src.len);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = colontmpD_;
	}
	goto LA1_;
	LA3_: ;
	{
		colontmpD__2 = crc32__OOZOOZOOZOnimbleZpkgsZzippy4548O57O55ZzippyZcrc_77(NIM_NIL, ((NI) 0));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = colontmpD__2;
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, uncompressGzip__OOZOOZOOZOnimbleZpkgsZzippy4548O57O55ZzippyZgzip_5)(NimStringV2* dst, NU8* src, NI len, NIM_BOOL trustSize) {
	NU8 id1;
	NU8 id2;
	NU8 cm;
	NU8 flg;
	NIM_BOOL fhcrc;
	NIM_BOOL fextra;
	NIM_BOOL fname;
	NIM_BOOL fcomment;
	NI pos;
	NU32 checksum;
	NU32 isize;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ* T5_;
		if (!(len < ((NI) 18))) goto LA3_;
		T5_ = NIM_NIL;
		T5_ = (tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ*) nimNewObj(sizeof(tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ), NIM_ALIGNOF(tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ));
		(*T5_).Sup.Sup.Sup.Sup.m_type = (&NTIv2__j2RCbV49bRvsx6N3fCdjSIQ_);
		(*T5_).Sup.Sup.Sup.name = "ZippyError";
		(*T5_).Sup.Sup.Sup.message = TM__KI6FnpwETfuweeL0NXTMMg_3;
		(*T5_).Sup.Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T5_, "ZippyError", "uncompressGzip", "gzip.nim", 11);
		goto BeforeRet_;
	}
	LA3_: ;
	id1 = src[((NI) 0)];
	id2 = src[((NI) 1)];
	cm = src[((NI) 2)];
	flg = src[((NI) 3)];
	{
		NIM_BOOL T8_;
		tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ* T12_;
		T8_ = (NIM_BOOL)0;
		T8_ = !((id1 == ((NU8) 31)));
		if (T8_) goto LA9_;
		T8_ = !((id2 == ((NU8) 139)));
		LA9_: ;
		if (!T8_) goto LA10_;
		T12_ = NIM_NIL;
		T12_ = (tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ*) nimNewObj(sizeof(tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ), NIM_ALIGNOF(tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ));
		(*T12_).Sup.Sup.Sup.Sup.m_type = (&NTIv2__j2RCbV49bRvsx6N3fCdjSIQ_);
		(*T12_).Sup.Sup.Sup.name = "ZippyError";
		(*T12_).Sup.Sup.Sup.message = TM__KI6FnpwETfuweeL0NXTMMg_5;
		(*T12_).Sup.Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T12_, "ZippyError", "uncompressGzip", "gzip.nim", 23);
		goto BeforeRet_;
	}
	LA10_: ;
	{
		tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ* T17_;
		if (!!((cm == ((NU8) 8)))) goto LA15_;
		T17_ = NIM_NIL;
		T17_ = (tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ*) nimNewObj(sizeof(tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ), NIM_ALIGNOF(tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ));
		(*T17_).Sup.Sup.Sup.Sup.m_type = (&NTIv2__j2RCbV49bRvsx6N3fCdjSIQ_);
		(*T17_).Sup.Sup.Sup.name = "ZippyError";
		(*T17_).Sup.Sup.Sup.message = TM__KI6FnpwETfuweeL0NXTMMg_7;
		(*T17_).Sup.Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T17_, "ZippyError", "uncompressGzip", "gzip.nim", 26);
		goto BeforeRet_;
	}
	LA15_: ;
	{
		tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ* T22_;
		if (!((NU8)(((NU8) 0)) < (NU8)((NU8)(flg & ((NU8) 224))))) goto LA20_;
		T22_ = NIM_NIL;
		T22_ = (tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ*) nimNewObj(sizeof(tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ), NIM_ALIGNOF(tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ));
		(*T22_).Sup.Sup.Sup.Sup.m_type = (&NTIv2__j2RCbV49bRvsx6N3fCdjSIQ_);
		(*T22_).Sup.Sup.Sup.name = "ZippyError";
		(*T22_).Sup.Sup.Sup.message = TM__KI6FnpwETfuweeL0NXTMMg_9;
		(*T22_).Sup.Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T22_, "ZippyError", "uncompressGzip", "gzip.nim", 29);
		goto BeforeRet_;
	}
	LA20_: ;
	fhcrc = !(((NU8)(flg & ((NU8) 2)) == ((NU8) 0)));
	fextra = !(((NU8)(flg & ((NU8) 4)) == ((NU8) 0)));
	fname = !(((NU8)(flg & ((NU8) 8)) == ((NU8) 0)));
	fcomment = !(((NU8)(flg & ((NU8) 16)) == ((NU8) 0)));
	pos = ((NI) 10);
	{
		tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ* T27_;
		if (!fextra) goto LA25_;
		T27_ = NIM_NIL;
		T27_ = (tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ*) nimNewObj(sizeof(tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ), NIM_ALIGNOF(tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ));
		(*T27_).Sup.Sup.Sup.Sup.m_type = (&NTIv2__j2RCbV49bRvsx6N3fCdjSIQ_);
		(*T27_).Sup.Sup.Sup.name = "ZippyError";
		(*T27_).Sup.Sup.Sup.message = TM__KI6FnpwETfuweeL0NXTMMg_11;
		(*T27_).Sup.Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T27_, "ZippyError", "uncompressGzip", "gzip.nim", 41);
		goto BeforeRet_;
	}
	LA25_: ;
	{
		NI T32_;
		if (!fname) goto LA30_;
		T32_ = (NI)0;
		T32_ = nextZeroByte__OOZOOZOOZOnimbleZpkgsZzippy4548O57O55ZzippyZgzip_40(src, len, pos);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		pos = (NI)(T32_ + ((NI) 1));
	}
	LA30_: ;
	{
		NI T37_;
		if (!fcomment) goto LA35_;
		T37_ = (NI)0;
		T37_ = nextZeroByte__OOZOOZOOZOnimbleZpkgsZzippy4548O57O55ZzippyZgzip_40(src, len, pos);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		pos = (NI)(T37_ + ((NI) 1));
	}
	LA35_: ;
	{
		if (!fhcrc) goto LA40_;
		{
			tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ* T46_;
			if (!(len <= (NI)(pos + ((NI) 2)))) goto LA44_;
			T46_ = NIM_NIL;
			T46_ = (tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ*) nimNewObj(sizeof(tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ), NIM_ALIGNOF(tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ));
			(*T46_).Sup.Sup.Sup.Sup.m_type = (&NTIv2__j2RCbV49bRvsx6N3fCdjSIQ_);
			(*T46_).Sup.Sup.Sup.name = "ZippyError";
			(*T46_).Sup.Sup.Sup.message = TM__KI6FnpwETfuweeL0NXTMMg_13;
			(*T46_).Sup.Sup.Sup.parent = ((Exception*) NIM_NIL);
			raiseExceptionEx((Exception*)T46_, "ZippyError", "uncompressGzip", "gzip.nim", 57);
			goto BeforeRet_;
		}
		LA44_: ;
		pos += ((NI) 2);
	}
	LA40_: ;
	{
		tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ* T51_;
		if (!(len <= (NI)(pos + ((NI) 8)))) goto LA49_;
		T51_ = NIM_NIL;
		T51_ = (tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ*) nimNewObj(sizeof(tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ), NIM_ALIGNOF(tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ));
		(*T51_).Sup.Sup.Sup.Sup.m_type = (&NTIv2__j2RCbV49bRvsx6N3fCdjSIQ_);
		(*T51_).Sup.Sup.Sup.name = "ZippyError";
		(*T51_).Sup.Sup.Sup.message = TM__KI6FnpwETfuweeL0NXTMMg_14;
		(*T51_).Sup.Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T51_, "ZippyError", "uncompressGzip", "gzip.nim", 62);
		goto BeforeRet_;
	}
	LA49_: ;
	checksum = read32__OOZOOZOOZOnimbleZpkgsZzippy4548O57O55ZzippyZinternal_390(src, (NI)(len - ((NI) 8)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	isize = read32__OOZOOZOOZOnimbleZpkgsZzippy4548O57O55ZzippyZinternal_390(src, (NI)(len - ((NI) 4)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!trustSize) goto LA54_;
		setLengthStrV2((&(*dst)), ((NI) ((NU32)((NU32)(isize) + (NU32)(((NU32) 16))))));
	}
	LA54_: ;
	inflate__OOZOOZOOZOnimbleZpkgsZzippy4548O57O55ZzippyZinflate_509(dst, src, len, pos);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NU32 T58_;
		tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ* T61_;
		T58_ = (NU32)0;
		T58_ = crc32__OOZOOZOOZOnimbleZpkgsZzippy4548O57O55ZzippyZcrc_138((*dst));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!!((checksum == T58_))) goto LA59_;
		T61_ = NIM_NIL;
		T61_ = (tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ*) nimNewObj(sizeof(tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ), NIM_ALIGNOF(tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ));
		(*T61_).Sup.Sup.Sup.Sup.m_type = (&NTIv2__j2RCbV49bRvsx6N3fCdjSIQ_);
		(*T61_).Sup.Sup.Sup.name = "ZippyError";
		(*T61_).Sup.Sup.Sup.message = TM__KI6FnpwETfuweeL0NXTMMg_16;
		(*T61_).Sup.Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T61_, "ZippyError", "uncompressGzip", "gzip.nim", 74);
		goto BeforeRet_;
	}
	LA59_: ;
	{
		tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ* T66_;
		if (!!((isize == ((NU32) ((NI)((*dst).len % ((NI) (-2147483647 -1)))))))) goto LA64_;
		T66_ = NIM_NIL;
		T66_ = (tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ*) nimNewObj(sizeof(tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ), NIM_ALIGNOF(tyObject_ZippyError__j2RCbV49bRvsx6N3fCdjSIQ));
		(*T66_).Sup.Sup.Sup.Sup.m_type = (&NTIv2__j2RCbV49bRvsx6N3fCdjSIQ_);
		(*T66_).Sup.Sup.Sup.name = "ZippyError";
		(*T66_).Sup.Sup.Sup.message = TM__KI6FnpwETfuweeL0NXTMMg_18;
		(*T66_).Sup.Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T66_, "ZippyError", "uncompressGzip", "gzip.nim", 77);
		goto BeforeRet_;
	}
	LA64_: ;
	}BeforeRet_: ;
}
