/* Generated by Nim Compiler v1.6.4 */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_FramebufferObj__1pPqnr9cylF8gi9bULYcALCQ tyObject_FramebufferObj__1pPqnr9cylF8gi9bULYcALCQ;
N_LIB_PRIVATE tyObject_FramebufferObj__1pPqnr9cylF8gi9bULYcALCQ* screen__OOZfauZsrcZfauZscreenbuffer_2;
