/* Generated by Nim Compiler v1.6.4 */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#include <stdlib.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_FauState__309cTFhuUrshBEQHbLmaQlw tyObject_FauState__309cTFhuUrshBEQHbLmaQlw;
typedef struct tyObject_Color__OSWJq3HNkIl1V7S3GsYvBg tyObject_Color__OSWJq3HNkIl1V7S3GsYvBg;
typedef struct tyObject_BatchcolonObjectType___RYPwJl20EVec0ujcBafF9aA tyObject_BatchcolonObjectType___RYPwJl20EVec0ujcBafF9aA;
typedef struct tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA;
typedef struct tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ;
typedef struct tyObject_CamcolonObjectType___4eTzE4gEL86vZ9bRFgwAN4A tyObject_CamcolonObjectType___4eTzE4gEL86vZ9bRFgwAN4A;
typedef struct tyObject_MeshObj__cPggZRHFWvGLKpQsZMF8yA tyObject_MeshObj__cPggZRHFWvGLKpQsZMF8yA;
typedef struct tyObject_ShaderObj__KFmcUvp7lIrtBdspoRxLXw tyObject_ShaderObj__KFmcUvp7lIrtBdspoRxLXw;
typedef struct tyObject_AtlascolonObjectType___5kuY28uezWLPxjw6Jjpi9ag tyObject_AtlascolonObjectType___5kuY28uezWLPxjw6Jjpi9ag;
typedef struct tySequence__HG77dJmfYz9agmsHT9aDRxHA tySequence__HG77dJmfYz9agmsHT9aDRxHA;
typedef struct tySequence__HG77dJmfYz9agmsHT9aDRxHA_Content tySequence__HG77dJmfYz9agmsHT9aDRxHA_Content;
typedef struct tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ;
typedef struct tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w;
typedef struct tyObject_Touch__O3vdnbkm84I9bOqV6XPOHdw tyObject_Touch__O3vdnbkm84I9bOqV6XPOHdw;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content tySequence__uB9b75OUPRENsBAu4AnoePA_Content;
typedef struct tyObject_FauEvent__YNvUGRpkmCiP22cM2l29bkQ tyObject_FauEvent__YNvUGRpkmCiP22cM2l29bkQ;
typedef struct tyObject_Time__3y2ZpqsTJLqdZvpC9a0rU2Q tyObject_Time__3y2ZpqsTJLqdZvpC9a0rU2Q;
typedef struct tyObject_FauInitParams__Z0pthJcpoAihemqm26DYFg tyObject_FauInitParams__Z0pthJcpoAihemqm26DYFg;
typedef struct tyObject_Env_coredotnim_initFau___l4LlgMNZocbw43qa0PmLHw tyObject_Env_coredotnim_initFau___l4LlgMNZocbw43qa0PmLHw;
typedef struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A;
typedef struct tyObject_Duration__lj9ar6Co3fgk6NgGnVaNpJw tyObject_Duration__lj9ar6Co3fgk6NgGnVaNpJw;
typedef struct tyObject_FramebufferObj__1pPqnr9cylF8gi9bULYcALCQ tyObject_FramebufferObj__1pPqnr9cylF8gi9bULYcALCQ;
typedef struct tyObject_Table__hLzAgCdI52IxQ1lJQGTKVA tyObject_Table__hLzAgCdI52IxQ1lJQGTKVA;
typedef struct tySequence__AB1TndMAvXQUoC2xJSQVEg tySequence__AB1TndMAvXQUoC2xJSQVEg;
typedef struct tySequence__AB1TndMAvXQUoC2xJSQVEg_Content tySequence__AB1TndMAvXQUoC2xJSQVEg_Content;
typedef struct tyObject_Table__c36tEmVxDEcCLwl9bZ5VYmw tyObject_Table__c36tEmVxDEcCLwl9bZ5VYmw;
typedef struct tySequence__NV14do9aURznn03ltuah5VA tySequence__NV14do9aURznn03ltuah5VA;
typedef struct tySequence__NV14do9aURznn03ltuah5VA_Content tySequence__NV14do9aURznn03ltuah5VA_Content;
typedef struct tyObject_Patch9__YtojNSDnK7j9aYZRNVXTN7g tyObject_Patch9__YtojNSDnK7j9aYZRNVXTN7g;
typedef struct tyTuple__wpFMp8IwxV6MlaM4GANJ0Q tyTuple__wpFMp8IwxV6MlaM4GANJ0Q;
typedef struct tyTuple__0vYzovSm9aKYybyF8MRuBJQ tyTuple__0vYzovSm9aKYybyF8MRuBJQ;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
typedef struct tyTuple__Ir1duhFQeN2Qu2wazAMb5w tyTuple__Ir1duhFQeN2Qu2wazAMb5w;
typedef struct tyTuple__HervhaKiavhm9bIe9bPCAHbA tyTuple__HervhaKiavhm9bIe9bPCAHbA;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc__HzVCwACFYM9cx9aV62PdjtuA;
typedef NU8 tyEnum_GLFMUserInterfaceChrome__DeDC6RscPPBwBTW8L0LFzA;
typedef NU8 tyEnum_GLFMRenderingAPI__m7gNWyYftn8SwRb0yBqEgw;
typedef NU8 tyEnum_GLFMColorFormat__WFrUyds4f29bI3cr1Fk0dvA;
typedef NU8 tyEnum_GLFMDepthFormat__CzlES7tOqhkveTpTGC0zWA;
typedef NU8 tyEnum_GLFMStencilFormat__Qo5BysVT79bf4LUta4F4jsw;
typedef NU8 tyEnum_GLFMMultisample__SIlDTvlE183jDOjkllQNrA;
struct tyObject_Color__OSWJq3HNkIl1V7S3GsYvBg {
NU8 rv;
NU8 gv;
NU8 bv;
NU8 av;
};
struct tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA {
tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ* texture;
NF32 u;
NF32 v;
NF32 u2;
NF32 v2;
};
struct tySequence__HG77dJmfYz9agmsHT9aDRxHA {
  NI len; tySequence__HG77dJmfYz9agmsHT9aDRxHA_Content* p;
};
struct tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ {
NI x;
NI y;
};
struct tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w {
NF32 x;
NF32 y;
};
typedef NF32 tyArray__9aTCwbdg1cSQimdVd0OEKVw[4];
struct tyObject_Touch__O3vdnbkm84I9bOqV6XPOHdw {
tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w pos;
tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w delta;
tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w last;
NIM_BOOL down;
};
typedef tyObject_Touch__O3vdnbkm84I9bOqV6XPOHdw tyArray__q1daT0HgNuIpm71XQ8ZW8w[10];
struct tyObject_FauState__309cTFhuUrshBEQHbLmaQlw {
tyObject_Color__OSWJq3HNkIl1V7S3GsYvBg clearColor;
tyObject_BatchcolonObjectType___RYPwJl20EVec0ujcBafF9aA* batch;
NF32 pixelScl;
tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA white;
tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA circle;
tyObject_CamcolonObjectType___4eTzE4gEL86vZ9bRFgwAN4A* cam;
tyObject_MeshObj__cPggZRHFWvGLKpQsZMF8yA* quad;
tyObject_ShaderObj__KFmcUvp7lIrtBdspoRxLXw* screenspace;
tyObject_AtlascolonObjectType___5kuY28uezWLPxjw6Jjpi9ag* atlas;
NI64 frameId;
NI fps;
NF32 delta;
NF rawDelta;
NF32 targetFps;
NF32 maxDelta;
NF32 time;
tySequence__HG77dJmfYz9agmsHT9aDRxHA listeners;
tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ sizei;
tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w size;
NF32 screenDensity;
tyArray__9aTCwbdg1cSQimdVd0OEKVw insets;
NIM_BOOL shown;
tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w mouse;
tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w scroll;
tyArray__q1daT0HgNuIpm71XQ8ZW8w touches;
};
typedef N_CDECL_PTR(void, tyProc__tSXorcuQMTR0CDK3H74oXg) (void** display, NCSTRING message);
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
struct TNimTypeV2 {
void* destructor;
NI size;
NI align;
NCSTRING name;
void* traceImpl;
void* typeInfoV1;
NI flags;
};
struct RootObj {
TNimTypeV2* m_type;
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  NI len; tySequence__uB9b75OUPRENsBAu4AnoePA_Content* p;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringV2 message;
tySequence__uB9b75OUPRENsBAu4AnoePA trace;
Exception* up;
};
typedef NimStringV2 tyArray__nHXaesL0DJZHyVS07ARPRA[1];
typedef N_CDECL_PTR(void, tyProc__eBQXvlktf2qIE9c0oKigWOw) (void** display, int width, int height);
typedef NU8 tyEnum_FauEventKind__xJFQo4JN2Z8swZKj8kGvYA;
typedef NU8 tyEnum_KeyCode__YhMyimscyfYwYiOPDuaH9bg;
struct tyObject_FauEvent__YNvUGRpkmCiP22cM2l29bkQ {
tyEnum_FauEventKind__xJFQo4JN2Z8swZKj8kGvYA kind;
union{
struct {tyEnum_KeyCode__YhMyimscyfYwYiOPDuaH9bg key;
NIM_BOOL keyDown;
} _kind_1;
struct {NI dragId;
tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w dragPos;
} _kind_2;
struct {NI touchId;
tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w touchPos;
NIM_BOOL touchDown;
tyEnum_KeyCode__YhMyimscyfYwYiOPDuaH9bg touchButton;
} _kind_3;
struct {tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w scroll;
} _kind_4;
struct {tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ size;
} _kind_5;
struct {NIM_BOOL shown;
} _kind_6;
};
};
typedef NU8 tyEnum_GLFMTouchPhase__nZYCBXwe50hT7mI9c6i9aIJA;
typedef N_CDECL_PTR(NIM_BOOL, tyProc__GYz9aAeXcUcXhZu8mHnkryQ) (void** display, int touch, tyEnum_GLFMTouchPhase__nZYCBXwe50hT7mI9c6i9aIJA phase, double x, double y);
typedef NU16 tyEnum_GLFMKey__KP9cywviLen49cxOidB6iriw;
typedef NU8 tyEnum_GLFMKeyAction__vh34eg2vDtKgLmgmzFWrrQ;
typedef N_CDECL_PTR(NIM_BOOL, tyProc__9c2FoZfrAgzQABUWTVMy9bsQ) (void** display, tyEnum_GLFMKey__KP9cywviLen49cxOidB6iriw keyCode, tyEnum_GLFMKeyAction__vh34eg2vDtKgLmgmzFWrrQ action, int modifiers);
typedef N_CDECL_PTR(void, tyProc__ln4kdL5W9bbX4a1xl8nnVXQ) (void);
typedef N_CDECL_PTR(tyProc__ln4kdL5W9bbX4a1xl8nnVXQ, tyProc__ZHwhrY39a8osp8M5lIF2USQ) (NCSTRING functionName);
typedef N_CLOSURE_PTR(void, TM__K9bwUuXws1Vn05sdTB9cnnxA_12) (void);
typedef N_CDECL_PTR(void, tyProc__bUzTHA9cDAo9c7djyJ80K6Vg) (void** display, double frameTime);
typedef N_CLOSURE_PTR(void, TM__K9bwUuXws1Vn05sdTB9cnnxA_13) (void);
typedef N_CDECL_PTR(void, tyProc__tvFChPh9cfry8HdsD2T8WuA) (void** display);
typedef N_CDECL_PTR(void, tyProc__rPBsRF6SiVzZaGPFQyigRw) (void** display, NIM_BOOL focused);
struct tyObject_Time__3y2ZpqsTJLqdZvpC9a0rU2Q {
NI64 seconds;
NI nanosecond;
};
struct tyObject_FauInitParams__Z0pthJcpoAihemqm26DYFg {
tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ size;
NimStringV2 title;
NIM_BOOL maximize;
NIM_BOOL depth;
NIM_BOOL undecorated;
NIM_BOOL transparent;
tyObject_Color__OSWJq3HNkIl1V7S3GsYvBg clearColor;
};
struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A {
NI rc;
};
struct tyObject_Env_coredotnim_initFau___l4LlgMNZocbw43qa0PmLHw {
  RootObj Sup;
NI colonstate_;
tyProc__HzVCwACFYM9cx9aV62PdjtuA loopProc1;
tyObject_FauInitParams__Z0pthJcpoAihemqm26DYFg params2;
tyProc__HzVCwACFYM9cx9aV62PdjtuA initProc3;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_FauEvent__YNvUGRpkmCiP22cM2l29bkQ e, void* ClE_0);
void* ClE_0;
} tyProc__pYsVTQ4Z7hmuFG9c39aHjS9cw;
typedef NIM_BOOL tyArray__SlNOxfPKUGCkXwonBOn1QQ[153];
typedef N_CLOSURE_PTR(void, TM__K9bwUuXws1Vn05sdTB9cnnxA_14) (tyObject_FauEvent__YNvUGRpkmCiP22cM2l29bkQ e, void* ClE_0);
struct tyObject_Duration__lj9ar6Co3fgk6NgGnVaNpJw {
NI64 seconds;
NI nanosecond;
};
typedef N_CLOSURE_PTR(void, TM__K9bwUuXws1Vn05sdTB9cnnxA_15) (void);
struct tySequence__AB1TndMAvXQUoC2xJSQVEg {
  NI len; tySequence__AB1TndMAvXQUoC2xJSQVEg_Content* p;
};
struct tyObject_Table__hLzAgCdI52IxQ1lJQGTKVA {
tySequence__AB1TndMAvXQUoC2xJSQVEg data;
NI counter;
};
struct tySequence__NV14do9aURznn03ltuah5VA {
  NI len; tySequence__NV14do9aURznn03ltuah5VA_Content* p;
};
struct tyObject_Table__c36tEmVxDEcCLwl9bZ5VYmw {
tySequence__NV14do9aURznn03ltuah5VA data;
NI counter;
};
typedef tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA tyArray__cYLMonStdqJ9bQDnj3JlASw[9];
struct tyObject_Patch9__YtojNSDnK7j9aYZRNVXTN7g {
tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ* texture;
NI left;
NI right;
NI top;
NI bot;
NI width;
NI height;
tyArray__cYLMonStdqJ9bQDnj3JlASw patches;
};
struct tyObject_AtlascolonObjectType___5kuY28uezWLPxjw6Jjpi9ag {
tyObject_Table__hLzAgCdI52IxQ1lJQGTKVA patches;
tyObject_Table__c36tEmVxDEcCLwl9bZ5VYmw patches9;
tyObject_TextureObj__cVmPWt9bHJAYuqtGMTQozzQ* texture;
tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA error;
tyObject_Patch9__YtojNSDnK7j9aYZRNVXTN7g error9;
};
struct tyTuple__wpFMp8IwxV6MlaM4GANJ0Q {
NF Field0;
NF Field1;
};
struct tyTuple__0vYzovSm9aKYybyF8MRuBJQ {
NF Field0;
NF Field1;
NF Field2;
NF Field3;
};
typedef N_CLOSURE_PTR(void, TM__K9bwUuXws1Vn05sdTB9cnnxA_25) (void);


#ifndef tySequence__HG77dJmfYz9agmsHT9aDRxHA_Content_PP
#define tySequence__HG77dJmfYz9agmsHT9aDRxHA_Content_PP
struct tySequence__HG77dJmfYz9agmsHT9aDRxHA_Content { NI cap; tyProc__pYsVTQ4Z7hmuFG9c39aHjS9cw data[SEQ_DECL_SIZE];};
#endif

      struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};


#ifndef tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
#define tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content { NI cap; tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};
#endif

      struct tyTuple__Ir1duhFQeN2Qu2wazAMb5w {
NI Field0;
NimStringV2 Field1;
tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA Field2;
};


#ifndef tySequence__AB1TndMAvXQUoC2xJSQVEg_Content_PP
#define tySequence__AB1TndMAvXQUoC2xJSQVEg_Content_PP
struct tySequence__AB1TndMAvXQUoC2xJSQVEg_Content { NI cap; tyTuple__Ir1duhFQeN2Qu2wazAMb5w data[SEQ_DECL_SIZE];};
#endif

      struct tyTuple__HervhaKiavhm9bIe9bPCAHbA {
NI Field0;
NimStringV2 Field1;
tyObject_Patch9__YtojNSDnK7j9aYZRNVXTN7g Field2;
};


#ifndef tySequence__NV14do9aURznn03ltuah5VA_Content_PP
#define tySequence__NV14do9aURznn03ltuah5VA_Content_PP
struct tySequence__NV14do9aURznn03ltuah5VA_Content { NI cap; tyTuple__HervhaKiavhm9bIe9bPCAHbA data[SEQ_DECL_SIZE];};
#endif

      N_LIB_PRIVATE N_CDECL(void, glfmMain)(void** display);
N_NIMCALL(void, NimMain)(void);
N_CDECL(void, glfmSetDisplayChrome)(void** display, tyEnum_GLFMUserInterfaceChrome__DeDC6RscPPBwBTW8L0LFzA uiChrome);
N_CDECL(void, glfmSetDisplayConfig)(void** display, tyEnum_GLFMRenderingAPI__m7gNWyYftn8SwRb0yBqEgw preferredAPI, tyEnum_GLFMColorFormat__WFrUyds4f29bI3cr1Fk0dvA colorFormat, tyEnum_GLFMDepthFormat__CzlES7tOqhkveTpTGC0zWA depthFormat, tyEnum_GLFMStencilFormat__Qo5BysVT79bf4LUta4F4jsw stencilFormat, tyEnum_GLFMMultisample__SIlDTvlE183jDOjkllQNrA multisample);
N_CDECL(double, glfmGetDisplayScale)(void** display);
N_CDECL(void, glfmSetSurfaceErrorFunc)(void** display, tyProc__tSXorcuQMTR0CDK3H74oXg surfaceErrorFunc);
N_LIB_PRIVATE N_CDECL(void, colonanonymous___OOZfauZsrcZcore_57)(void** display, NCSTRING message);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size, NI alignment);
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(void, copyMem__system_1709)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_2592)(NimStringV2* dest);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args, NI argsLen_0);
N_CDECL(void, glfmSetSurfaceResizedFunc)(void** display, tyProc__eBQXvlktf2qIE9c0oKigWOw surfaceResizedFunc);
N_LIB_PRIVATE N_CDECL(void, colonanonymous___OOZfauZsrcZcore_61)(void** surf, int width, int height);
N_LIB_PRIVATE N_NIMCALL(void, updateInsets__OOZfauZsrcZcore_40)(void** display);
N_CDECL(void, glfmGetDisplayChromeInsets)(void** display, double* top, double* right, double* bottom, double* left);
N_LIB_PRIVATE N_NIMCALL(void, fireFauEvent__OOZfauZsrcZfauZglobals_571)(tyObject_FauEvent__YNvUGRpkmCiP22cM2l29bkQ ev);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
static N_INLINE(tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ, vec2i__OOZfauZsrcZfauZfmath_428)(NI x, NI y);
N_CDECL(void, glfmSetTouchFunc)(void** display, tyProc__GYz9aAeXcUcXhZu8mHnkryQ touchFunc);
N_LIB_PRIVATE N_CDECL(NIM_BOOL, colonanonymous___OOZfauZsrcZcore_86)(void** display, int touch, tyEnum_GLFMTouchPhase__nZYCBXwe50hT7mI9c6i9aIJA phase, double x, double y);
N_CDECL(void, glfmSetKeyFunc)(void** display, tyProc__9c2FoZfrAgzQABUWTVMy9bsQ keyFunc);
N_LIB_PRIVATE N_CDECL(NIM_BOOL, colonanonymous___OOZfauZsrcZcore_110)(void** display, tyEnum_GLFMKey__KP9cywviLen49cxOidB6iriw keyCode, tyEnum_GLFMKeyAction__vh34eg2vDtKgLmgmzFWrrQ action, int modifiers);
N_LIB_PRIVATE N_NIMCALL(tyEnum_KeyCode__YhMyimscyfYwYiOPDuaH9bg, toKeyCode__OOZfauZsrcZcore_28)(tyEnum_GLFMKey__KP9cywviLen49cxOidB6iriw code);
N_CDECL(void, glfmSetSurfaceCreatedFunc)(void** display, tyProc__eBQXvlktf2qIE9c0oKigWOw surfaceCreatedFunc);
N_LIB_PRIVATE N_CDECL(void, colonanonymous___OOZfauZsrcZcore_117)(void** surf, int width, int height);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, loadGl__OOZfauZsrcZcore_121)(tyProc__ZHwhrY39a8osp8M5lIF2USQ load);
N_CDECL(tyProc__ln4kdL5W9bbX4a1xl8nnVXQ, glfmGetProcAddress)(NCSTRING functionName);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_3)(NI x);
N_CDECL(void, glfmSetMainLoopFunc)(void** display, tyProc__bUzTHA9cDAo9c7djyJ80K6Vg mainLoopFunc);
N_LIB_PRIVATE N_CDECL(void, colonanonymous___OOZfauZsrcZcore_679)(void** display, double frameTime);
N_CDECL(void, glfmSetSurfaceDestroyedFunc)(void** display, tyProc__tvFChPh9cfry8HdsD2T8WuA surfaceDestroyedFunc);
N_LIB_PRIVATE N_CDECL(void, colonanonymous___OOZfauZsrcZcore_682)(void** display);
N_CDECL(void, glfmSetAppFocusFunc)(void** display, tyProc__rPBsRF6SiVzZaGPFQyigRw focusFunc);
N_LIB_PRIVATE N_CDECL(void, colonanonymous___OOZfauZsrcZcore_684)(void** display, NIM_BOOL focused);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZfauZsrcZcore_1556)(tyObject_Env_coredotnim_initFau___l4LlgMNZocbw43qa0PmLHw** dest);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p);
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZfauZsrcZcore_1534)(tyObject_Env_coredotnim_initFau___l4LlgMNZocbw43qa0PmLHw* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___OOZfauZsrcZfauZdraw_430)(tyProc__HzVCwACFYM9cx9aV62PdjtuA* dest, tyProc__HzVCwACFYM9cx9aV62PdjtuA src);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___OOZfauZsrcZfauZglobals_219)(tyObject_FauInitParams__Z0pthJcpoAihemqm26DYFg* dest, tyObject_FauInitParams__Z0pthJcpoAihemqm26DYFg src);
N_LIB_PRIVATE N_NIMCALL(void, addFauListener__OOZfauZsrcZfauZglobals_603)(tyProc__pYsVTQ4Z7hmuFG9c39aHjS9cw ev);
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___OOZfauZsrcZcore_725)(tyObject_FauEvent__YNvUGRpkmCiP22cM2l29bkQ e);
static N_INLINE(tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w, vec2__OOZfauZsrcZfauZfmath_446)(tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ v);
N_LIB_PRIVATE N_NIMCALL(void, initCore__OOZfauZsrcZcore_694)(tyProc__HzVCwACFYM9cx9aV62PdjtuA loopProc, tyProc__HzVCwACFYM9cx9aV62PdjtuA initProc, tyObject_FauInitParams__Z0pthJcpoAihemqm26DYFg params);
N_LIB_PRIVATE N_CLOSURE(void, colonanonymous___OOZfauZsrcZcore_755)(void* ClE_0);
N_LIB_PRIVATE N_NIMCALL(NI64, inNanoseconds__pureZtimes_675)(tyObject_Duration__lj9ar6Co3fgk6NgGnVaNpJw dur);
N_LIB_PRIVATE N_NIMCALL(tyObject_Duration__lj9ar6Co3fgk6NgGnVaNpJw, ntDiffTime)(tyObject_Time__3y2ZpqsTJLqdZvpC9a0rU2Q a, tyObject_Time__3y2ZpqsTJLqdZvpC9a0rU2Q b);
N_LIB_PRIVATE N_NIMCALL(tyObject_Time__3y2ZpqsTJLqdZvpC9a0rU2Q, getTime__pureZtimes_952)(void);
N_LIB_PRIVATE N_NIMCALL(void, nossleep)(NI milsecs);
static N_INLINE(NF, min__system_2050)(NF x, NF y);
static N_INLINE(void, pluseq___OOZfauZsrcZfauZfmath_107)(NF32* x, NF32 y);
static N_INLINE(tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w, minus___OOZfauZsrcZfauZfmath_506)(tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w vecX60gensym19_, tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w otherX60gensym19_);
N_LIB_PRIVATE N_NIMCALL(void, resize__OOZfauZsrcZfauZframebuffer_22)(tyObject_FramebufferObj__1pPqnr9cylF8gi9bULYcALCQ* buffer, tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ size);
N_LIB_PRIVATE N_NIMCALL(void, clear__OOZfauZsrcZfauZframebuffer_87)(tyObject_FramebufferObj__1pPqnr9cylF8gi9bULYcALCQ* buffer, tyObject_Color__OSWJq3HNkIl1V7S3GsYvBg color);
N_LIB_PRIVATE N_NIMCALL(void, drawFlush__OOZfauZsrcZfauZdraw_401)(void);
N_LIB_PRIVATE N_CLOSURE(void, colonanonymous___OOZfauZsrcZcore_869)(void* ClE_0);
N_LIB_PRIVATE N_NIMCALL(void, randomize__pureZrandom_277)(void);
N_LIB_PRIVATE N_NIMCALL(void, initAudio__OOZfauZsrcZfauZaudio_27)(void);
N_LIB_PRIVATE N_NIMCALL(void, loadAudio__OOZfauZsrcZfauZaudio_384)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZfauZsrcZfauZframebuffer_76)(tyObject_FramebufferObj__1pPqnr9cylF8gi9bULYcALCQ** dest, tyObject_FramebufferObj__1pPqnr9cylF8gi9bULYcALCQ* src);
N_LIB_PRIVATE N_NIMCALL(tyObject_FramebufferObj__1pPqnr9cylF8gi9bULYcALCQ*, newDefaultFramebuffer__OOZfauZsrcZfauZframebuffer_82)(NIM_BOOL windowDepth);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZfauZsrcZfauZbatch_729)(tyObject_BatchcolonObjectType___RYPwJl20EVec0ujcBafF9aA** dest, tyObject_BatchcolonObjectType___RYPwJl20EVec0ujcBafF9aA* src);
N_LIB_PRIVATE N_NIMCALL(tyObject_BatchcolonObjectType___RYPwJl20EVec0ujcBafF9aA*, newBatch__OOZfauZsrcZfauZbatch_459)(NI size);
N_LIB_PRIVATE N_NIMCALL(void, screenMat__OOZfauZsrcZfauZdraw_409)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZfauZsrcZfauZfmath_1326)(tyObject_CamcolonObjectType___4eTzE4gEL86vZ9bRFgwAN4A** dest, tyObject_CamcolonObjectType___4eTzE4gEL86vZ9bRFgwAN4A* src);
N_LIB_PRIVATE N_NIMCALL(tyObject_CamcolonObjectType___4eTzE4gEL86vZ9bRFgwAN4A*, newCam__OOZfauZsrcZfauZfmath_1308)(tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w size);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZfauZsrcZcore_1482)(tyObject_AtlascolonObjectType___5kuY28uezWLPxjw6Jjpi9ag** dest, tyObject_AtlascolonObjectType___5kuY28uezWLPxjw6Jjpi9ag* src);
N_LIB_PRIVATE N_NIMCALL(tyObject_AtlascolonObjectType___5kuY28uezWLPxjw6Jjpi9ag*, loadAtlas__OOZfauZsrcZcore_870)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZfauZsrcZfauZmesh_412)(tyObject_MeshObj__cPggZRHFWvGLKpQsZMF8yA** dest, tyObject_MeshObj__cPggZRHFWvGLKpQsZMF8yA* src);
N_LIB_PRIVATE N_NIMCALL(tyObject_MeshObj__cPggZRHFWvGLKpQsZMF8yA*, newScreenMesh__OOZfauZsrcZfauZmesh_312)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZfauZsrcZfauZshader_1658)(tyObject_ShaderObj__KFmcUvp7lIrtBdspoRxLXw** dest, tyObject_ShaderObj__KFmcUvp7lIrtBdspoRxLXw* src);
N_LIB_PRIVATE N_NIMCALL(tyObject_ShaderObj__KFmcUvp7lIrtBdspoRxLXw*, newShader__OOZfauZsrcZfauZshader_65)(NimStringV2 vertexSource, NimStringV2 fragmentSource);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZfauZsrcZfauZpatch_31)(tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA* dest, tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA src);
static N_INLINE(void, X5BX5D___OOZfauZsrcZfauZatlas_47)(tyObject_AtlascolonObjectType___5kuY28uezWLPxjw6Jjpi9ag* atlas, NimStringV2 name, tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA* Result);
N_LIB_PRIVATE N_NIMCALL(void, getOrDefault__OOZfauZsrcZfauZatlas_117)(tyObject_Table__hLzAgCdI52IxQ1lJQGTKVA t, NimStringV2 key, tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA default_0, tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA* Result);
extern TNimTypeV2 NTIv2__XEycrCsme5C8CVWAYEcdBQ_;
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__K9bwUuXws1Vn05sdTB9cnnxA_2 = { 12 | NIM_STRLIT_FLAG, "GLFM error: " };
static const NimStringV2 TM__K9bwUuXws1Vn05sdTB9cnnxA_3 = {12, (NimStrPayload*)&TM__K9bwUuXws1Vn05sdTB9cnnxA_2};
static const struct {
  NI cap; NIM_CHAR data[21+1];
} TM__K9bwUuXws1Vn05sdTB9cnnxA_5 = { 21 | NIM_STRLIT_FLAG, "Initialized GLFM v0.9" };
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__K9bwUuXws1Vn05sdTB9cnnxA_4 = {{21, (NimStrPayload*)&TM__K9bwUuXws1Vn05sdTB9cnnxA_5}}
;
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__K9bwUuXws1Vn05sdTB9cnnxA_6 = { 22 | NIM_STRLIT_FLAG, "Failed to load OpenGL." };
static const NimStringV2 TM__K9bwUuXws1Vn05sdTB9cnnxA_7 = {22, (NimStrPayload*)&TM__K9bwUuXws1Vn05sdTB9cnnxA_6};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__K9bwUuXws1Vn05sdTB9cnnxA_8 = { 20 | NIM_STRLIT_FLAG, "Initialized OpenGL v" };
static const NimStringV2 TM__K9bwUuXws1Vn05sdTB9cnnxA_9 = {20, (NimStrPayload*)&TM__K9bwUuXws1Vn05sdTB9cnnxA_8};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__K9bwUuXws1Vn05sdTB9cnnxA_10 = { 1 | NIM_STRLIT_FLAG, "." };
static const NimStringV2 TM__K9bwUuXws1Vn05sdTB9cnnxA_11 = {1, (NimStrPayload*)&TM__K9bwUuXws1Vn05sdTB9cnnxA_10};
N_LIB_PRIVATE TNimTypeV2 NTIv2__l4LlgMNZocbw43qa0PmLHw_;
static const struct {
  NI cap; NIM_CHAR data[120+1];
} TM__K9bwUuXws1Vn05sdTB9cnnxA_16 = { 120 | NIM_STRLIT_FLAG, "attribute vec4 a_pos;\012attribute vec2 a_uv;\012varying vec2 v_uv;\012\012void main(){\012    v_uv = a_uv;\012    gl_Position = a_pos;\012}\012" };
static const NimStringV2 TM__K9bwUuXws1Vn05sdTB9cnnxA_17 = {120, (NimStrPayload*)&TM__K9bwUuXws1Vn05sdTB9cnnxA_16};
static const struct {
  NI cap; NIM_CHAR data[109+1];
} TM__K9bwUuXws1Vn05sdTB9cnnxA_18 = { 109 | NIM_STRLIT_FLAG, "uniform sampler2D u_texture;\012varying vec2 v_uv;\012\012void main(){\012  gl_FragColor = texture2D(u_texture, v_uv);\012}\012" };
static const NimStringV2 TM__K9bwUuXws1Vn05sdTB9cnnxA_19 = {109, (NimStrPayload*)&TM__K9bwUuXws1Vn05sdTB9cnnxA_18};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__K9bwUuXws1Vn05sdTB9cnnxA_20 = { 5 | NIM_STRLIT_FLAG, "white" };
static const NimStringV2 TM__K9bwUuXws1Vn05sdTB9cnnxA_21 = {5, (NimStrPayload*)&TM__K9bwUuXws1Vn05sdTB9cnnxA_20};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__K9bwUuXws1Vn05sdTB9cnnxA_22 = { 6 | NIM_STRLIT_FLAG, "circle" };
static const NimStringV2 TM__K9bwUuXws1Vn05sdTB9cnnxA_23 = {6, (NimStrPayload*)&TM__K9bwUuXws1Vn05sdTB9cnnxA_22};
static NIM_CONST tyProc__HzVCwACFYM9cx9aV62PdjtuA TM__K9bwUuXws1Vn05sdTB9cnnxA_24 = {NIM_NIL,NIM_NIL};
N_LIB_PRIVATE tyProc__HzVCwACFYM9cx9aV62PdjtuA cloopProc__OOZfauZsrcZcore_25;
N_LIB_PRIVATE tyProc__HzVCwACFYM9cx9aV62PdjtuA cinitProc__OOZfauZsrcZcore_27;
extern tyObject_FauState__309cTFhuUrshBEQHbLmaQlw fau__OOZfauZsrcZfauZglobals_252;
extern NIM_BOOL nimInErrorMode__system_3443;
extern NI glVersionMajor__OOZfauZsrcZfauZglZglad_3;
extern NI glVersionMinor__OOZfauZsrcZfauZglZglad_4;
extern NIM_BOOL glInitialized__OOZfauZsrcZfauZglZglproc_8;
N_LIB_PRIVATE NI64 lastFrameTime__OOZfauZsrcZcore_714 = IL64(-1);
N_LIB_PRIVATE NI64 frameCounterStart__OOZfauZsrcZcore_715;
N_LIB_PRIVATE NI frames__OOZfauZsrcZcore_716;
N_LIB_PRIVATE tyObject_Time__3y2ZpqsTJLqdZvpC9a0rU2Q startTime__OOZfauZsrcZcore_717;
extern tyArray__SlNOxfPKUGCkXwonBOn1QQ keysJustDown__OOZfauZsrcZfauZinput_4;
extern tyArray__SlNOxfPKUGCkXwonBOn1QQ keysPressed__OOZfauZsrcZfauZinput_3;
extern tyArray__SlNOxfPKUGCkXwonBOn1QQ keysJustUp__OOZfauZsrcZfauZinput_5;
extern tyObject_FramebufferObj__1pPqnr9cylF8gi9bULYcALCQ* screen__OOZfauZsrcZfauZscreenbuffer_2;
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__system_1709)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src) {
	{
		if (!(((NI) 0) < src.len)) goto LA3_;
		copyMem__system_1709(((void*) ((&(*(*dest).p).data[(*dest).len]))), ((void*) ((&(*src.p).data[((NI) 0)]))), ((NI) ((NI)(src.len + ((NI) 1)))));
		(*dest).len += src.len;
	}
	LA3_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__system_3443);
	return result;
}
N_LIB_PRIVATE N_CDECL(void, colonanonymous___OOZfauZsrcZcore_57)(void** display, NCSTRING message) {
	NimStringV2 colontmpD_;
	Exception* T2_;
	NimStringV2 T3_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	T2_ = NIM_NIL;
	T2_ = (Exception*) nimNewObj(sizeof(Exception), NIM_ALIGNOF(Exception));
	(*T2_).Sup.m_type = (&NTIv2__XEycrCsme5C8CVWAYEcdBQ_);
	(*T2_).name = "Exception";
	T3_.len = 0; T3_.p = NIM_NIL;
	colontmpD_ = cstrToNimstr(message);
	T3_ = rawNewString(colontmpD_.len + 12);
appendString((&T3_), TM__K9bwUuXws1Vn05sdTB9cnnxA_3);
appendString((&T3_), colontmpD_);
	(*T2_).message = T3_;
	(*T2_).parent = ((Exception*) NIM_NIL);
	raiseExceptionEx((Exception*)T2_, "Exception", ":anonymous", "glfmcore.nim", 44);
	goto LA1_;
	{
		LA1_:;
	}
	{
		eqdestroy___system_2592((&colontmpD_));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, updateInsets__OOZfauZsrcZcore_40)(void** display) {
	double top;
	double right;
	double bot;
	double left;
	top = (double)0;
	right = (double)0;
	bot = (double)0;
	left = (double)0;
	glfmGetDisplayChromeInsets(display, (&top), (&right), (&bot), (&left));
	fau__OOZfauZsrcZfauZglobals_252.insets[(((NI) 0))- 0] = ((NF32) (top));
	fau__OOZfauZsrcZfauZglobals_252.insets[(((NI) 1))- 0] = ((NF32) (right));
	fau__OOZfauZsrcZfauZglobals_252.insets[(((NI) 2))- 0] = ((NF32) (bot));
	fau__OOZfauZsrcZfauZglobals_252.insets[(((NI) 3))- 0] = ((NF32) (left));
}
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ, vec2i__OOZfauZsrcZfauZfmath_428)(NI x, NI y) {
	tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ result;
	NI colontmpD_;
	NI colontmpD__2;
	nimZeroMem((void*)(&result), sizeof(tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ));
	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	nimZeroMem((void*)(&result), sizeof(tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ));
	colontmpD_ = x;
	result.x = colontmpD_;
	colontmpD__2 = y;
	result.y = colontmpD__2;
	return result;
}
N_LIB_PRIVATE N_CDECL(void, colonanonymous___OOZfauZsrcZcore_61)(void** surf, int width, int height) {
	tyObject_FauEvent__YNvUGRpkmCiP22cM2l29bkQ T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	updateInsets__OOZfauZsrcZcore_40(surf);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimZeroMem((void*)(&T1_), sizeof(tyObject_FauEvent__YNvUGRpkmCiP22cM2l29bkQ));
	T1_.kind = ((tyEnum_FauEventKind__xJFQo4JN2Z8swZKj8kGvYA) 4);
	T1_._kind_5.size = vec2i__OOZfauZsrcZfauZfmath_428(((NI) (width)), ((NI) (height)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	fireFauEvent__OOZfauZsrcZfauZglobals_571(T1_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_CDECL(NIM_BOOL, colonanonymous___OOZfauZsrcZcore_86)(void** display, int touch, tyEnum_GLFMTouchPhase__nZYCBXwe50hT7mI9c6i9aIJA phase, double x, double y) {
	NIM_BOOL result;
	double colontmpD_;
	tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	colontmpD_ = (double)0;
	nimZeroMem((void*)(&T1_), sizeof(tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w));
	colontmpD_ = x;
	T1_.x = ((NF32) (colontmpD_));
	T1_.y = ((NF32)(((NF32)(fau__OOZfauZsrcZfauZglobals_252.size.y) - (NF32)(1.0f))) - (NF32)(((NF32) (y))));
	fau__OOZfauZsrcZfauZglobals_252.mouse = T1_;
	{
		NIM_BOOL T4_;
		tyObject_FauEvent__YNvUGRpkmCiP22cM2l29bkQ T8_;
		T4_ = (NIM_BOOL)0;
		T4_ = (phase == ((tyEnum_GLFMTouchPhase__nZYCBXwe50hT7mI9c6i9aIJA) 1));
		if (T4_) goto LA5_;
		T4_ = (phase == ((tyEnum_GLFMTouchPhase__nZYCBXwe50hT7mI9c6i9aIJA) 3));
		LA5_: ;
		if (!T4_) goto LA6_;
		nimZeroMem((void*)(&T8_), sizeof(tyObject_FauEvent__YNvUGRpkmCiP22cM2l29bkQ));
		T8_.kind = ((tyEnum_FauEventKind__xJFQo4JN2Z8swZKj8kGvYA) 2);
		T8_._kind_3.touchId = ((NI) (touch));
		nimZeroMem((void*)(&T8_._kind_3.touchPos), sizeof(tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w));
		T8_._kind_3.touchPos.x = ((NF32) (x));
		T8_._kind_3.touchPos.y = ((NF32)(((NF32)(fau__OOZfauZsrcZfauZglobals_252.size.y) - (NF32)(1.0f))) - (NF32)(((NF32) (y))));
		T8_._kind_3.touchDown = (phase == ((tyEnum_GLFMTouchPhase__nZYCBXwe50hT7mI9c6i9aIJA) 1));
		T8_._kind_3.touchButton = ((tyEnum_KeyCode__YhMyimscyfYwYiOPDuaH9bg) 150);
		fireFauEvent__OOZfauZsrcZfauZglobals_571(T8_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA2_;
	LA6_: ;
	{
		tyObject_FauEvent__YNvUGRpkmCiP22cM2l29bkQ T12_;
		if (!(phase == ((tyEnum_GLFMTouchPhase__nZYCBXwe50hT7mI9c6i9aIJA) 2))) goto LA10_;
		nimZeroMem((void*)(&T12_), sizeof(tyObject_FauEvent__YNvUGRpkmCiP22cM2l29bkQ));
		T12_.kind = ((tyEnum_FauEventKind__xJFQo4JN2Z8swZKj8kGvYA) 1);
		T12_._kind_2.dragId = ((NI) (touch));
		nimZeroMem((void*)(&T12_._kind_2.dragPos), sizeof(tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w));
		T12_._kind_2.dragPos.x = ((NF32) (x));
		T12_._kind_2.dragPos.y = ((NF32)(((NF32)(fau__OOZfauZsrcZfauZglobals_252.size.y) - (NF32)(1.0f))) - (NF32)(((NF32) (y))));
		fireFauEvent__OOZfauZsrcZfauZglobals_571(T12_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA2_;
	LA10_: ;
	LA2_: ;
	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyEnum_KeyCode__YhMyimscyfYwYiOPDuaH9bg, toKeyCode__OOZfauZsrcZcore_28)(tyEnum_GLFMKey__KP9cywviLen49cxOidB6iriw code) {
	tyEnum_KeyCode__YhMyimscyfYwYiOPDuaH9bg result;
	tyEnum_KeyCode__YhMyimscyfYwYiOPDuaH9bg colontmpD_;
	tyEnum_KeyCode__YhMyimscyfYwYiOPDuaH9bg colontmpD__2;
{	result = (tyEnum_KeyCode__YhMyimscyfYwYiOPDuaH9bg)0;
	colontmpD_ = (tyEnum_KeyCode__YhMyimscyfYwYiOPDuaH9bg)0;
	colontmpD__2 = (tyEnum_KeyCode__YhMyimscyfYwYiOPDuaH9bg)0;
	switch (code) {
	case ((tyEnum_GLFMKey__KP9cywviLen49cxOidB6iriw) 4096):
	case ((tyEnum_GLFMKey__KP9cywviLen49cxOidB6iriw) 27):
	{
		colontmpD_ = ((tyEnum_KeyCode__YhMyimscyfYwYiOPDuaH9bg) 37);
		result = colontmpD_;
	}
	break;
	default:
	{
		colontmpD__2 = ((tyEnum_KeyCode__YhMyimscyfYwYiOPDuaH9bg) 149);
		result = colontmpD__2;
	}
	break;
	}
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_CDECL(NIM_BOOL, colonanonymous___OOZfauZsrcZcore_110)(void** display, tyEnum_GLFMKey__KP9cywviLen49cxOidB6iriw keyCode, tyEnum_GLFMKeyAction__vh34eg2vDtKgLmgmzFWrrQ action, int modifiers) {
	NIM_BOOL result;
	tyEnum_KeyCode__YhMyimscyfYwYiOPDuaH9bg code;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	code = toKeyCode__OOZfauZsrcZcore_28(keyCode);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	switch (action) {
	case ((tyEnum_GLFMKeyAction__vh34eg2vDtKgLmgmzFWrrQ) 0):
	{
		tyObject_FauEvent__YNvUGRpkmCiP22cM2l29bkQ T2_;
		nimZeroMem((void*)(&T2_), sizeof(tyObject_FauEvent__YNvUGRpkmCiP22cM2l29bkQ));
		T2_.kind = ((tyEnum_FauEventKind__xJFQo4JN2Z8swZKj8kGvYA) 0);
		T2_._kind_1.key = code;
		T2_._kind_1.keyDown = NIM_TRUE;
		fireFauEvent__OOZfauZsrcZfauZglobals_571(T2_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	break;
	case ((tyEnum_GLFMKeyAction__vh34eg2vDtKgLmgmzFWrrQ) 2):
	{
		tyObject_FauEvent__YNvUGRpkmCiP22cM2l29bkQ T4_;
		nimZeroMem((void*)(&T4_), sizeof(tyObject_FauEvent__YNvUGRpkmCiP22cM2l29bkQ));
		T4_.kind = ((tyEnum_FauEventKind__xJFQo4JN2Z8swZKj8kGvYA) 0);
		T4_._kind_1.key = code;
		T4_._kind_1.keyDown = NIM_FALSE;
		fireFauEvent__OOZfauZsrcZfauZglobals_571(T4_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	break;
	default:
	{
	}
	break;
	}
	result = NIM_FALSE;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_CDECL(void, colonanonymous___OOZfauZsrcZcore_117)(void** surf, int width, int height) {
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	NimStringV2 colontmpD__3;
	tyArray__nHXaesL0DJZHyVS07ARPRA T8_;
	NimStringV2 T9_;
	tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ T10_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
	{
		NIM_BOOL T4_;
		Exception* T7_;
		T4_ = (NIM_BOOL)0;
		T4_ = loadGl__OOZfauZsrcZcore_121(glfmGetProcAddress);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!!(T4_)) goto LA5_;
		T7_ = NIM_NIL;
		T7_ = (Exception*) nimNewObj(sizeof(Exception), NIM_ALIGNOF(Exception));
		(*T7_).Sup.m_type = (&NTIv2__XEycrCsme5C8CVWAYEcdBQ_);
		(*T7_).name = "Exception";
		(*T7_).message = TM__K9bwUuXws1Vn05sdTB9cnnxA_7;
		(*T7_).parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T7_, "Exception", ":anonymous", "glfmcore.nim", 84);
		goto LA1_;
	}
	LA5_: ;
	T9_.len = 0; T9_.p = NIM_NIL;
	colontmpD_ = dollar___systemZdollars_3(glVersionMajor__OOZfauZsrcZfauZglZglad_3);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	colontmpD__2 = dollar___systemZdollars_3(glVersionMinor__OOZfauZsrcZfauZglZglad_4);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T9_ = rawNewString(colontmpD_.len + colontmpD__2.len + 21);
appendString((&T9_), TM__K9bwUuXws1Vn05sdTB9cnnxA_9);
appendString((&T9_), colontmpD_);
appendString((&T9_), TM__K9bwUuXws1Vn05sdTB9cnnxA_11);
appendString((&T9_), colontmpD__2);
	colontmpD__3 = T9_;
	T8_[0] = colontmpD__3;
	echoBinSafe(T8_, 1);
	nimZeroMem((void*)(&T10_), sizeof(tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ));
	T10_ = vec2i__OOZfauZsrcZfauZfmath_428(((NI) (width)), ((NI) (height)));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	fau__OOZfauZsrcZfauZglobals_252.sizei = T10_;
	updateInsets__OOZfauZsrcZcore_40(surf);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	glInitialized__OOZfauZsrcZfauZglZglproc_8 = NIM_TRUE;
	cinitProc__OOZfauZsrcZcore_27.ClE_0? cinitProc__OOZfauZsrcZcore_27.ClP_0(cinitProc__OOZfauZsrcZcore_27.ClE_0):((TM__K9bwUuXws1Vn05sdTB9cnnxA_12)(cinitProc__OOZfauZsrcZcore_27.ClP_0))();
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		eqdestroy___system_2592((&colontmpD__3));
		eqdestroy___system_2592((&colontmpD__2));
		eqdestroy___system_2592((&colontmpD_));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_CDECL(void, colonanonymous___OOZfauZsrcZcore_679)(void** display, double frameTime) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	cloopProc__OOZfauZsrcZcore_25.ClE_0? cloopProc__OOZfauZsrcZcore_25.ClP_0(cloopProc__OOZfauZsrcZcore_25.ClE_0):((TM__K9bwUuXws1Vn05sdTB9cnnxA_13)(cloopProc__OOZfauZsrcZcore_25.ClP_0))();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_CDECL(void, colonanonymous___OOZfauZsrcZcore_682)(void** display) {
	glInitialized__OOZfauZsrcZfauZglZglproc_8 = NIM_FALSE;
	exit(((NI) 0));
}
N_LIB_PRIVATE N_CDECL(void, colonanonymous___OOZfauZsrcZcore_684)(void** display, NIM_BOOL focused) {
	tyObject_FauEvent__YNvUGRpkmCiP22cM2l29bkQ T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&T1_), sizeof(tyObject_FauEvent__YNvUGRpkmCiP22cM2l29bkQ));
	T1_.kind = ((tyEnum_FauEventKind__xJFQo4JN2Z8swZKj8kGvYA) 5);
	T1_._kind_6.shown = focused;
	fireFauEvent__OOZfauZsrcZfauZglobals_571(T1_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_CDECL(void, glfmMain)(void** display) {
	double T1_;
	NimMain();
	glfmSetDisplayChrome(display, ((tyEnum_GLFMUserInterfaceChrome__DeDC6RscPPBwBTW8L0LFzA) 2));
	glfmSetDisplayConfig(display, ((tyEnum_GLFMRenderingAPI__m7gNWyYftn8SwRb0yBqEgw) 0), ((tyEnum_GLFMColorFormat__WFrUyds4f29bI3cr1Fk0dvA) 0), ((tyEnum_GLFMDepthFormat__CzlES7tOqhkveTpTGC0zWA) 0), ((tyEnum_GLFMStencilFormat__Qo5BysVT79bf4LUta4F4jsw) 0), ((tyEnum_GLFMMultisample__SIlDTvlE183jDOjkllQNrA) 0));
	T1_ = (double)0;
	T1_ = glfmGetDisplayScale(display);
	fau__OOZfauZsrcZfauZglobals_252.screenDensity = ((NF32) (T1_));
	glfmSetSurfaceErrorFunc(display, colonanonymous___OOZfauZsrcZcore_57);
	echoBinSafe(TM__K9bwUuXws1Vn05sdTB9cnnxA_4, 1);
	glfmSetSurfaceResizedFunc(display, colonanonymous___OOZfauZsrcZcore_61);
	glfmSetTouchFunc(display, colonanonymous___OOZfauZsrcZcore_86);
	glfmSetKeyFunc(display, colonanonymous___OOZfauZsrcZcore_110);
	glfmSetSurfaceCreatedFunc(display, colonanonymous___OOZfauZsrcZcore_117);
	glfmSetMainLoopFunc(display, colonanonymous___OOZfauZsrcZcore_679);
	glfmSetSurfaceDestroyedFunc(display, colonanonymous___OOZfauZsrcZcore_682);
	glfmSetAppFocusFunc(display, colonanonymous___OOZfauZsrcZcore_684);
}
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU32)(((NU) (x))) - (NU32)(((NU) (y))))));
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* cell;
		NI T5_;
		if (!!((p == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_716(((NI) (ptrdiff_t) (p)), ((NI) 4));
		cell = ((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T5_));
		{
			if (!((NI)((*cell).rc & ((NI) -8)) == ((NI) 0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
		LA8_: ;
		{
			(*cell).rc -= ((NI) 8);
		}
		LA6_: ;
	}
	LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZfauZsrcZcore_1556)(tyObject_Env_coredotnim_initFau___l4LlgMNZocbw43qa0PmLHw** dest) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest));
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest));
	}
	LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZfauZsrcZcore_1534)(tyObject_Env_coredotnim_initFau___l4LlgMNZocbw43qa0PmLHw* dest) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest).loopProc1.ClE_0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest).loopProc1.ClE_0);
	}
	LA4_: ;
	eqdestroy___system_2592((&(*dest).params2.title));
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLast((*dest).initProc3.ClE_0);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest).initProc3.ClE_0);
	}
	LA9_: ;
}
static N_INLINE(tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w, vec2__OOZfauZsrcZfauZfmath_446)(tyObject_Vec2i__Vb00liq4ISM4Oc07yydBJQ v) {
	tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w result;
	NI colontmpD_;
	NI colontmpD__2;
	nimZeroMem((void*)(&result), sizeof(tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w));
	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	nimZeroMem((void*)(&result), sizeof(tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w));
	colontmpD_ = v.x;
	result.x = ((NF32) (colontmpD_));
	colontmpD__2 = v.y;
	result.y = ((NF32) (colontmpD__2));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___OOZfauZsrcZcore_725)(tyObject_FauEvent__YNvUGRpkmCiP22cM2l29bkQ e) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	switch (e.kind) {
	case ((tyEnum_FauEventKind__xJFQo4JN2Z8swZKj8kGvYA) 0):
	{
		{
			if (!e._kind_1.keyDown) goto LA4_;
			keysJustDown__OOZfauZsrcZfauZinput_4[(e._kind_1.key)- 0] = NIM_TRUE;
			keysPressed__OOZfauZsrcZfauZinput_3[(e._kind_1.key)- 0] = NIM_TRUE;
		}
		goto LA2_;
		LA4_: ;
		{
			keysJustUp__OOZfauZsrcZfauZinput_5[(e._kind_1.key)- 0] = NIM_TRUE;
			keysPressed__OOZfauZsrcZfauZinput_3[(e._kind_1.key)- 0] = NIM_FALSE;
		}
		LA2_: ;
	}
	break;
	case ((tyEnum_FauEventKind__xJFQo4JN2Z8swZKj8kGvYA) 3):
	{
		fau__OOZfauZsrcZfauZglobals_252.scroll = e._kind_4.scroll;
	}
	break;
	case ((tyEnum_FauEventKind__xJFQo4JN2Z8swZKj8kGvYA) 4):
	{
		tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w T9_;
		fau__OOZfauZsrcZfauZglobals_252.sizei = e._kind_5.size;
		nimZeroMem((void*)(&T9_), sizeof(tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w));
		T9_ = vec2__OOZfauZsrcZfauZfmath_446(e._kind_5.size);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		fau__OOZfauZsrcZfauZglobals_252.size = T9_;
	}
	break;
	case ((tyEnum_FauEventKind__xJFQo4JN2Z8swZKj8kGvYA) 2):
	{
		{
			if (!e._kind_3.touchDown) goto LA13_;
			keysJustDown__OOZfauZsrcZfauZinput_4[(e._kind_3.touchButton)- 0] = NIM_TRUE;
			keysPressed__OOZfauZsrcZfauZinput_3[(e._kind_3.touchButton)- 0] = NIM_TRUE;
		}
		goto LA11_;
		LA13_: ;
		{
			keysJustUp__OOZfauZsrcZfauZinput_5[(e._kind_3.touchButton)- 0] = NIM_TRUE;
			keysPressed__OOZfauZsrcZfauZinput_3[(e._kind_3.touchButton)- 0] = NIM_FALSE;
		}
		LA11_: ;
		{
			if (!(e._kind_3.touchId < ((NI) 10))) goto LA18_;
			fau__OOZfauZsrcZfauZglobals_252.touches[(e._kind_3.touchId)- 0].pos = e._kind_3.touchPos;
			fau__OOZfauZsrcZfauZglobals_252.touches[(e._kind_3.touchId)- 0].down = e._kind_3.touchDown;
			{
				tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w T24_;
				if (!e._kind_3.touchDown) goto LA22_;
				fau__OOZfauZsrcZfauZglobals_252.touches[(e._kind_3.touchId)- 0].last = fau__OOZfauZsrcZfauZglobals_252.touches[(e._kind_3.touchId)- 0].pos;
				nimZeroMem((void*)(&T24_), sizeof(tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w));
				T24_.x = 0.0f;
				T24_.y = 0.0f;
				fau__OOZfauZsrcZfauZglobals_252.touches[(e._kind_3.touchId)- 0].delta = T24_;
			}
			LA22_: ;
		}
		LA18_: ;
	}
	break;
	case ((tyEnum_FauEventKind__xJFQo4JN2Z8swZKj8kGvYA) 1):
	{
		fau__OOZfauZsrcZfauZglobals_252.mouse = e._kind_2.dragPos;
		{
			if (!(e._kind_2.dragId < ((NI) 10))) goto LA28_;
			fau__OOZfauZsrcZfauZglobals_252.touches[(e._kind_2.dragId)- 0].pos = e._kind_2.dragPos;
		}
		LA28_: ;
	}
	break;
	case ((tyEnum_FauEventKind__xJFQo4JN2Z8swZKj8kGvYA) 5):
	{
		fau__OOZfauZsrcZfauZglobals_252.shown = e._kind_6.shown;
	}
	break;
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, initCore__OOZfauZsrcZcore_694)(tyProc__HzVCwACFYM9cx9aV62PdjtuA loopProc, tyProc__HzVCwACFYM9cx9aV62PdjtuA initProc, tyObject_FauInitParams__Z0pthJcpoAihemqm26DYFg params) {
	eqcopy___OOZfauZsrcZfauZdraw_430((&cloopProc__OOZfauZsrcZcore_25), loopProc);
	eqcopy___OOZfauZsrcZfauZdraw_430((&cinitProc__OOZfauZsrcZcore_27), initProc);
}
static N_INLINE(NF, min__system_2050)(NF x, NF y) {
	NF result;
	NF colontmpD_;
	NF colontmpD__2;
	result = (NF)0;
	colontmpD_ = (NF)0;
	colontmpD__2 = (NF)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (x <= y);
		if (T3_) goto LA4_;
		T3_ = !((y == y));
		LA4_: ;
		if (!T3_) goto LA5_;
		colontmpD_ = x;
		result = colontmpD_;
	}
	goto LA1_;
	LA5_: ;
	{
		colontmpD__2 = y;
		result = colontmpD__2;
	}
	LA1_: ;
	return result;
}
static N_INLINE(void, pluseq___OOZfauZsrcZfauZfmath_107)(NF32* x, NF32 y) {
	(*x) = ((NF32)((*x)) + (NF32)(y));
}
static N_INLINE(tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w, minus___OOZfauZsrcZfauZfmath_506)(tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w vecX60gensym19_, tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w otherX60gensym19_) {
	tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w result;
	tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w T1_;
	nimZeroMem((void*)(&result), sizeof(tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w));
	nimZeroMem((void*)(&T1_), sizeof(tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w));
	T1_.x = ((NF32)(vecX60gensym19_.x) - (NF32)(otherX60gensym19_.x));
	T1_.y = ((NF32)(vecX60gensym19_.y) - (NF32)(otherX60gensym19_.y));
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_CLOSURE(void, colonanonymous___OOZfauZsrcZcore_755)(void* ClE_0) {
	tyObject_Env_coredotnim_initFau___l4LlgMNZocbw43qa0PmLHw* colonenvP_;
	NI64 time;
	tyObject_Time__3y2ZpqsTJLqdZvpC9a0rU2Q T1_;
	tyObject_Duration__lj9ar6Co3fgk6NgGnVaNpJw T2_;
	NF T17_;
	tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w T30_;
	tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w T45_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colonenvP_ = (tyObject_Env_coredotnim_initFau___l4LlgMNZocbw43qa0PmLHw*) ClE_0;
	T1_ = getTime__pureZtimes_952();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T2_ = ntDiffTime(T1_, startTime__OOZfauZsrcZcore_717);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	time = inNanoseconds__pureZtimes_675(T2_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!(lastFrameTime__OOZfauZsrcZcore_714 == IL64(-1))) goto LA5_;
		lastFrameTime__OOZfauZsrcZcore_714 = time;
	}
	LA5_: ;
	{
		NF targetDelay;
		NF actualDelay;
		if (!!((fau__OOZfauZsrcZfauZglobals_252.targetFps == 0.0f))) goto LA9_;
		targetDelay = ((NF)(((NF) (((NF32)(1.0f) / (NF32)(fau__OOZfauZsrcZfauZglobals_252.targetFps))))) * (NF)(1000000000.0));
		actualDelay = ((NF) ((NI64)(time - lastFrameTime__OOZfauZsrcZcore_714)));
		{
			tyObject_Time__3y2ZpqsTJLqdZvpC9a0rU2Q T15_;
			tyObject_Duration__lj9ar6Co3fgk6NgGnVaNpJw T16_;
			if (!(actualDelay < targetDelay)) goto LA13_;
			nossleep(((NI) (((NF)(((NF)(targetDelay) - (NF)(actualDelay))) * (NF)(0.000001)))));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			T15_ = getTime__pureZtimes_952();
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			T16_ = ntDiffTime(T15_, startTime__OOZfauZsrcZcore_717);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			time = inNanoseconds__pureZtimes_675(T16_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		LA13_: ;
	}
	LA9_: ;
	fau__OOZfauZsrcZfauZglobals_252.rawDelta = ((NF)(((NF) ((NI64)(time - lastFrameTime__OOZfauZsrcZcore_714)))) / (NF)(1000000000.0));
	T17_ = (NF)0;
	T17_ = min__system_2050(fau__OOZfauZsrcZfauZglobals_252.rawDelta, ((NF) (fau__OOZfauZsrcZfauZglobals_252.maxDelta)));
	fau__OOZfauZsrcZfauZglobals_252.delta = ((NF32) (T17_));
	pluseq___OOZfauZsrcZfauZfmath_107((&fau__OOZfauZsrcZfauZglobals_252.time), fau__OOZfauZsrcZfauZglobals_252.delta);
	lastFrameTime__OOZfauZsrcZcore_714 = time;
	{
		if (!(IL64(1000000000) <= (NI64)(time - frameCounterStart__OOZfauZsrcZcore_715))) goto LA20_;
		fau__OOZfauZsrcZfauZglobals_252.fps = frames__OOZfauZsrcZcore_716;
		frames__OOZfauZsrcZcore_716 = ((NI) 0);
		frameCounterStart__OOZfauZsrcZcore_715 = time;
	}
	LA20_: ;
	{
		tyObject_Touch__O3vdnbkm84I9bOqV6XPOHdw* t;
		NI i;
		t = (tyObject_Touch__O3vdnbkm84I9bOqV6XPOHdw*)0;
		i = ((NI) 0);
		{
			while (1) {
				tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w T25_;
				t = (&fau__OOZfauZsrcZfauZglobals_252.touches[(i)- 0]);
				nimZeroMem((void*)(&T25_), sizeof(tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w));
				T25_ = minus___OOZfauZsrcZfauZfmath_506((*t).pos, (*t).last);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				(*t).delta = T25_;
				(*t).last = (*t).pos;
				{
					if (!(((NI) 9) <= ((NI) (i)))) goto LA28_;
					goto LA23;
				}
				LA28_: ;
				i += ((NI) 1);
			}
		} LA23: ;
	}
	frames__OOZfauZsrcZcore_716 += ((NI) 1);
	nimZeroMem((void*)(&T30_), sizeof(tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w));
	T30_ = vec2__OOZfauZsrcZfauZfmath_446(fau__OOZfauZsrcZfauZglobals_252.sizei);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	fau__OOZfauZsrcZfauZglobals_252.size = T30_;
	resize__OOZfauZsrcZfauZframebuffer_22(screen__OOZfauZsrcZfauZscreenbuffer_2, fau__OOZfauZsrcZfauZglobals_252.sizei);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	clear__OOZfauZsrcZfauZframebuffer_87(screen__OOZfauZsrcZfauZscreenbuffer_2, fau__OOZfauZsrcZfauZglobals_252.clearColor);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*colonenvP_).loopProc1.ClE_0? (*colonenvP_).loopProc1.ClP_0((*colonenvP_).loopProc1.ClE_0):((TM__K9bwUuXws1Vn05sdTB9cnnxA_15)((*colonenvP_).loopProc1.ClP_0))();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	drawFlush__OOZfauZsrcZfauZdraw_401();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	fau__OOZfauZsrcZfauZglobals_252.frameId += ((NI) 1);
	{
		NIM_BOOL* x;
		tyEnum_KeyCode__YhMyimscyfYwYiOPDuaH9bg i_2;
		x = (NIM_BOOL*)0;
		i_2 = ((tyEnum_KeyCode__YhMyimscyfYwYiOPDuaH9bg) 0);
		{
			while (1) {
				x = (&keysJustDown__OOZfauZsrcZfauZinput_4[(i_2)- 0]);
				(*x) = NIM_FALSE;
				{
					if (!(((tyEnum_KeyCode__YhMyimscyfYwYiOPDuaH9bg) 152) <= i_2)) goto LA36_;
					goto LA32;
				}
				LA36_: ;
				i_2 += ((NI) 1);
			}
		} LA32: ;
	}
	{
		NIM_BOOL* x_2;
		tyEnum_KeyCode__YhMyimscyfYwYiOPDuaH9bg i_3;
		x_2 = (NIM_BOOL*)0;
		i_3 = ((tyEnum_KeyCode__YhMyimscyfYwYiOPDuaH9bg) 0);
		{
			while (1) {
				x_2 = (&keysJustUp__OOZfauZsrcZfauZinput_5[(i_3)- 0]);
				(*x_2) = NIM_FALSE;
				{
					if (!(((tyEnum_KeyCode__YhMyimscyfYwYiOPDuaH9bg) 152) <= i_3)) goto LA43_;
					goto LA39;
				}
				LA43_: ;
				i_3 += ((NI) 1);
			}
		} LA39: ;
	}
	nimZeroMem((void*)(&T45_), sizeof(tyObject_Vec2__207B9cwFjt9a8ydWqYFfZZ2w));
	fau__OOZfauZsrcZfauZglobals_252.scroll = T45_;
	}BeforeRet_: ;
}
static N_INLINE(void, X5BX5D___OOZfauZsrcZfauZatlas_47)(tyObject_AtlascolonObjectType___5kuY28uezWLPxjw6Jjpi9ag* atlas, NimStringV2 name, tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA* Result) {
	tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&T1_), sizeof(tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA));
	getOrDefault__OOZfauZsrcZfauZatlas_117((*atlas).patches, name, (*atlas).error, (&T1_));
	(*Result) = T1_;
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_CLOSURE(void, colonanonymous___OOZfauZsrcZcore_869)(void* ClE_0) {
	tyObject_Env_coredotnim_initFau___l4LlgMNZocbw43qa0PmLHw* colonenvP_;
	tyObject_FramebufferObj__1pPqnr9cylF8gi9bULYcALCQ* T5_;
	tyObject_BatchcolonObjectType___RYPwJl20EVec0ujcBafF9aA* T6_;
	tyObject_CamcolonObjectType___4eTzE4gEL86vZ9bRFgwAN4A* T7_;
	tyObject_AtlascolonObjectType___5kuY28uezWLPxjw6Jjpi9ag* T8_;
	tyObject_MeshObj__cPggZRHFWvGLKpQsZMF8yA* T9_;
	tyObject_ShaderObj__KFmcUvp7lIrtBdspoRxLXw* T10_;
	tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA T11_;
	tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA T12_;
	tyTuple__wpFMp8IwxV6MlaM4GANJ0Q avg;
	tyTuple__0vYzovSm9aKYybyF8MRuBJQ _;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colonenvP_ = (tyObject_Env_coredotnim_initFau___l4LlgMNZocbw43qa0PmLHw*) ClE_0;
	randomize__pureZrandom_277();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	initAudio__OOZfauZsrcZfauZaudio_27();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	loadAudio__OOZfauZsrcZfauZaudio_384();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!(fau__OOZfauZsrcZfauZglobals_252.screenDensity <= 0.0001f)) goto LA3_;
		fau__OOZfauZsrcZfauZglobals_252.screenDensity = 1.0f;
	}
	LA3_: ;
	fau__OOZfauZsrcZfauZglobals_252.shown = NIM_TRUE;
	T5_ = NIM_NIL;
	T5_ = newDefaultFramebuffer__OOZfauZsrcZfauZframebuffer_82((*colonenvP_).params2.depth);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqsink___OOZfauZsrcZfauZframebuffer_76(&screen__OOZfauZsrcZfauZscreenbuffer_2, T5_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T6_ = NIM_NIL;
	T6_ = newBatch__OOZfauZsrcZfauZbatch_459(((NI) 4092));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqsink___OOZfauZsrcZfauZbatch_729(&fau__OOZfauZsrcZfauZglobals_252.batch, T6_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	fau__OOZfauZsrcZfauZglobals_252.pixelScl = 1.0f;
	fau__OOZfauZsrcZfauZglobals_252.maxDelta = 0.016666668f;
	screenMat__OOZfauZsrcZfauZdraw_409();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T7_ = NIM_NIL;
	T7_ = newCam__OOZfauZsrcZfauZfmath_1308(fau__OOZfauZsrcZfauZglobals_252.size);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqsink___OOZfauZsrcZfauZfmath_1326(&fau__OOZfauZsrcZfauZglobals_252.cam, T7_);
	T8_ = NIM_NIL;
	T8_ = loadAtlas__OOZfauZsrcZcore_870();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqsink___OOZfauZsrcZcore_1482(&fau__OOZfauZsrcZfauZglobals_252.atlas, T8_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T9_ = NIM_NIL;
	T9_ = newScreenMesh__OOZfauZsrcZfauZmesh_312();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqsink___OOZfauZsrcZfauZmesh_412(&fau__OOZfauZsrcZfauZglobals_252.quad, T9_);
	T10_ = NIM_NIL;
	T10_ = newShader__OOZfauZsrcZfauZshader_65(TM__K9bwUuXws1Vn05sdTB9cnnxA_17, TM__K9bwUuXws1Vn05sdTB9cnnxA_19);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqsink___OOZfauZsrcZfauZshader_1658(&fau__OOZfauZsrcZfauZglobals_252.screenspace, T10_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimZeroMem((void*)(&T11_), sizeof(tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA));
	X5BX5D___OOZfauZsrcZfauZatlas_47(fau__OOZfauZsrcZfauZglobals_252.atlas, TM__K9bwUuXws1Vn05sdTB9cnnxA_21, (&T11_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqsink___OOZfauZsrcZfauZpatch_31((&fau__OOZfauZsrcZfauZglobals_252.white), T11_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimZeroMem((void*)(&T12_), sizeof(tyObject_Patch__8QaUwC1IkZpFffoZ7KEkFA));
	X5BX5D___OOZfauZsrcZfauZatlas_47(fau__OOZfauZsrcZfauZglobals_252.atlas, TM__K9bwUuXws1Vn05sdTB9cnnxA_23, (&T12_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqsink___OOZfauZsrcZfauZpatch_31((&fau__OOZfauZsrcZfauZglobals_252.circle), T12_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	avg.Field0 = ((NF)(((NF) (((NF32)(fau__OOZfauZsrcZfauZglobals_252.white.u) + (NF32)(fau__OOZfauZsrcZfauZglobals_252.white.u2))))) / (NF)(2.0));
	avg.Field1 = ((NF)(((NF) (((NF32)(fau__OOZfauZsrcZfauZglobals_252.white.v) + (NF32)(fau__OOZfauZsrcZfauZglobals_252.white.v2))))) / (NF)(2.0));
	nimZeroMem((void*)(&_), sizeof(tyTuple__0vYzovSm9aKYybyF8MRuBJQ));
	_.Field0 = avg.Field0;
	_.Field1 = avg.Field1;
	_.Field2 = avg.Field0;
	_.Field3 = avg.Field1;
	fau__OOZfauZsrcZfauZglobals_252.white.u = ((NF32) (_.Field0));
	fau__OOZfauZsrcZfauZglobals_252.white.v = ((NF32) (_.Field1));
	fau__OOZfauZsrcZfauZglobals_252.white.u2 = ((NF32) (_.Field2));
	fau__OOZfauZsrcZfauZglobals_252.white.v2 = ((NF32) (_.Field3));
	{
		if (!!(((*colonenvP_).initProc3.ClP_0 == TM__K9bwUuXws1Vn05sdTB9cnnxA_24.ClP_0 && (*colonenvP_).initProc3.ClE_0 == TM__K9bwUuXws1Vn05sdTB9cnnxA_24.ClE_0))) goto LA15_;
		(*colonenvP_).initProc3.ClE_0? (*colonenvP_).initProc3.ClP_0((*colonenvP_).initProc3.ClE_0):((TM__K9bwUuXws1Vn05sdTB9cnnxA_25)((*colonenvP_).initProc3.ClP_0))();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	LA15_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, initFau__OOZfauZsrcZcore_718)(tyProc__HzVCwACFYM9cx9aV62PdjtuA loopProc, tyProc__HzVCwACFYM9cx9aV62PdjtuA initProc, tyObject_FauInitParams__Z0pthJcpoAihemqm26DYFg params) {
	tyObject_Env_coredotnim_initFau___l4LlgMNZocbw43qa0PmLHw* colonenv_;
	tyProc__pYsVTQ4Z7hmuFG9c39aHjS9cw T1_;
	tyProc__HzVCwACFYM9cx9aV62PdjtuA T2_;
	tyProc__HzVCwACFYM9cx9aV62PdjtuA T3_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colonenv_ = NIM_NIL;
	eqdestroy___OOZfauZsrcZcore_1556(&colonenv_);
	colonenv_ = (tyObject_Env_coredotnim_initFau___l4LlgMNZocbw43qa0PmLHw*) nimNewObj(sizeof(tyObject_Env_coredotnim_initFau___l4LlgMNZocbw43qa0PmLHw), NIM_ALIGNOF(tyObject_Env_coredotnim_initFau___l4LlgMNZocbw43qa0PmLHw));
	(*colonenv_).Sup.m_type = (&NTIv2__l4LlgMNZocbw43qa0PmLHw_);
	eqcopy___OOZfauZsrcZfauZdraw_430((&(*colonenv_).loopProc1), loopProc);
	eqcopy___OOZfauZsrcZfauZdraw_430((&(*colonenv_).initProc3), initProc);
	eqcopy___OOZfauZsrcZfauZglobals_219((&(*colonenv_).params2), params);
	fau__OOZfauZsrcZfauZglobals_252.clearColor = (*colonenv_).params2.clearColor;
	nimZeroMem((void*)(&T1_), sizeof(tyProc__pYsVTQ4Z7hmuFG9c39aHjS9cw));
	T1_.ClP_0 = ((TM__K9bwUuXws1Vn05sdTB9cnnxA_14) (colonanonymous___OOZfauZsrcZcore_725)); T1_.ClE_0 = NIM_NIL;
	addFauListener__OOZfauZsrcZfauZglobals_603(T1_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimZeroMem((void*)(&T2_), sizeof(tyProc__HzVCwACFYM9cx9aV62PdjtuA));
	T2_.ClP_0 = colonanonymous___OOZfauZsrcZcore_755; T2_.ClE_0 = colonenv_;
	nimZeroMem((void*)(&T3_), sizeof(tyProc__HzVCwACFYM9cx9aV62PdjtuA));
	T3_.ClP_0 = colonanonymous___OOZfauZsrcZcore_869; T3_.ClE_0 = colonenv_;
	initCore__OOZfauZsrcZcore_694(T2_, T3_, (*colonenv_).params2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___OOZfauZsrcZcore_1556(&colonenv_);
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, fau_coreDatInit000)(void) {
NTIv2__l4LlgMNZocbw43qa0PmLHw_.destructor = (void*)eqdestroy___OOZfauZsrcZcore_1534; NTIv2__l4LlgMNZocbw43qa0PmLHw_.size = sizeof(tyObject_Env_coredotnim_initFau___l4LlgMNZocbw43qa0PmLHw); NTIv2__l4LlgMNZocbw43qa0PmLHw_.align = NIM_ALIGNOF(tyObject_Env_coredotnim_initFau___l4LlgMNZocbw43qa0PmLHw); NTIv2__l4LlgMNZocbw43qa0PmLHw_.name = "|fau.core.Env_core.nim_initFau|RootObj|";
; NTIv2__l4LlgMNZocbw43qa0PmLHw_.traceImpl = (void*)NIM_NIL; NTIv2__l4LlgMNZocbw43qa0PmLHw_.flags = 0;}

